[fx] change host-tool to exec
This prevents a recent regression where pm serve was not being killed
approprately when serve-updates exited.

Test: updated fx_host_tool_test to validate that 'fx host-tool <tool> &'
works as expected, and that 'kill $!' correctly kills the tool that
'fx host-tool <tool>' spawned.

Change-Id: Ief32790c6da6196fb614d59b36b925bb9f972028
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/471143
Commit-Queue: Renato Mangini Dias <mangini@google.com>
Reviewed-by: James Tucker <raggi@google.com>

diff --git a/tools/devshell/tests/subcommands/fx_host_tool_test b/tools/devshell/tests/subcommands/fx_host_tool_test
--- a/tools/devshell/tests/subcommands/fx_host_tool_test
+++ b/tools/devshell/tests/subcommands/fx_host_tool_test
@@ -116,5 +116,74 @@ TEST_firewall_check_fail() {
   btf::expect-mock-args "${macfw}.mock_state.2" "--getappblocked" "${devfinder}"
 }
 
+# test if sending the host-tool to the background and killing it effectively
+# kills it as expected.
+# the logic for this test is the following:
+#  - execute a custom fx command (mycmd)
+#  - 'fx mycmd' runs 'host-tool slow_tool' in the background, waits a bit and
+#    attempts to kill it with SIGINT, simulating a user Ctrl+C in the foreground
+#    command.
+#  - 'slow_tool' should be stopped and have a chance to clean up resources, in
+#    this case a lock file in a known location, which is checked as a condition
+#    for the test to succeeed.
+TEST_kill_bg_process() {
+  lockfile="${BT_TEMP_DIR}/.slow_tool.lock"
+  local frontend_cmd="${BT_TEMP_DIR}/tools/devshell/mycmd"
+  cat >"${frontend_cmd}" <<EOF
+  #!/bin/bash
+  source ${BT_TEMP_DIR}/tools/devshell/lib/vars.sh
+  fx-command-exec host-tool slow_tool &
+  pid=\$!
+  # give some time for slow_tool to create the lockfile
+  SECONDS=0
+  while [[ ! -f "$lockfile" ]] ; do
+    if [[ $SECONDS -gt 10 ]]; then
+      echo >&2 "ERROR, timed out waiting for lockfile to be created"
+      exit 1
+    fi
+  done
+
+  kill -SIGINT \$pid
+
+  SECONDS=0
+  while kill -0 \$pid >/dev/null 2>&1; do
+    if [[ $SECONDS -gt 10 ]]; then
+      echo >&2 "ERROR, timed out waiting for PID $pid to die"
+      exit 1
+    fi
+  done
+  exit $?
+EOF
+  chmod +x "${frontend_cmd}"
+
+  local slow_tool="$(btf::make_installed_hosttools_mock slow_tool)"
+  local slow_tool_rel="${slow_tool##${FUCHSIA_BUILD_DIR}/}"
+  cat >"${BT_TEMP_DIR}/tools/devshell/list-build-artifacts.mock_side_effects" <<EOF
+    [[ \$2 == "slow_tool" ]] && echo ${slow_tool_rel} && exit 0
+    exit 1
+EOF
+  cat >"${slow_tool}.mock_side_effects" <<EOF
+  cleanup() {
+    local st=\$1
+    echo >&2 "cleanup executed, status \$st."
+    rm -f "$lockfile"
+    exit \$st
+  }
+  trap 'cleanup 0' SIGINT
+  touch "$lockfile"
+  c=0
+  while (( c < 10 )); do
+    sleep 1
+    echo >&2 "sleeping inside slow_tool"
+    (( c++ ))
+  done
+  echo >&2 "ERROR! timeout passed without slow_tool being killed: $slow_tool"
+  cleanup 1
+EOF
+
+  local _out="${BT_TEMP_DIR}/_out.log"
+  BT_EXPECT ${fx} mycmd >"$_out" 2>&1
+  BT_EXPECT_FILE_DOES_NOT_EXIST "$lockfile"
+}
 
 BT_RUN_TESTS "$@"
