[prebuilt] Update CIPD client and enable the use of resolved versions
This increases security by not relying on the server, instead we always
check the package hash against the digests file.

Change-Id: Ic2178e0b654224c420419d4553bcc2b35c6fcc94

diff --git a/cipd b/cipd
--- a/cipd
+++ b/cipd
@@ -7,8 +7,8 @@ set -eo pipefail; [[ "${TRACE}" ]] && set -x
 
 readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-readonly CIPD_CLIENT_VERSION="${CIPD_CLIENT_VERSION:-$(cat ${SCRIPT_DIR}/.cipd_version)}"
-readonly CIPD_CLIENT_URL="${CIPD_CLIENT_URL:-https://chrome-infra-packages.appspot.com}"
+readonly VERSION_FILE="${SCRIPT_DIR}/.cipd_version"
+readonly CIPD_BACKEND="https://chrome-infra-packages.appspot.com"
 
 declare HOST_PLATFORM="$(uname -s | tr '[:upper:]' '[:lower:]')"
 case "${HOST_PLATFORM}" in
@@ -19,7 +19,7 @@ case "${HOST_PLATFORM}" in
     readonly HOST_PLATFORM="mac"
     ;;
   *)
-    echo "Unknown operating system."
+    echo "Unknown operating system." >&2
     exit 1
 esac
 
@@ -35,48 +35,91 @@ case "${HOST_ARCH}" in
     readonly HOST_ARCH=386
     ;;
   *)
-    echo "Unknown machine architecture."
+    echo "Unknown machine architecture." >&2
     exit 1
 esac
 
-readonly URL="${CIPD_CLIENT_URL}/client?platform=${HOST_PLATFORM}-${HOST_ARCH}&version=${CIPD_CLIENT_VERSION}"
+readonly PLATFORM="${HOST_PLATFORM}-${HOST_ARCH}"
+readonly VERSION="$(cat ${VERSION_FILE})"
+readonly URL="${CIPD_BACKEND}/client?platform=${PLATFORM}&version=${VERSION}"
 readonly CLIENT="${SCRIPT_DIR}/.cipd_client"
 
 readonly USER_AGENT="buildtools/$(git -C ${SCRIPT_DIR} rev-parse HEAD 2>/dev/null || echo "???")"
 
-
-# clean_bootstrap bootstraps the client from scratch using 'curl'.
-function clean_bootstrap() {
-  echo "Bootstrapping cipd client for ${HOST_PLATFORM}-${HOST_ARCH}..."
-  local CLIENT_TMP="$(mktemp -p "${SCRIPT_DIR}" 2>/dev/null || mktemp "${SCRIPT_DIR}/.cipd_client.XXXXXXX")"
-  if hash curl 2> /dev/null ; then
-    curl -f --progress-bar "${URL}" -A "${USER_AGENT}"  -L -o "${CLIENT_TMP}"
-    chmod +x "${CLIENT_TMP}"
+function actual_sha256() {
+  if type shasum >/dev/null ; then
+    shasum -a 256 "$1" | cut -d' ' -f1
   else
-    echo "The \`curl\` command is missing, download ${URL} as ${CLIENT}, set +x, and then re-run this command" 1>&2
+    echo "The \`shasum\` command is missing. Please use your package manager to install it." >&2
+    return 1
+  fi
+}
+
+function expected_sha256() {
+  local line
+  while read -r line; do
+    if [[ "${line}" =~ ^([0-9a-z\-]+)[[:blank:]]+sha256[[:blank:]]+([0-9a-f]+)$ ]] ; then
+      local platform="${BASH_REMATCH[1]}"
+      local hash="${BASH_REMATCH[2]}"
+      if [[ "${platform}" ==  "$1" ]]; then
+        echo "${hash}"
+        return 0
+      fi
+    fi
+  done < "${VERSION_FILE}.digests"
+
+  echo "Platform $1 is not supported by the CIPD client bootstrap. There's no pinned hash for it in the *.digests file." >&2
+
+  return 1
+}
+
+# bootstraps the client from scratch using 'curl'.
+function bootstrap() {
+  local expected_hash="$(expected_sha256 "${PLATFORM}")"
+  if [[ -z "${expected_hash}" ]] ; then
     exit 1
   fi
-  mv "${CLIENT_TMP}" "${CLIENT}"
+
+  echo "Bootstrapping cipd client for ${HOST_PLATFORM}-${HOST_ARCH}..."
+  local CLIENT_TMP="$(mktemp -p "${SCRIPT_DIR}" 2>/dev/null || mktemp "${SCRIPT_DIR}/.cipd_client.XXXXXXX")"
+  if type curl >/dev/null ; then
+    curl -f --progress-bar "${URL}" -A "${USER_AGENT}"  -L -o "${CLIENT_TMP}"
+  else
+    echo "The \`curl\` command is missing. Please use your package manager to install it." >&2
+    exit 1
+  fi
+  trap "rm -f '${CLIENT_TMP}'" EXIT ERR HUP INT TERM
+
+  local actual_hash="$(actual_sha256 "${CLIENT_TMP}")"
+  if [[ -z "${actual_hash}" ]] ; then
+    exit 1
+  fi
+
+  if [[ "${actual_hash}" != "${expected_hash}" ]]; then
+    echo "SHA256 digest of the downloaded CIPD client is incorrect. Check that *.digests file is up-to-date." >&2
+    exit 1
+  fi
+
+  chmod +x "${CLIENT_TMP}"
+  mv -f "${CLIENT_TMP}" "${CLIENT}"
+  trap - EXIT
 }
 
 # self_update asks the existing client to update itself, if necessary.
 function self_update() {
-  "${CLIENT}" selfupdate -version "${CIPD_CLIENT_VERSION}" -service-url "${CIPD_CLIENT_URL}"
+  "${CLIENT}" selfupdate -version-file "${VERSION_FILE}" -service-url "${CIPD_BACKEND}"
 }
 
 if [[ ! -x "${CLIENT}" ]]; then
-  clean_bootstrap
+  bootstrap
 fi
 
 export CIPD_HTTP_USER_AGENT_PREFIX="${USER_AGENT}"
 if ! self_update ; then
-  echo -n "[31;1mCIPD selfupdate failed. " 1>&2
-  echo "Trying to bootstrap the CIPD client from scratch... [0m" 1>&2
-  clean_bootstrap
-  if ! self_update ; then  # need to run it again to setup .cipd_version file
-    echo -n "[31;1mBootstrap from scratch failed, something is seriously broken[0m " 1>&2
-    echo "run \`CIPD_HTTP_USER_AGENT_PREFIX=${USER_AGENT}/manual ${CLIENT} selfupdate -version '${CIPD_CLIENT_VERSION}'\` to diagnose if this is repeating." 1>&2
-    echo "[0m" 1>&2
+  echo "CIPD selfupdate failed. Trying to bootstrap the CIPD client from scratch..." >&2
+  bootstrap
+  if ! self_update ; then  # we need to run it again to setup .cipd_version file
+    echo "Bootstrap from scratch failed. Run \`CIPD_HTTP_USER_AGENT_PREFIX=${USER_AGENT}/manual ${CLIENT} selfupdate -version-file '${VERSION_FILE}'\` to diagnose if this is repeating." >&2
   fi
 fi
 
