[fx debug] some lint and simplifications
Change-Id: I4112937b97ea7ba16097b2cd5f76c2f388966ab9

diff --git a/scripts/devshell/debug b/scripts/devshell/debug
--- a/scripts/devshell/debug
+++ b/scripts/devshell/debug
@@ -46,7 +46,7 @@ while [[ "$1" =~ ^- ]]; do
       port="$1"
       ;;
     --verbose-agent|-va)
-      agent_out=""
+      agent_out="/dev/stdout"
       ;;
     --)
       shift
@@ -60,24 +60,22 @@ while [[ "$1" =~ ^- ]]; do
 done
 
 # Get the defaulted device address.
-target=$(fx-command-run "netaddr" "--fuchsia" "$(get-device-name)")
+target=$(get-fuchsia-device-addr)
 if [[ -z "${target}" ]]; then
-  # netaddr will have put the correct error message by now.
-  echo -e "Could not get a valid target. Run \"fx set-device\""
+  fx-error "Could not find fuchsia device" "$(get-device-name)"
   exit 1
 fi
 
 debug_agent_pkg="fuchsia-pkg://fuchsia.com/debug_agent#meta/debug_agent.cmx"
 
+fx_ssh_pid=""
+trap 'kill ${fx_ssh_pid}' EXIT
+
 # Leave the SSH connection open. Will be closed on script end.
 # We branch out on whether the user used the verbose-agent flag. If so, we
 # redirect the debug agent output to /dev/null.
 echo -e "Attempting to start the Debug Agent."
-if [[ -z "${agent_out}" ]]; then
-  (fx-command-run "ssh" "${target}" "run ${debug_agent_pkg} --port=${port}" &) &
-else
-  (fx-command-run "ssh" "${target}" "run ${debug_agent_pkg} --port=${port}" &) > "${agent_out}" 2>&1 &
-fi
+fx-command-run "ssh" "${target}" "run ${debug_agent_pkg} --port=${port}" > "${agent_out}" 2>&1 &
 fx_ssh_pid="$!"
 
 # We wait until the debug agent is listening on the given port. We use NC to
@@ -86,22 +84,17 @@ fx_ssh_pid="$!"
 # close the connection and receive the actual client's connection and work fine.
 try_count=0
 max_tries=10
-echo -e "Waiting for the Debug Agent to start."
+echo "Waiting for the Debug Agent to start."
 while true; do
   # Use NC to test if the port is open and the debug agent is listening.
-  cmd="nc -w5 -6 -z ${target} ${port}"  # Useful for printing when debugging.
-  ${cmd} > /dev/null 2>&1
-  # If successful, we proceed to connect.
-  if [[ "$?" -eq 0 ]]; then
+  if nc -w5 -6 -z "${target}" "${port}"; then
     break
   fi
 
   # Otherwise, we count and check if we need to exit.
   try_count=$(expr "${try_count}" + 1)
   if [[ "${try_count}" -gt "${max_tries}" ]]; then
-    echo -e "Timed out trying to find the Debug Agent. Exiting."
-    echo -e "Attempting to kill SSH connection."
-    kill "${fx_ssh_pid}"
+    fx-error "Timed out trying to find the Debug Agent. Exiting."
     exit 1
   fi
   sleep 1
