[fx][set] Switch to set2
After this CL, "fx set" runs the new set command, which was previously
called "set2". The old set command is available as "fx oldset".

Change-Id: Ic524231d86f3d3846a4a6b652367215601322816

diff --git a/scripts/devshell/set b/scripts/devshell/set
--- a/scripts/devshell/set
+++ b/scripts/devshell/set
@@ -1,79 +1,53 @@
 #!/bin/bash
-# Copyright 2017 The Fuchsia Authors. All rights reserved.
+# Copyright 2019 The Fuchsia Authors. All rights reserved.
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-### set up a build directory
+### set up a build directory (EXPERIMENTAL)
 
-## usage: fx set TARGET [OUTDIR]
-##               [--board NAME|PATH]
-##               [--product NAME|PATH]
-##               [--monolith PATH]
-##               [--preinstall PATH]
-##               [--available PATH]
-##               [--netboot]
+## usage: fx set PRODUCT.BOARD [--with GNLABEL1,GNLABEL2,...]
+##               [--release] [--build-dir BUILDDIR]
 ##               [--args ARG] [--help-args [ARG]] [--variant VARIANT]
-##               [--goma|--no-goma] [--no-ensure-goma]
-##               [--goma-dir DIR]
-##               [--ccache|--no-ccache]
-##               [--release]
-##               [--zircon-arg ARG]
+##               [--with-base GNLABEL1,GNLABEL2,...]
 ##
-## where TARGET is x64 or arm64
+## where PRODUCT is an entry from `//products` or `//vendor/*/products` and
+## BOARD is an entry from `//boards` or `//vendor/*/boards`. Use the
+## `fx list-products` and `fx list-boards` commands to see a list of
+## possible products and boards (respectively). See the README.md in those
+## directories for a description of the various options.
 ##
-## OUTDIR is the directory where the build output goes.
+## BUILDDIR is the directory where the build output goes.
 ## If it begins with `//` or `out/` then it's taken as relative to FUCHSIA_DIR.
 ## Otherwise it should be an absolute path or a path relative to the current
 ## working directory that winds up in `FUCHSIA_DIR/out`.
-## It defaults to `out/TARGET`.
+## It defaults to `out/default`.
 ##
-## This is a wrapper around running `gn gen --check OUTDIR --args ...`.
+## This command store the location of the build directory in the //.config file,
+## which causes subsequent `fx` commands to use that build directory. Use
+## `fx use` to switch build directories.
+##
+## Ensures Goma is ready (if Goma is enabled).
+##
+## This is a wrapper around running `gn gen --check BUILDDIR --args ...`.
 ## If GN fails with an error, `fx set` does not change anything.
-## If GN succeeds, this also points subsequent `fx` commands at OUTDIR,
-## just as `fx use` does and ensures Goma is ready (if enabled).
-##
-## NAME|PATH can be provided as arguments to --board and --product. In the
-## case of NAME the name is searched for in //layer/board/NAME.gni, otherwise it
-## is treated as a PATH.
 ##
 ## optional arguments:
-##   --board               Use the given board target definition. Board
-##                         configurations are used to modulate hardware specific
-##                         behavior, such as configuring the set of drivers
-##                         included, or adding peripheral specific configurations.
-##                         If no board is given, a default board for the architecture
-##                         is selected from the current layer, e.g.
-##                         garnet/boards/x64.gni.
-##   --product             Include the given product in the build. Defaults to
-##                         the default product for the current layer (e.g.,
-##                         "garnet/products/default.gni" for the Garnet layer).
-##                         Product configurations define a set of packages to be
-##                         included in the monolith, preinstall and available
-##                         package sets, as well as product oriented configurations.
-##   --monolith            Additional packages to be built and included in the
-##                         monolithic system image. Monolith is the set of packages
-##                         that make up an OTA image.
-##                         If the --monolith argument is given multiple times,
-##                         all the specified packages are included in this set.
-##                         These packages are added to the available set defined
-##                         by the board and product specifications.
-##   --preinstall          Additional packages to be built and included in the
-##                         system image alongside the monolithic system image.
-##                         Packages in preinstall are not part of OTA updates,
-##                         instead they are updated dynamically.
-##                         If the --preinstall argument is given multiple times,
-##                         all the specified packages are included in this set.
-##                         These packages are added to the available set defined
-##                         by the board and product specifications.
-##   --available           Additional packages to be built and included in the
-##                         set of packages available for pushing dynamically.
-##                         If the --available argument is given multiple times,
-##                         all the specified available are included in this set.
-##                         These packages are added to the available set defined
-##                         by the board and product specifications.
-##   --netboot             Ensure that a network ramboot image is always built.
-##   --variant             Pass a `select_variant=[VARIANT*,...]` GN build argument
-##                         collecting all the --variant arguments in order.
+##   --with GNLABEL        Labels of additional packages to include in the
+##                         universe of available packages. These packages can
+##                         be run ephemerally. Multiple labels can be provided
+##                         delimited by commas or the --with argument can be
+##                         provided multiple times.
+##   --variant             Selects which runtime variant to use (e.g., asan) by
+##                         passing a `select_variant=[VARIANT*,...]` argument
+##                         to gn that collects all the --variant arguments in
+##                         order. Variants are normal builds in most respects,
+##                         but allow users to test different runtime settings
+##                         for either the whole build or for a specific target.
+##                         This can be specified by passing the variant name
+##                         to this argument (e.g. `--variant asan`) for the
+##                         former, or the variant name and the target name
+##                         separated by a slash (e.g. `--variant asan/my_test`)
+##                         for the latter.
 ##   --fuzz-with           Pass a sanitizer name, e.g. "--fuzz-with asan" to
 ##                         enable ALL supporting fuzzers.  Use --variant for
 ##                         individual fuzzers, e.g. "--variant asan-fuzzer/foo".
@@ -86,10 +60,11 @@
 ##                         survive, for example, the shell. Thus when passing
 ##                         an argument that takes a string, pass it with
 ##                         something like --args=foo='"bar"'. E.g.,
-##                         bash$ fx set x64 --args=foo='"bar"'
+##                         bash$ fx set core.x64 --args=foo='"bar"'
 ##                         More complicated arguments, e.g., lists, require
 ##                         their own special syntax. See GN documentation
 ##                         for the syntax of each kind of argument.
+##   --netboot             Ensure that a network ramboot image is always built.
 ##   --help-args           Display GN arguments documentation.  If --help-args
 ##                         is followed by a GN build argument identifier, just
 ##                         that argument's documentation is displayed.
@@ -111,94 +86,94 @@
 ##                         files usable with that IDE. Useful values include "vs"
 ##                         for Visual Studio or "xcode" for Xcode.
 ##   --release             an alias for "--args=is_debug=false"
-##
-## Deprecated flags:
-##
-##   --zircon-arg ARG      Additional arguments to pass to build-zircon.sh.
-##                         Can be given multiple times.
+##   --with-base GNLABEL   Labels of additional packages to include in the
+##                         base set of packages. These packages are included in
+##                         the system image and can be updated only with an OTA.
+##                         Multiple labels can be provided delimited by commas
+##                         or the --with-base argument can be provided multiple
+##                         times.
 ##
 ## Example:
 ##
-##   $ fx set x64 kitchensink --product ermine --available topaz/packages/kitchen_sink
-##   -> architecture: x64
-##      build directory: out/kitchensink
-##      board: topaz/boards/x64.gni
-##      product: products/ermine.gni
-##      available: topaz/packages/kitchen_sink (all other packages)
+##   $ fx set core.x64 --with //bundles:tests
+##   -> build directory: out/default
+##      board: //boards/x64.gni
+##      product: //products/core.gni
+##      universe: //bundles:tests (all test packages)
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
 
-function guess_config_location {
+set -e
+
+function find_config {
   local config_type="$1"
   local config_name="$2"
-  local __resultvar="$3"
 
-  # If there is a vendor repository checked out, look there.
-  local vendor_repo
-  vendor_repo="$(${FUCHSIA_DIR}/build/gn/find_vendor_repo.py)" || return 1
-  readonly vendor_repo
-
-  if [[ -n "${vendor_repo}" ]]; then
-    guessed_config="${vendor_repo}/${config_type}/${config_name}.gni"
-    if [[ -a "${FUCHSIA_DIR}/${guessed_config}" ]]; then
-      eval "${__resultvar}"="${guessed_config}"
+  for directory in vendor/*/"${config_type}" "${config_type}"; do
+    local guessed_config="${directory}/${config_name}.gni"
+    if [[ -a "${guessed_config}" ]]; then
+      echo "${guessed_config}"
       return
     fi
-  fi
+  done
 
-  # Otherwise look at the top level location
-  # Check if the configuration is in the top-level location
-  guessed_config="${config_type}/${config_name}.gni"
-  if [[ -a "${FUCHSIA_DIR}/${guessed_config}" ]]; then
-    eval "${__resultvar}"="${guessed_config}"
-    return
-  fi
-
-  fx-error "Could not guess a ${config_type} configuration matching \"${config_name}\""
-  fx-error "Please specify the full path from the root of the checkout such as"
-  fx-error "${config_type}/core.gni"
+  fx-error "Could not find a ${config_type} configuration matching \"${config_name}\""
+  fx-error "Checked:"
+  for directory in vendor/*/"${config_type}" "${config_type}"; do
+    local guessed_config="${directory}/${config_name}.gni"
+    fx-error "  ${guessed_config}"
+  done
   exit 1
 }
 
+function explain-goal-argument {
+  fx-error You must specify which product and which board you wish to build.
+  fx-error Example:
+  fx-error "  fx set core.x64"
+  fx-error
+  fx-error Run \"fx list-products\" to see the available products.
+  fx-error Run \"fx list-boards\" to see the available boards.
+  fx-error Run \"fx set --help\" to see full usage.
+  return 0
+}
 
 function main {
   fx-standard-switches "$@"
   set -- "${FX_ARGV[@]}"
 
   if [[ $# -lt 1 ]]; then
-    fx-command-help
-    return 1
+      fx-error Missing an explicit PRODUCT.BOARD goal.
+      explain-goal-argument
+      return 1
   fi
 
-  local arch=
-  case $1 in
-    x64 | x86 | x64-64)
-      arch=x64
-      ;;
-    arm64 | aarch64)
-      arch=arm64
+  cd "${FUCHSIA_DIR}"
+
+  local gn_args=""
+  case "$1" in
+    *.*)
+      local product_name="${1%.*}"
+      local board_name="${1##*.}"
+      local product="$(find_config "products" "${product_name}")"
+      local board="$(find_config "boards" "${board_name}")"
+      gn_args+=" import(\"//${board}\") import(\"//${product}\")"
       ;;
     *)
-      # TODO(alainv): Add support for extracting arch from board configs.
-      fx-error Unknown target \"$1\"
-      fx-command-help
+      fx-error Unable to parse PRODUCT.BOARD goal \"$1\"
+      explain-goal-argument
       return 1
       ;;
   esac
   shift
 
-  cd "${FUCHSIA_DIR}"
+  local gn_args+=" allow_layer_guesswork=false"
 
   local gn_cmd='gen'
   local -a gn_switches=(--check)
-  local gn_args="target_cpu=\"${arch}\""
   local gn_after_args=""
-  local boards=()
-  local products=()
-  local available=()
-  local preinstall=()
-  local monolith=()
-  local zircon_args=(-v -g -t "$arch")
+  local base=()
+  local universe=()
+  local zircon_args=(-v -g)
   local build_dir=
   local variant=
   local use_goma
@@ -207,53 +182,20 @@ function main {
   local ccache
   while [[ $# -ne 0 ]]; do
     case "$1" in
-      --board)
+      --with-base)
         if [[ $# -lt 2 ]]; then
           fx-command-help
           return 1
         fi
-        boards+=("$2")
+        IFS=, base+=("$2")
         shift
         ;;
-      --product)
+      --with)
         if [[ $# -lt 2 ]]; then
           fx-command-help
           return 1
         fi
-        products+=("$2")
-        shift
-        ;;
-      --available)
-        if [[ $# -lt 2 ]]; then
-          fx-command-help
-          return 1
-        fi
-        IFS=, available+=("$2")
-        shift
-        ;;
-      --preinstall)
-        if [[ $# -lt 2 ]]; then
-          fx-command-help
-          return 1
-        fi
-        IFS=, preinstall+=("$2")
-        shift
-        ;;
-      --monolith)
-        if [[ $# -lt 2 ]]; then
-          fx-command-help
-          return 1
-        fi
-        IFS=, monolith+=("$2")
-        shift
-        ;;
-      --zircon-arg)
-        fx-warn "--zircon-arg is deprecated, common use case is no longer required"
-        if [[ $# -lt 2 ]]; then
-          fx-command-help
-          return 1
-        fi
-        zircon_args+=("$2")
+        IFS=, universe+=("$2")
         shift
         ;;
       --netboot)
@@ -275,9 +217,17 @@ function main {
         fi
         goma_dir=$2
         if [[ ! -d "${goma_dir}" ]]; then
-          fx-error "GOMA directory does not exist: "${goma_dir}""
+          fx-error "GOMA directory does not exist: ${goma_dir}"
           return 1
         fi
+        shift
+        ;;
+      --build-dir)
+        if [[ $# -lt 2 ]]; then
+          fx-command-help
+          return 1
+        fi
+        build_dir="$2"
         shift
         ;;
       --release)
@@ -330,38 +280,14 @@ function main {
         gn_switches+=("--ide=$2")
         shift
         ;;
-      --*)
+      *)
+        fx-error "Unknown argument \"$1\""
         fx-command-help
         return 1
-        ;;
-      *)
-        # A non-option argument is the build_dir, but there can be only one.
-        if [[ -n "$build_dir" ]]; then
-          fx-command-help
-          return 1
-        fi
-        build_dir="$1"
         ;;
     esac
     shift
   done
-
-  if [[ -z "${products}" ]]; then
-    # This is the default logic GN would use, but if a user specified --netboot
-    # we would short-circuit the logic, so repeat it here.
-    local vendor_repo
-    vendor_repo="$(${FUCHSIA_DIR}/build/gn/find_vendor_repo.py)" || return 1
-    readonly vendor_repo
-    if [[ -n "${vendor_repo}" ]]; then
-      products+="${vendor_repo}/products/default.gni"
-    else
-      products+="products/core.gni"
-    fi
-  fi
-
-  if [[ -z "${boards}" ]]; then
-    boards="boards/$arch.gni"
-  fi
 
   # Remove any trailing slash from build directory name.
   build_dir="${build_dir%/}"
@@ -369,8 +295,8 @@ function main {
   local config_build_dir
   case "$build_dir" in
     '')
-      # Default is "//out/$target_cpu".  Store it as relative.
-      config_build_dir="out/${arch}"
+      # Default is "//out/default".  Store it as relative.
+      config_build_dir="out/default"
       build_dir="${FUCHSIA_DIR}/${config_build_dir}"
       ;;
     //*|out/*)
@@ -379,18 +305,9 @@ function main {
       build_dir="${FUCHSIA_DIR}/${config_build_dir}"
       ;;
     *)
-      # Absolute or relative path.  Canonicalize it to source-relative.
-      local abs_build_dir
-      abs_build_dir="$(cd "${build_dir%/*}" >/dev/null 2>&1; pwd)/${build_dir##*/}" || {
-        fx-error "Missing parent directories for ${build_dir}"
-        return 1
-      }
-      if [[ "$abs_build_dir" == "${FUCHSIA_DIR}"/out/* ]]; then
-        config_build_dir="${abs_build_dir#${FUCHSIA_DIR}/}"
-      else
-        fx-warn "${abs_build_dir} is not a subdirectory of ${FUCHSIA_DIR}/out"
-        config_build_dir="$abs_build_dir"
-      fi
+      fx-error "Invalid build directory: ${build_dir}"
+      fx-error "Please specify a build directory as \"out/something\"."
+      exit 1
       ;;
   esac
 
@@ -408,19 +325,6 @@ function main {
     fi
   fi
 
-  if [[ -z "${boards}" ]]; then
-    guess_config_within_layer "boards" "${arch}" boards
-  fi
-
-  for board in ${boards[@]}; do
-    if [[ ! -f "${FUCHSIA_DIR}/${board}" ]]; then
-      local guessed_board=""
-      guess_config_location "boards" "${board}" guessed_board
-      board="${guessed_board}"
-    fi
-    gn_args+=" import(\"//${board}\")"
-  done
-
   # Add goma or ccache settings as appropriate.
   if [[ "${use_goma}" -eq 1 ]]; then
     gn_args+=" use_goma=true goma_dir=\"${goma_dir}\""
@@ -429,31 +333,22 @@ function main {
     gn_args+=" use_ccache=true"
   fi
 
-  for product in ${products[@]}; do
-    if [[ ! -a "${FUCHSIA_DIR}/${product}" ]]; then
-      local guessed_product=""
-      guess_config_location "products" "${product}" guessed_product
-      product="${guessed_product}"
-    fi
-    gn_args+=" import(\"//${product}\")"
-  done
+  gn_args+="
+# See: fx args --list=base_package_labels
+base_package_labels+=["
 
-  gn_args+=" if (!defined(available)) { available = [] }"
-  gn_args+=" available+=["
-  for package in ${available[@]}; do
+  for package in ${base[@]}; do
     gn_args+="\"${package}\","
   done
-  gn_args+="]"
+  gn_args+="]
 
-  gn_args+=" if (!defined(preinstall)) { preinstall = [] }"
-  gn_args+=" preinstall+=["
-  for package in ${preinstall[@]}; do
-    gn_args+="\"${package}\","
-  done
-  gn_args+="]"
-  gn_args+=" if (!defined(monolith)) { monolith = [] }"
-  gn_args+=" monolith+=["
-  for package in ${monolith[@]}; do
+# See: fx args --list=cache_package_labels
+cache_package_labels+=[]
+
+# See: fx args --list=universe_package_labels
+universe_package_labels+=["
+
+  for package in ${universe[@]}; do
     gn_args+="\"${package}\","
   done
   gn_args+="]"
@@ -464,18 +359,11 @@ function main {
 
   gn_args+="${gn_after_args}"
 
-  # Using a subshell with -x prints out the gn command precisely with shell
-  # quoting so a cut&paste to the command line works.  Always show the real
-  # meaning of what this script does so everyone learns how GN works.
-  (
-    set -x -e
-    # Zircon's `gn gen` phase has to be done before Fuchsia's `gn gen`.
-    # The former produces the legacy-$cpu.json file consumed by the latter.
-    "${FUCHSIA_DIR}/scripts/build-zircon.sh" "${zircon_args[@]}"
-    "${FUCHSIA_DIR}/buildtools/gn" ${gn_cmd} "${build_dir}" \
-                                   "${gn_switches[@]}" --args="${gn_args}" "$@"
-  # If GN failed, don't update .config.
-  ) || return
+  # Zircon's `gn gen` phase has to be done before Fuchsia's `gn gen`.
+  # The former produces the legacy-$cpu.json file consumed by the latter.
+  "${FUCHSIA_DIR}/scripts/build-zircon.sh" "${zircon_args[@]}"
+  "${FUCHSIA_DIR}/buildtools/gn" ${gn_cmd} "${build_dir}" \
+                                  "${gn_switches[@]}" --args="${gn_args}" "$@"
 
   fx-config-write "${config_build_dir}"
 
