[fx] introduce fx-error and fx-warn with colors
fx-error prints ERROR: and it's arguemnts to stderr, with the prefix colored
red if stderr is a terminal.
fx-warn prints WARNING: and it's arguemnts to stderr, with the prefix colored
yellow if stderr is a terminal.

test -t is known to be imperfect, however, it should be sufficiently portable
to be usable for now without otherwise going off the deep end.

This should help to make errors and warnings stand out in output for a large
group of users.

Change-Id: Ib7fdee3ca677bfd27e4a3a64d39ecc9a812bfeab

diff --git a/scripts/devshell/update-rustc-third-party b/scripts/devshell/update-rustc-third-party
--- a/scripts/devshell/update-rustc-third-party
+++ b/scripts/devshell/update-rustc-third-party
@@ -21,15 +21,16 @@ source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.
 case "$(uname -s)" in
   Linux*) OS=linux-x64;;
   Darwin*) OS=mac-x64;;
-  *) echo "Error: unrecognized OS"; exit 1;;
+  *) fx-error "unrecognized OS"; exit 1;;
 esac
 
 declare -x PATH=$FUCHSIA_DIR/buildtools/$OS/cmake/bin:$PATH
 
 if [[ "$OS" = "mac-x64" ]]; then
   if ! [[ -x "$(command -v brew)" ]]; then
-    echo >&2 "'brew' binary not found"
-    echo >&2 "A homebrew <https://brew.sh> installation of opensslis required in order to update"       echo >&2 "Rust third party crates on the Mac."
+    fx-error "'brew' binary not found"
+    fx-error "A homebrew <https://brew.sh> installation of opensslis required in order to update"
+    fx-error "Rust third party crates on the Mac."
     exit 1
   fi
 
