[fx][ffx] Optionally use ffx repository serve to implement fx serve-updates
This sets in an opt-in feature to switch from using `pm` for the
repository server over to using `ffx`. This is opt-in because we lack
the following features:

* ffx does not yet support the `--persist` flag
* ffx does not allow the port to be configured.

Fixed: 75500
Bug: 78985

Change-Id: I9a137ca7266e76245be2727ef57964bf009163ac
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/539171
Reviewed-by: Dan Johnson <computerdruid@google.com>
Reviewed-by: James Tucker <raggi@google.com>
Reviewed-by: Jordon Wing <jwing@google.com>
Commit-Queue: Erick Tryzelaar <etryzelaar@google.com>

diff --git a/tools/devshell/add-update-source b/tools/devshell/add-update-source
--- a/tools/devshell/add-update-source
+++ b/tools/devshell/add-update-source
@@ -40,7 +40,7 @@ function main {
   set -- "${FX_ARGV[@]}"
 
   addr=""
-  port="8083"
+  port=""
   source_name="devhost"
   persist=""
   while [[ $# -ne 0 ]]; do
@@ -73,61 +73,107 @@ function main {
     shift
   done
 
-  if [[ -z "${addr}" ]]; then
-    addr=$(fx-command-run shell 'echo $SSH_CONNECTION' | cut -d ' ' -f 1)
-    if [[ $? -ne 0 || -z "${addr}" ]]; then
-      fx-error "unable to determine host address as seen from the target.  Is the target up?"
-      exit 1
+  if is_feature_enabled "legacy_serve"; then
+    if [[ -z "${port}" ]]; then
+      port="8083"
+    fi
+
+    if [[ -z "${addr}" ]]; then
+      addr=$(fx-command-run shell 'echo $SSH_CONNECTION' | cut -d ' ' -f 1)
+      if [[ $? -ne 0 || -z "${addr}" ]]; then
+        fx-error "unable to determine host address as seen from the target.  Is the target up?"
+        exit 1
+      fi
+    fi
+
+    addr="$(echo "${addr}" | sed 's/%/%25/g')"
+
+    # A poor mans heuristic for "is an ipv6 address", URL encase escape
+    # the address.
+    if [[ "${addr}" =~ : ]]; then
+      addr="[${addr}]"
+    fi
+
+    config_url="http://${addr}:${port}/config.json"
+
+    add_repo_args=(-n "${source_name}")
+    if [[ ! -z "${persist}" ]]; then
+      add_repo_args+=( "${persist}" )
+    fi
+    add_repo_args+=( "${config_url}" )
+
+    fx-command-run shell pkgctl repo add url "${add_repo_args[@]}"
+    err=$?
+
+    if [[ $err -ne 0 ]]; then
+      fx-error "Unable to register update source."
+      if [[ $err -eq 2 ]]; then
+        # The GET request failed.
+        fx-error " - Is 'fx serve' or 'fx serve-updates' running?"
+        fx-error " - Can the target reach ${config_url} ?"
+      fi
+      return "$err"
+    fi
+
+    rule="'{
+      \"version\": \"1\",
+      \"content\": [
+        {
+          \"host_match\": \"fuchsia.com\",
+          \"host_replacement\": \"${source_name}\",
+          \"path_prefix_match\": \"/\",
+          \"path_prefix_replacement\": \"/\"
+        }
+      ]
+    }'"
+
+    fx-command-run shell pkgctl rule replace json $rule
+    err=$?
+
+    if [[ $err -ne 0 ]]; then
+      fx-error "The repo has been set up, but there was an error setting the rewriting rule for ${source_name}: $rule"
+      fx-error "To remove the repo, run \"fx shell pkgctl repo rm fuchsia-pkg://${source_name}\"."
+      return $err
+    fi
+  else
+    # FIXME(http://fxbug.dev/77146): The tunnel is currently hardcoded to port
+    # [::1]:8085.
+    if [[ ! -z "${addr}" ]]; then
+      fx-error "Flag '--addr' is not yet supported by ffx repository serving"
+      fx-error "See http://fxbug.dev/77146 for more details."
+      return 1
+    fi
+
+    if [[ -z "${port}" ]]; then
+      port=8085
+    elif [[ "${port}" != "8085" ]]; then
+      fx-error "Flag '--port' is currently required to be 8085 by ffx repository serving"
+      fx-error "See http://fxbug.dev/77146 for more details."
+      return 1
+    fi
+
+    # FIXME(http://fxbug.dev/78901): ffx does not allow configuring repository
+    # persistence.
+    if [[ -z "{persist}" ]]; then
+      fx-error "Flag '--persist' is not yet supported by ffx repository serving"
+      fx-error "See http://fxbug.dev/78901 for more details."
+      return 1
+    fi
+
+    fx-command-run ffx repository add-from-pm "$source_name" "${FUCHSIA_BUILD_DIR}/amber-files"
+    err=$?
+    if [[ $err -ne 0 ]]; then
+      fx-error "The repository was not able to be added to ffx"
+      return $err
+    fi
+
+    fx-command-run ffx repository target register "$source_name"
+    err=$?
+    if [[ $err -ne 0 ]]; then
+      fx-error "The repository was unable to be added to the target device"
+      return $err
     fi
   fi
-
-  addr="$(echo "${addr}" | sed 's/%/%25/g')"
-
-  # A poor mans heuristic for "is an ipv6 address", URL encase escape
-  # the address.
-  if [[ "${addr}" =~ : ]]; then
-    addr="[${addr}]"
-  fi
-
-  config_url="http://${addr}:${port}/config.json"
-
-  fx-command-run shell pkgctl repo add url\
-    -n "${source_name}" \
-    "${persist}" \
-    "${config_url}"
-  err=$?
-
-  if [[ $err -ne 0 ]]; then
-    fx-error "Unable to register update source."
-    if [[ $err -eq 2 ]]; then
-      # The GET request failed.
-      fx-error " - Is 'fx serve' or 'fx serve-updates' running?"
-      fx-error " - Can the target reach ${config_url} ?"
-    fi
-    return "$err"
-  fi
-
-  rule="'{
-    \"version\": \"1\",
-    \"content\": [
-      {
-        \"host_match\": \"fuchsia.com\",
-        \"host_replacement\": \"${source_name}\",
-        \"path_prefix_match\": \"/\",
-        \"path_prefix_replacement\": \"/\"
-      }
-    ]
-  }'"
-
-  fx-command-run shell pkgctl rule replace json $rule
-  err=$?
-
-  if [[ $err -ne 0 ]]; then
-    fx-error "The repo has been set up, but there was an error setting the rewriting rule for ${source_name}: $rule"
-    fx-error "To remove the repo, run \"fx shell pkgctl repo rm fuchsia-pkg://${source_name}\"."
-    return $err
-  fi
-
 }
 
 main "$@"
diff --git a/tools/devshell/serve-updates b/tools/devshell/serve-updates
--- a/tools/devshell/serve-updates
+++ b/tools/devshell/serve-updates
@@ -36,7 +36,7 @@ function usage {
 fx-standard-switches "$@"
 set -- "${FX_ARGV[@]}"
 
-port="8083"
+port=""
 serve_flags=()
 verbose=false
 auto_config=true
@@ -87,12 +87,12 @@ if [[ "${verbose}" != true ]]; then
   serve_flags+=("-q")
 fi
 
-pm_srv_pid=
+background_pid=
 cleanup() {
-  if [[ -n "${pm_srv_pid}" ]]; then
-    if kill -0 "${pm_srv_pid}" 2> /dev/null; then
-      kill -TERM "${pm_srv_pid}" 2> /dev/null
-      wait "${pm_srv_pid}" 2> /dev/null
+  if [[ -n "${background_pid}" ]]; then
+    if kill -0 "${background_pid}" 2> /dev/null; then
+      kill -TERM "${background_pid}" 2> /dev/null
+      wait "${background_pid}" 2> /dev/null
     fi
   fi
 }
@@ -179,28 +179,68 @@ else
   fi
 fi
 
-pm_serve_args=( serve -vt -repo "${repo_dir}" "${serve_flags[@]}" )
+if is_feature_enabled "legacy_serve"; then
+  # Default the port to 8083 if it is unset.
+  if [[ -z "${port}" ]]; then
+    port="8083"
+  fi
 
-# the manifest list file has relative paths and "pm serve" looks for them
-# from PWD, so pm command needs to be executed in "$FUCHSIA_BUILD_DIR"
-cd "${FUCHSIA_BUILD_DIR}"
+  pm_serve_args=( serve -vt -repo "${repo_dir}" "${serve_flags[@]}" )
+
+  # the manifest list file has relative paths and "pm serve" looks for them
+  # from PWD, so pm command needs to be executed in "$FUCHSIA_BUILD_DIR"
+  cd "${FUCHSIA_BUILD_DIR}"
+else
+  # FIXME(http://fxbug.dev/79636): ffx doesn't yet support incremental package building.
+  if is_feature_enabled "incremental"; then
+    fx-error "The feature 'incremental' is not supported yet by ffx"
+    fx-error "See http://fxbug.dev/79636 for more details."
+    exit 1
+  fi
+
+  # FIXME(http://fxbug.dev/77146): The tunnel is currently hardcoded to port
+  # 8085.
+  if [[ -z "${port}" ]]; then
+    port=8085
+  elif [[ "${port}" != "8085" ]]; then
+    fx-error "Flag '--port' is currently required to be 8085 by ffx repository serving"
+    fx-error "See http://fxbug.dev/77146 for more details."
+    exit 1
+  fi
+fi
 
 if [[ "${auto_config}" == false ]]; then
   log "Flag '--no-auto-config' used, automatic device configuration disabled."
   log "Use 'fx -d DEVICE add-update-source --port ${port}' to reconfigure devices as needed, since it is not persistent accross reboots."
   log "Serving packages on port ${port}..."
-  fx-command-exec host-tool pm "${pm_serve_args[@]}"
+
+  if is_feature_enabled "legacy_serve"; then
+    fx-command-exec host-tool pm "${pm_serve_args[@]}"
+  else
+    log "Repository is being served in the background by ffx"
+    exit 0
+  fi
 fi
 
-fx-command-exec host-tool pm "${pm_serve_args[@]}" &
-pm_srv_pid=$!
+if is_feature_enabled "legacy_serve"; then
+  fx-command-exec host-tool pm "${pm_serve_args[@]}" &
+  background_pid=$!
 
-# Allow a little slack for pm serve to startup, that way the first kill -0 will catch a dead server
-sleep 0.1
-if ! kill -0 "${pm_srv_pid}" 2> /dev/null; then
-  log "Server died, exiting"
-  wait
-  exit $?
+  # Allow a little slack for pm serve to startup, that way the first kill -0 will catch a dead server
+  sleep 0.1
+  if ! kill -0 "${background_pid}" 2> /dev/null; then
+    log "Server died, exiting"
+    wait
+    exit $?
+  fi
+else
+  if [[ "${verbose}" == true ]]; then
+    # FIXME(http://fxbug.dev/78891): `ffx daemon log` doesn't have a mechanism for
+    # filtering based off of a specific tag, so we'll grep for the lines that
+    # denote traffic to the web server.
+    fx-command-run ffx daemon log --follow --line-count 0 | grep ' \(pkg::repository::server\)\|\(ffx_daemon_service_repo\): ' &
+    background_pid=$!
+  fi
 fi
 
 log "Discovery..."
@@ -208,9 +248,13 @@ log "Discovery..."
 # State is used to prevent too much output
 state="discover"
 while true; do
-  if ! kill -0 "${pm_srv_pid}" 2> /dev/null; then
-    log "Server died, exiting"
-    pm_srv_pid=
+  if ! kill -0 "${background_pid}" 2> /dev/null; then
+    if is_feature_enabled "legacy_serve"; then
+      log "Server died, exiting"
+    else
+      log "Repository Server Logger died, exiting"
+    fi
+    background_pid=
     exit 1
   fi
 
