Revert "[pkg_resolver] Rewrite rules toggle amber sources"
This reverts commit e78ed1e2062564d3cf29d63ee5edf07f8dc5ba97.

Reason for revert: working out integration points

Original change's description:
> [pkg_resolver] Rewrite rules toggle amber sources
> 
> When pkg_resolver's rewrite rules change, it will now exclusively enable
> all matching amber sources with an equivalent ID, if there is a rewrite
> rule that rewrites all of fuchsia.com. Additionally, amberctl now
> enables and disables amber sources by managing rewrite rules.
> 
> Test: CQ
> PKG-743 #done
> 
> Change-Id: Id7f55798e2a572663db0016b20a804e08bf65798

TBR=jamesr@google.com,raggi@google.com,etryzelaar@google.com,kevinwells@google.com,computerdruid@google.com

Change-Id: I1278d55e85ab9cb9de392a00f0e9826afebd4398
No-Presubmit: true
No-Tree-Checks: true
No-Try: true

diff --git a/tools/devshell/add-update-source b/tools/devshell/add-update-source
--- a/tools/devshell/add-update-source
+++ b/tools/devshell/add-update-source
@@ -5,7 +5,7 @@
 
 ### register dev host as target's update source
 
-## usage: fx add-update-source [--type=TYPE] [--name=NAME]
+## usage: fx add-update-source [--type=TYPE] [--name=NAME] [--disable-source=NAME]
 ##
 ## Configure target device to use a new update source.
 ##
@@ -16,6 +16,7 @@
 ## update source.
 ##
 ## --name=NAME           Name the generated update source config NAME. Defaults to the config type.
+## --disable-source=NAME Disable the update source with NAME after adding the new update source.
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
 fx-config-read
@@ -31,6 +32,7 @@ function main {
   config_type="devhost"
   port="8083"
   source_name=""
+  disable_source=""
   while [[ $# -ne 0 ]]; do
     case "$1" in
       --port)
@@ -43,6 +45,10 @@ function main {
         ;;
       --name)
         source_name="$2"
+        shift
+        ;;
+      --disable-source)
+        disable_source="$2"
         shift
         ;;
       *)
@@ -93,6 +99,11 @@ function main {
       echo >&2 " - Can the target reach the development host on tcp port 8083?"
     fi
     return "$err"
+  fi
+
+  if [[ -n "${disable_source}" ]]; then
+    # Best effort, don't show status or fail on error
+    fx-command-run shell amberctl disable_src -n "${disable_source}" >/dev/null 2>/dev/null || true
   fi
 }
 
