[serve-updates] Don't error out for custom ports.
We now support alternative port configurations.

Change-Id: Ie844bf256b8c29bae1304b14dea5f2faaf073e4c
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/563206
Reviewed-by: Erick Tryzelaar <etryzelaar@google.com>
Commit-Queue: Erick Tryzelaar <etryzelaar@google.com>
Fuchsia-Auto-Submit: Erick Tryzelaar <etryzelaar@google.com>

diff --git a/tools/devshell/add-update-source b/tools/devshell/add-update-source
--- a/tools/devshell/add-update-source
+++ b/tools/devshell/add-update-source
@@ -151,9 +151,19 @@ function main {
 
     if [[ -z "${port}" ]]; then
       port=8085
-    elif [[ "${port}" != "8085" ]]; then
-      fx-error "Flag '--port' is currently required to be 8085 by ffx repository serving"
-      fx-error "See http://fxbug.dev/77146 for more details."
+    fi
+
+    config_addr=$(fx-command-run ffx config get repository.server.listen)
+    err=$?
+    if [[ $err -ne 0 ]]; then
+      fx-error "Unable to get the configured repository server address."
+      return "$err"
+    fi
+
+    if [[ "$config_addr" != "\"[::1]:$port\"" ]]; then
+      fx-error "The repository server is configured to use $config_addr."
+      fx-error "To switch to a different address, run:"
+      fx-error "$ ffx config set repository.server.listen \"[::1]:${port}\" && ffx doctor --restart-daemon"
       return 1
     fi
 
