[fx build] Frankenbuild cleanup
Remove a lingering build-zircon.sh reference.  When `fx build` finds a
missing Zircon build directory, re-run `gn gen` to create it first.

Bug: BLD-424 #comment fx build cleanup for transition
Change-Id: Ic3ef10dc46fe937fd1b5f43bea1640dcbf993be7

diff --git a/tools/devshell/build b/tools/devshell/build
--- a/tools/devshell/build
+++ b/tools/devshell/build
@@ -51,6 +51,11 @@ function main {
     shift
   done
 
+  if [ ! -d "$ZIRCON_BUILDROOT" ]; then
+    echo >&2 "Re-running gn gen first (missing $ZIRCON_BUILDROOT)"
+    fx-gen || return
+  fi
+
   # Build requested Zircon targets.
   # Add default if building any Fuchsia targets.
   if [ ${#fuchsia_targets[@]} -ne 0 ]; then
