[femu] Support custom local port for emu-remote.
Now user can specify custom local port by adding "--port PORT"
argument to "fx emu-remote" command, in case the default 8080
port is used by other processes.

TEST=`fx emu-remote --port 9999 liyl`

Change-Id: Ia93c876d012b3641e7ae8af4ef4096f372bdb4ba
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/377148
Reviewed-by: James Tucker <raggi@google.com>
Reviewed-by: David Reveman <reveman@google.com>
Commit-Queue: Yilong Li <liyl@google.com>
Testability-Review: David Reveman <reveman@google.com>

diff --git a/tools/devshell/emu-remote b/tools/devshell/emu-remote
--- a/tools/devshell/emu-remote
+++ b/tools/devshell/emu-remote
@@ -6,7 +6,8 @@
 #### CATEGORY=Other
 ### Remotely run emulator
 
-## usage: fx emu-remote [--no-emu] [--no-turn] [--no-open] [--display DPY] HOST [DIR] [-- ARGS]
+## usage: fx emu-remote [--no-emu] [--no-turn] [--no-open] [--display DPY]
+## [--port PORT] HOST [DIR] [-- ARGS]
 ##
 ## Connect to HOST, run a build using fx from DIR, start the emulator,
 ## and open WebRTC connection using local browser.
@@ -15,6 +16,7 @@
 ##  --no-turn     do not use turn configuration
 ##  --no-open     do not open https://web-femu.appspot.com, just run emulator
 ##  --display DPY do not start virtual display, use DPY instead
+##  --port PORT   port used on local machine to connect with emulator over HTTP (default: 8080).
 ##
 ##  HOST          the hostname to connect to
 ##  DIR           defaults to ~/fuchsia, the path to the FUCHSIA_DIR on HOST
@@ -29,6 +31,8 @@ open=true
 display="xvfb-run"
 host=""
 dir=""
+local_port="8080"
+remote_port="8080"
 while [[ $# -ne 0 ]]; do
   case "$1" in
   --help|-h)
@@ -48,8 +52,12 @@ while [[ $# -ne 0 ]]; do
     shift
     display="DISPLAY=$1"
     ;;
+  --port)
+    shift
+    local_port=$1
+    ;;
   --)
-	shift
+    shift
     break
     ;;
   *)
@@ -84,6 +92,34 @@ if "${emu}"; then
   fi
 fi
 
+# Check if the port given in argument "$1" is listened by other processes.
+#
+# Returns true if other process is already listening to this port; otherwise
+# returns false.
+is_port_used() {
+  # Print all listening ports and check if $1 is listed.
+  if [[ "$(uname -s)" == "Darwin" ]]; then
+    # On macOS we parse output from `netstat`.
+    netstat -anp tcp 2>/dev/null |
+    awk '$1 ~ /tcp4/ && $6 == "LISTEN" { \
+      sub(/.*\./, "", $4); print $4 \
+    }'
+  else
+    # On Linux we parse output from `ss`.
+    ss -lpn4 2>/dev/null | awk '$1 == "tcp" { \
+      if (match($5, /^[0-9.]+:[0-9]+$/)) { \
+        sub(/^.*:/, "", $5); print $5 \
+      } \
+    }'
+  fi | grep -q "^$1$"
+}
+
+if is_port_used ${local_port}; then
+  fx-error "Local port ${local_port} is not available. Please try specifying"\
+           "a different port using --port flag."
+  exit 1
+fi
+
 echo "Using remote ${host}:${dir}"
 
 # First we need to check if we already have a control master for the
@@ -96,7 +132,7 @@ if ! ssh -O check "${host}" > /dev/null 2>&1; then
   # forward, so we'll check for that and speculatively attempt to clean
   # it up. Unfortunately this means authing twice, but it's likely the
   # best we can do for now.
-  if ssh "${host}" 'ss -ln | grep :8080' > /dev/null; then
+  if ssh "${host}" "ss -ln | grep :${remote_port}" > /dev/null; then
     ssh "${host}" 'pkill -u $USER sshd'
     ssh "${host}" -O exit > /dev/null 2>&1
   fi
@@ -110,8 +146,8 @@ wait_and_open() {
   while true
   do
     # Check if we can connect to the forwarded port.
-    if curl -sI http://localhost:8080 > /dev/null; then
-      open_args=("https://web-femu.appspot.com/")
+    if curl -sI "http://localhost:${local_port}" > /dev/null; then
+      open_args=("https://web-femu.appspot.com/?port=${local_port}")
 
       # Launch Chrome browser tab for emulator feed.
       if [[ "$(uname -s)" == "Darwin" ]]; then
@@ -136,7 +172,8 @@ wait_and_open() {
 
 ssh_args=(
   -6 # We want ipv6 binds for the port forwards.
-  -L "\*:8080:localhost:8080" # Requests to the WebRTC service address locally go to the workstation.
+  # Requests to the WebRTC service address locally go to the workstation.
+  -L "${local_port}:localhost:${remote_port}"
   -o ExitOnForwardFailure=yes
   "${host}"
 )
@@ -149,7 +186,7 @@ if "${emu}"; then
     ssh "$host" 'pkill -u $USER qemu-system; pkill -u $USER goldfish-webrtc'
   fi
 
-  emu_args=(-x 8080)
+  emu_args=(-x ${remote_port})
 
   # Add turn configuration if enabled.
   if "${turn}"; then
@@ -169,4 +206,23 @@ else
   ssh_args+=("-nNT")
 fi
 
-exec ssh "${ssh_args[@]}"
+# Cleanup after ssh command ends:
+# - Terminate all child processes;
+# - Close port forwarding if we use ssh multiplexing.
+cleanup_processes_and_ports() {
+  child_pids=$(jobs -p)
+  if [[ -n "${child_pids}" ]]; then
+    # Note: child_pids must be expanded to args here.
+    kill ${child_pids} 2> /dev/null
+    wait 2> /dev/null
+  fi
+
+  # Cancel port forwarding.
+  if ssh -O check "${host}" > /dev/null 2>&1; then
+    ssh -O cancel -L "${local_port}:localhost:${remote_port}" "${host}"
+  fi
+}
+trap cleanup_processes_and_ports EXIT
+
+ssh "${ssh_args[@]}"
+
