[devshell] Enable ffx fastboot flash over remote
Update flash-remote to support fastboot flashing artifacts.

Test: fx --disable=legacy_fastboot flash-remote
Test: fx self-test subcommands/fx_remote_test

Bug: 71141
Change-Id: Ic01928cbb8c49b37010762fb3f49479bdb8a928f
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/493451
Reviewed-by: Renato Mangini Dias <mangini@google.com>
Reviewed-by: Matthew Boetger <boetger@google.com>
Commit-Queue: Dave Smith <smithdave@google.com>

diff --git a/tools/devshell/flash-remote b/tools/devshell/flash-remote
--- a/tools/devshell/flash-remote
+++ b/tools/devshell/flash-remote
@@ -94,11 +94,21 @@ fi
 
 save_remote_info "$host" "$dir"
 
+# Fetch remote flashing artifacts
 artifact_dir="${FUCHSIA_DIR}/out/fetched"
+flash_manifest=$(find_remote_build_artifact "${host}" "${dir}" flash-manifest images)
+
+if [[ -z "${flash_manifest}" ]]; then
+    fx-error "failed to find flash manifest on $host."
+    exit 1
+fi
+
 fetch_remote_build_artifacts "${host}" "${dir}" "${artifact_dir}" flash $build
+fetch_remote_artifacts "${host}" "${dir}" "${artifact_dir}" "${flash_manifest}"
 
 if "${flash}"; then
   fetch_or_build_tool ${host} ${dir} "${artifact_dir}" fastboot
   cd "${artifact_dir}"
-  fx-flash "${serial}" "${device}"
+  manifest_path="${artifact_dir}/${flash_manifest}"
+  fx-flash "${serial}" "${device}" "${manifest_path}"
 fi
