[fx host-tool] ensure build outputs to terminal
As host-tool is often used in a captured output capacity, the output
from a build would be disruptive. In order to avoid this problem, the
tool now checks to see if there is a controlling terminal, and if so,
redirect output to it. In the case where there is no controlling
terminal, or no terminal on stderr, the automatic build is skipped,
and an error is printed as if --no-build was passed.

Change-Id: I450b28778eca5927b4f1cbabb843fa31984aba1e
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/465402
Commit-Queue: James Tucker <raggi@google.com>
Reviewed-by: Renato Mangini Dias <mangini@google.com>
Fuchsia-Auto-Submit: James Tucker <raggi@google.com>

diff --git a/tools/devshell/host-tool b/tools/devshell/host-tool
--- a/tools/devshell/host-tool
+++ b/tools/devshell/host-tool
@@ -13,11 +13,14 @@
 ##    --no-build       does not attempt to build the tool if it does not exist
 ##    --check-firewall print a warning if the tool isn't included in firewall
 ##                     rules. This is a no-op outside of macOS.
-
+##
 ## If the tool is not known to the build system, for example if it is not in
 ## the GN build graph, a proper message will be printed and the script fails.
 ## This script is specially useful for other scripts, via fx-command-run,
 ## although it can also be used directly by final users.
+##
+## The tool will be built if host-tool is being run interactively,
+## otherwise an error will be produced if the tool is missing.
 
 set -e
 
@@ -80,24 +83,35 @@ shift
 # list-build-artifacts fails with a reasonable error message if tool is unknown
 toolpath="$(fx-command-run list-build-artifacts --name "${toolname}" --expect-one tools)"
 
+if [[ ! -f "${FUCHSIA_BUILD_DIR}/${toolpath}" ]]; then
+  # If the desire is to build, then it's important for the build to
+  # have stdout and stderr to print to. There are two possible
+  # conditions, one is that host-tool is being run with stdout going to
+  # a terminal, the other is that stdout is being captured, for example
+  # if the user is running `fx set-device`. In the latter case it is
+  # desirable to attach the build to the controlling terminal, if there
+  # is one. In the case where there is not, fall back to printing an
+  # error, as if --no-build was passed. If stderr is also redirected,
+  # then the build is cundontiionally skipped.
+  if ! fx-is-stderr-tty; then
+    build=false
+  fi
+
+  if ! $build; then
+    fx-error "Tool \"${toolname}\" is required by this command and has not been built."
+    fx-error "Please build it first: fx build ${toolpath}"
+    exit 2
+  fi
+
+  {
+    echo "Building required tool \"${toolpath}\"..."
+    fx-command-run build --no-zircon "${toolpath}" || exit $?
+  } 1>&2
+fi
+
 # Print a warning if the firewall doesn't allow this tool from running.
 if $check_firewall; then
   check_firewall_func "${FUCHSIA_BUILD_DIR}/${toolpath}"
-fi
-
-needs_build=false
-
-if [[ ! -f "${FUCHSIA_BUILD_DIR}/${toolpath}" ]]; then
-  if ! $build; then
-    fx-error "Tool does not exist and flag --no-build was used. Please build it first."
-    fx-error "  ${FUCHSIA_BUILD_DIR}/${toolpath}"
-    exit 2
-  fi
-  needs_build=true
-fi
-
-if $needs_build; then
-  fx-command-run build --no-zircon "${toolpath}"
 fi
 
 "${FUCHSIA_BUILD_DIR}/${toolpath}" "$@"
