[fx] add support to remote servers on symbolize
Added an argument to fx symbolize, fx log and fx klog to support
remote servers.

fx-symbolize was also removed as a shared function and its code was
moved to the symbolize command in order to thin out business logic in vars.sh

To test, run:
  fx self-test subcommands/fx_log_test subcommands/fx_klog_test subcommands/fx_symbolize_test

Fixed: 44083
Change-Id: I38fecf98439c5ed265397989e073a7e7a5db34de

diff --git a/tools/devshell/klog b/tools/devshell/klog
--- a/tools/devshell/klog
+++ b/tools/devshell/klog
@@ -4,11 +4,20 @@
 # found in the LICENSE file.
 
 #### CATEGORY=Run, inspect and debug
-### listen for kernel logs.
+### listen for kernel logs
 
+## usage: fx klog [--raw] [-r | --remote-symbols]
+##
+##    --raw                   do not attempt to symbolize the log
+##
+##    --remote-symbols|-r     attemp to resolve symbols using predefined remote
+##                            symbol servers for symbols that cannot be resolved
+##                            locally. See `fx help symbolize` for more
+##                            information on remote symbol servers.
+##
 ## This command delegates to the Zircon `loglistener` binary.
-## This will listen to the device specified with `fx set-device`; otherwise
-## one of the devices on the link-local network.
+## It will listen to the device specified with `fx -d DEVICE klog` or
+## `fx set-device`, otherwise one of the devices on the link-local network.
 
 set -e
 set -o pipefail
@@ -16,9 +25,41 @@ set -o pipefail
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
 fx-config-read
 
-if [[ $# > 0 && $1 = "--raw" ]]; then
+declare is_raw=0
+declare is_remote=0
+
+while [[ $# -ne 0 ]]; do
+  case "$1" in
+  -h|--help)
+    fx-command-help
+    exit 0
+    ;;
+  --raw)
+    is_raw=1
+    ;;
+  --remote-symbols|-r)
+    is_remote=1
+    ;;
+  *)
+    fx-error Invalid syntax
+    fx-command-help
+    exit 1
+  esac
   shift
+done
+
+if (( is_raw )) && (( is_remote )); then
+  fx-error "Invalid syntax: --raw and -r cannot be used together"
+  fx-command-help
+  exit 1
+fi
+
+if (( is_raw )); then
   exec "${ZIRCON_TOOLS_DIR}/loglistener" "$(get-device-name)"
 else
-  "${ZIRCON_TOOLS_DIR}/loglistener" "$(get-device-name)" | fx-symbolize
+  declare symbolizer=( "fx-command-run" "symbolize" )
+  if (( is_remote )); then
+    symbolizer+=("-r")
+  fi
+  "${ZIRCON_TOOLS_DIR}/loglistener" "$(get-device-name)" | "${symbolizer[@]}"
 fi
diff --git a/tools/devshell/log b/tools/devshell/log
--- a/tools/devshell/log
+++ b/tools/devshell/log
@@ -4,13 +4,25 @@
 # found in the LICENSE file.
 
 #### CATEGORY=Run, inspect and debug
-### listen for logs.
+### listen for logs from the on-device log_listener
 
-## usage: fx syslog [--raw] [flags]
+## usage: fx log [-h | --help] [--raw] [-r | --remote-symbols] LOG_LISTENER_FLAGS
+##
+##    --raw                   do not attempt to symbolize the log
+##
+##    --remote-symbols|-r     attemp to resolve symbols using predefined remote
+##                            symbol servers for symbols that cannot be resolved
+##                            locally. See `fx help symbolize` for more
+##                            information on remote symbol servers.
+##
+##    --help|-h               show this help and attempt to also show the
+##                            on-device log_listener help
+##
+##    LOG_LISTENER_FLAGS      bypass flags for the on-device log_listener
 ##
 ## Creates an SSH connection with a device and starts listening for logs.
-## Pass -h to get help with log-listener flags.
-## pass --raw as the first argument to get the raw, unsymbolized logs.
+## It will listen to the device specified with `fx -d DEVICE log` or
+## `fx set-device`, otherwise it will try to find a connected device.
 
 set -o pipefail
 
@@ -20,20 +32,51 @@ function listen {
   while true; do
     fx-command-run wait || return
     fx-command-run shell log_listener "$@"
-    echo "$(date '+%Y-%m-%d %H:%M:%S %Z'): Connection lost, reconnecting..."
+    local error_code=$?
+    if [[ "${error_code}" -eq 0 ]]; then
+      # this is necessary, so that "--dump_logs yes" works as expected.
+      break
+    fi
+    echo "$(date '+%Y-%m-%d %H:%M:%S %Z'): Connection lost (status ${error_code}), reconnecting..."
   done
 }
 
-for arg in "$@"; do
-  if [[ "$arg" = "-h" || "$arg" = "--help" ]]; then
-    fx-command-exec shell log_listener "$arg"
-  fi
+declare is_raw=0
+declare is_remote=0
+
+while [[ $# -ne 0 ]]; do
+  case "$1" in
+  -h|--help)
+    fx-command-help
+    echo
+    echo "*** Help for on-device log_listener:"
+    fx-command-exec shell log_listener -h
+    exit 0
+    ;;
+  --raw)
+    is_raw=1
+    ;;
+  --remote-symbols|-r)
+    is_remote=1
+    ;;
+  *)
+    break
+  esac
+  shift
 done
 
-echo "Connecting..."
-if [[ $# > 0 && "$1" = "--raw" ]]; then
-  shift
+if (( is_raw )) && (( is_remote )); then
+  fx-error "Invalid syntax: --raw and -r cannot be used together"
+  fx-command-help
+  exit 1
+fi
+
+if (( is_raw )); then
   listen "$@"
 else
-  listen "$@" | fx-symbolize
+  declare symbolizer=( "fx-command-run" "symbolize" )
+  if (( is_remote )); then
+    symbolizer+=("-r")
+  fi
+  listen "$@" | "${symbolizer[@]}"
 fi
diff --git a/tools/devshell/symbolize b/tools/devshell/symbolize
--- a/tools/devshell/symbolize
+++ b/tools/devshell/symbolize
@@ -6,16 +6,100 @@
 #### CATEGORY=Run, inspect and debug
 ### symbolize backtraces and program locations provided as input on stdin
 
-## This tool takes in log output from either zx_log or syslog and processes
-## the results to make the symbolizer markup in them human readable.
-## Anything that is not valid marked up is left alone. This is similar
+## usage: fx symbolize [-i IDS_TXT_FILE] [-r | --remote-symbols]
+##
+##    -i IDS_TXT_FILE         specify an ids.txt file to be used
+##
+##    --remote-symbols|-r     attemp to resolve symbols using predefined remote
+##                            symbol servers for symbols that cannot be resolved
+##                            locally.
+##
+## Converts sybmolizer markup found in stdin to human readable using
+## local symbols (and remote if the --remote-symbols option is used).
+## This command is usually used on log output from either zx_log or syslog.
+## Anything that is not valid symbolizer markup is left alone. This is similar
 ## to how c++filt works for demangling C++ symbols.
+##
+## By default, `fx log` and `fx klog` automatically pipe their results into
+## this command.
+##
+## Authentication:
+## If the `--remote-symbols` option is specified, `fx symbolize` will fail if the
+## current user is not authenticated with `gcloud` or if they don't have enough
+## privileges on the symbol servers. To ensure that the current user is
+## properly authenticated, run:
+##      `gcloud auth application-default login`
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
-fx-config-read
 
-if [[ $# > 1 && "$1" = "-i" ]]; then
-  fx-symbolize "$2"
-else
-  fx-symbolize
+function symbolize {
+  fx-config-read
+  local symbolize="${HOST_OUT_DIR}/symbolize"
+  if [[ ! -x "${symbolize}" ]]; then
+    fx-error "Cannot execute '${symbolize}'. Try \`fx build\` first."
+    exit 1
+  fi
+  local llvm_symbolizer="${PREBUILT_CLANG_DIR}/bin/llvm-symbolizer"
+  local toolchain_dir="${PREBUILT_CLANG_DIR}/lib/debug/.build-id"
+  local prebuilt_build_ids_dir="${FUCHSIA_BUILD_DIR}/gen/build/gn/prebuilt_build_ids"
+  local out_dir="${FUCHSIA_BUILD_DIR}/.build-id"
+  local zircon_dir="${ZIRCON_BUILDROOT}/.build-id"
+  if [[ "${is_remote}" -eq 1 ]]; then
+    trap '_code=$?; set +x; exit-with-warning ${_code}' ERR
+  fi
+  set -x
+  "$symbolize" -llvm-symbolizer "$llvm_symbolizer" \
+    -ids-rel "${extra_args[@]}" \
+    -build-id-dir "$prebuilt_build_ids_dir" -build-id-dir "$toolchain_dir" \
+    -build-id-dir "$out_dir" -build-id-dir "$zircon_dir"
+}
+
+function exit-with-warning {
+  local error_code="$1"
+  if [[ "${error_code}" -ne 0 ]]; then
+    fx-error "If you are having trouble with authentication, make sure you are" \
+             "authenticated in gcloud and you have permission to access" \
+             "the remote symbols servers.\nSee \`fx help symbolize\` for more information"
+  fi
+  exit ${error_code}
+}
+
+declare extra_args=()
+declare is_remote=0
+
+while [[ $# -ne 0 ]]; do
+  case "$1" in
+  -h|--help)
+    fx-command-help
+    exit 0
+    ;;
+  -i)
+    if [[ $# -lt 2 ]]; then
+      fx-error Invalid syntax
+      fx-command-help
+      return 1
+    fi
+    extra_args+=( "-ids" "$2")
+    shift
+    ;;
+  --remote-symbols|-r)
+    is_remote=1
+    ;;
+  *)
+    fx-error Invalid syntax
+    fx-command-help
+    exit 1
+  esac
+  shift
+done
+
+if [[ "${is_remote}" -eq 1 ]]; then
+  extra_args+=(
+    "-symbol-cache" "$HOME/.fuchsia-symbol-cache"
+    "-symbol-server" "fuchsia-debug-symbols-shortlived"
+    "-symbol-server" "fuchsia-debug-symbols-shortlived-internal"
+    "-symbol-server" "fuchsia-infra-debug-symbols"
+  )
 fi
+
+symbolize
