[fx][incr] build dependencies on core commands
If incremental is enabled, some behaviors of specific
commands have changed.

Change-Id: Ifd790ecbdc27bbcc124aa50259bc2738263e7dfc
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/450238
Commit-Queue: Renato Mangini Dias <mangini@google.com>
Fuchsia-Auto-Submit: Renato Mangini Dias <mangini@google.com>
Reviewed-by: James Tucker <raggi@google.com>

diff --git a/tools/devshell/mkzedboot b/tools/devshell/mkzedboot
--- a/tools/devshell/mkzedboot
+++ b/tools/devshell/mkzedboot
@@ -6,8 +6,14 @@
 #### CATEGORY=Software delivery
 ### make a zedboot USB key
 
-## usage: fx mkzedboot [options] <usb device>
-##  -f            force writing to a non-usb target
+## usage: fx mkzedboot [-f] [--build|--no-build] <usb device>
+##
+##   --build | --no-build     build (or not) the image required to run mkzedboot.
+##   -f                       force writing to a non-usb target.
+##
+## The default for --build is defined by the "incremental" feature:
+##    'fx --enable=incremental mkzedboot'  defaults to '--build'
+##    'fx --disable=incremental mkzedboot'  defaults to '--no-build'
 
 set -e
 
@@ -17,19 +23,49 @@ source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/fx-mk
 fx-config-read
 
 force=false
-if [[ "$1" == "-f" ]]; then
-  shift
-  force=true
+build=false
+if is_feature_enabled "incremental"; then
+  # In incremental workflows, these defaults have changed.
+  # Keep old behavior if incremental is not enabled.
+  build=true
 fi
+while (( $# )); do
+  case "$1" in
+    --help)
+      fx-command-help
+      exit 0
+      ;;
+    --no-build)
+      build=false
+      ;;
+    --build)
+      build=true
+      ;;
+    -f)
+      force=true
+      ;;
+    *)
+      break
+      ;;
+  esac
+  shift
+done
 
-USB_DEVICE="$1"
-
-if [[ -z "${USB_DEVICE}" ]]; then
-    echo >&2 "device argument required"
+if [[ $# -gt 1 ]]; then
+  fx-error "Invalid syntax"
+  fx-command-help
+  exit 1
+fi
+if [[ $# -eq 0 ]]; then
+    fx-error "Device argument required!"
+    fx-command-help
+    echo
     echo "USB disks:"
     fx-command-run list-usb-disks
     exit 1
 fi
+
+USB_DEVICE="$1"
 
 image=""
 type=""
@@ -47,8 +83,12 @@ if [[ -z "${image}" ]]; then
   exit 1
 fi
 
-if [[ ! -f "${FUCHSIA_BUILD_DIR}/${image}" ]]; then
-  fx-warn "Cannot find image to run mkzedboot: $image. Attempting to build it..."
+if ! $build && [[ ! -f "${FUCHSIA_BUILD_DIR}/${image}" ]]; then
+  fx-warn "Cannot find image to run mkzedboot: $image, will attempt to build it."
+  build=true
+fi
+
+if $build; then
   fx-command-run build "${image}"
 fi
 
diff --git a/tools/devshell/ota b/tools/devshell/ota
--- a/tools/devshell/ota
+++ b/tools/devshell/ota
@@ -6,15 +6,20 @@
 #### CATEGORY=Software delivery
 ### perform a system OTA on a connected device
 
-## usage: fx ota [-h|--help]
+## usage: fx ota [--help] [--build|--no-build]
 ##
-## Ask the target to do an OTA. The target will use any update server available
-## to it to do the update. This requires the target have a update server
-## available to it. The 'serve' fx command is typically used to make your
-## development host available to the target as an update server.
+##   --build | --no-build   Build (or not) the 'updates' target before initiating OTA.
+##   --help                 Print out this message.
 ##
-## Arguments:
-##   -h|--help    Print out this message.
+## Ask the connected Fuchsia device to do an OTA.
+## Depending on the flags, this command will attempt to build the necessary
+## dependencies ('fx build updates') before requesting the OTA.
+##
+## The default for --build is defined by the "incremental" feature:
+##    'fx --enable=incremental ota'  defaults to '--build'
+##    'fx --disable=incremental ota'  defaults to '--no-build'
+##
+## A package server needs to be running and this command will fail if it is not.
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/updates.sh || exit $?
@@ -26,10 +31,38 @@ function needs-update {
 }
 
 function main {
-  fx-standard-switches "$@"
-  set -- "${FX_ARGV[@]}"
+  local build=false
+  if is_feature_enabled "incremental"; then
+    # In incremental workflows, these defaults have changed.
+    # Keep old behavior if incremental is not enabled.
+    build=true
+  fi
+  while (( $# )); do
+    case "$1" in
+      --help)
+        fx-command-help
+        exit 0
+        ;;
+      --no-build)
+        build=false
+        ;;
+      --build)
+        build=true
+        ;;
+      *)
+       fx-error 'Invalid syntax'
+       fx-command-help
+       exit 1
+    esac
+    shift
+  done
 
   check-for-amber-server || return 1
+
+  if $build; then
+    fx-info "Building/refreshing target 'updates'"
+    fx-command-run build updates
+  fi
 
   # Note: the following command continues to run as the system goes into
   # reboot, so we lose SSH connection before it "completes". As such the
diff --git a/tools/devshell/pave b/tools/devshell/pave
--- a/tools/devshell/pave
+++ b/tools/devshell/pave
@@ -6,27 +6,103 @@
 #### CATEGORY=Software delivery
 ### run bootserver for paving
 
-## usage: fx pave [extra bootserver arguments]
+## usage: fx pave [--build|--no-build] [-1|--keep-running] [extra bootserver arguments]
+##
+##   --build | --no-build     build (or not) the images required to pave.
+##   -1 | --keep-running      perform a single pave and exit or keep the bootserver
+##                            running after the first paving
+##   extra bootserver args    arguments passed directly to bootserver
+##
+## Start a bootserver for paving a device, optionally performing a build of the
+## system images before.
+##
+## Defaults are defined by the "incremental" feature:
+##    'fx --enable=incremental pave'  defaults to "--build" and "-1"
+##    'fx --disable=incremental pave'  defaults to "--no-build" and "--keep-running"
+##
+## For bootserver specific arguments, use 'fx pave --help'
 
 set -e
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
 fx-config-read
 
-name_args=()
-name="$(get-device-name)" || exit $?
-if [[ -n "$name" ]]; then
-  name_args+=("-n" "${name}")
-fi
+function main {
+  local single_run=false
+  local build=false
+  if is_feature_enabled "incremental"; then
+    # In incremental workflows, these defaults have changed.
+    # Keep old behavior if incremental is not enabled.
+    single_run=true
+    build=true
+  fi
+  local pave_args=()
+  local help=false
+  while (( $# )); do
+    case "$1" in
+      --help)
+        help=true
+        ;;
+      --no-build)
+        build=false
+        ;;
+      --build)
+        build=true
+        ;;
+      --keep-running)
+        single_run=false
+        ;;
+      -1)
+        single_run=true
+        ;;
+      *)
+        pave_args+=("$1")
+        ;;
+    esac
+    shift
+  done
 
-authkeys_path="$(get-ssh-authkeys)" || {
-  fx-error "Cannot continue without a valid authorized keys file."
-  exit 1
+  if $help; then
+    if ! $build; then
+      # bootserver options cannot be shown if depedencies cannot be built, so
+      # if --no-build flag is used, just show the simple help.
+      fx-command-help
+      exit 0
+    fi
+    fx-command-help 2>&1 | grep -v "fx pave --help" >&2
+    fx-info
+    fx-info "Building and executing 'pave.sh --help' to show bootserver specific options."
+    fx-info "Press Ctrl+C to interrupt."
+    fx-info
+    pave_args=(--help)
+
+  else
+    if $single_run; then
+      pave_args+=( "-1" )
+    fi
+
+    name="$(get-device-name)" || exit $?
+    if [[ -n "$name" ]]; then
+      pave_args+=("-n" "${name}")
+    fi
+
+    if ! fx-is-bringup; then
+      authkeys_path="$(get-ssh-authkeys)" || {
+        fx-error "Cannot continue without a valid authorized keys file."
+        exit 1
+      }
+      pave_args+=(--authorized-keys "${authkeys_path}")
+    fi
+  fi
+
+  if $build; then
+    local artifacts=($(fx-command-run list-build-artifacts pave)) || exit $?
+    fx-info "Building/refreshing targets ${artifacts[@]}"
+    fx-command-run build "${artifacts[@]}"
+  fi
+
+  exec "${FUCHSIA_BUILD_DIR}/pave.sh" "${pave_args[@]}"
 }
 
-auth_keys_args=(--authorized-keys "${authkeys_path}" "$@")
-if fx-is-bringup; then
-  auth_keys_args=()
-fi
+main "$@"
 
-exec "${FUCHSIA_BUILD_DIR}/pave.sh" "${name_args[@]}" "${auth_keys_args[@]}" "$@"
