[ninjatrace2json] Add rpl interleaving support
Fixed: 85536

Change-Id: Idabe1d8f97d3445c4949db04ff255c9d6fd1e147
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/595581
Commit-Queue: Jay Zhuang <jayzhuang@google.com>
Fuchsia-Auto-Submit: Jay Zhuang <jayzhuang@google.com>
Reviewed-by: David Fang <fangism@google.com>
Reviewed-by: David Turner <digit@google.com>

diff --git a/tools/devshell/ninjatrace2json b/tools/devshell/ninjatrace2json
--- a/tools/devshell/ninjatrace2json
+++ b/tools/devshell/ninjatrace2json
@@ -8,15 +8,62 @@
 
 ## Usage: fx ninjatrace2json
 ##
-## Use this after a build to write "ninjatrace.json" and
-## "ninjatrace_critical_path.json" files in the build directories (separately
-## for Zircon and Fuchsia build directories). Then use the chrome://tracing view
-## to load that file into your browser.
+## Use this after a build to write "ninjatrace.json" in the build directory.
 
 set -e
 
-source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
+source "$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
 fx-config-read
+
+function usage() {
+  cat << EOF
+Use this after a build to write "ninjatrace.json" in the build directory.
+See https://fuchsia.dev/internal/intree/concepts/build-performance?hl=en#build-performance-analysis-as-a-trace.
+
+fx ninjatrace2json [options]
+
+Options:
+  --help|-h: print this help and exit
+  --rbe-rpl-path: when provided, interleave remote execution stats from RBE into
+      the main trace
+EOF
+}
+
+rbe_rpl_path=''
+# Extract script options before --
+for opt; do
+  # handle --option arg
+  if test -n "$prev_opt"; then
+    eval "$prev_opt"=\$opt
+    prev_opt=
+    shift
+    continue
+  fi
+  # Extract optarg from --opt=optarg
+  case "$opt" in
+    *=?*) optarg=$(expr "X$opt" : '[^=]*=\(.*\)') ;;
+    *=) optarg= ;;
+  esac
+  case "$opt" in
+    --help | -h)
+      usage
+      exit
+      ;;
+    --rbe-rpl-path=*) rbe_rpl_path="$optarg" ;;
+    --rbe-rpl-path) prev_opt='rbe_rpl_path' ;;
+    *)
+      echo "Unknown option ${opt}"
+      usage
+      exit 1
+      ;;
+  esac
+  shift
+done
+
+test -z "$prev_opt" || {
+  echo "Option is missing argument to set $prev_opt."
+  exit 1
+}
 
 TMP_DIR="$(mktemp -d)"
 readonly TMP_DIR
@@ -25,10 +72,21 @@ trap 'rm -rf "${TMP_DIR}"' EXIT
 "${PREBUILT_NINJA}" -C "${FUCHSIA_BUILD_DIR}" -t compdb > "${TMP_DIR}/compdb.json"
 "${PREBUILT_NINJA}" -C "${FUCHSIA_BUILD_DIR}" -t graph > "${TMP_DIR}/graph.dot"
 
-"${HOST_OUT_DIR}/ninjatrace" \
-  -ninjalog "${FUCHSIA_BUILD_DIR}/.ninja_log" \
-  -compdb "${TMP_DIR}/compdb.json" \
-  -graph "${TMP_DIR}/graph.dot" \
-  -trace-json "${FUCHSIA_BUILD_DIR}/ninjatrace.json" \
+ninjatrace_args=(
+  -ninjalog "${FUCHSIA_BUILD_DIR}/.ninja_log"
+  -compdb "${TMP_DIR}/compdb.json"
+  -graph "${TMP_DIR}/graph.dot"
+  -trace-json "${FUCHSIA_BUILD_DIR}/ninjatrace.json"
   -critical-path
+)
+
+test -z "${rbe_rpl_path}" || {
+  ninjatrace_args+=(
+    -rbe-rpl-path "${rbe_rpl_path}"
+    '-rpl2trace-path' "${PREBUILT_RECLIENT_DIR}/rpl2trace"
+  )
+}
+
+"${HOST_OUT_DIR}/ninjatrace" "${ninjatrace_args[@]}"
+
 echo "Now visit chrome://tracing and load ${FUCHSIA_BUILD_DIR}/ninjatrace.json"
