[fx][pave] Emit better error if pave.sh does not exist
Previously, `fx pave` would emit an unhelpful error message if the
`pave.sh` script doesn't exist. This CL updates `fx pave` to instruct
the user how to produce the script for future executions.

Fixed: 75098
Change-Id: I613ef28fe33a270c763b581e6fd0b9564bdeafae
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/580860
Reviewed-by: James Tucker <raggi@google.com>
Commit-Queue: Erick Tryzelaar <etryzelaar@google.com>

diff --git a/tools/devshell/pave b/tools/devshell/pave
--- a/tools/devshell/pave
+++ b/tools/devshell/pave
@@ -101,6 +101,13 @@ function main {
     fx-command-run build "${artifacts[@]}"
   fi
 
+  if [[ ! -f "${FUCHSIA_BUILD_DIR}/pave.sh" ]]; then
+    fx-error "'pave.sh' script does not exist."
+    fx-error "Run 'fx pave --build' or 'fx build' to build it and"
+    fx-error "all the required artifacts to pave a device."
+    exit 1
+  fi
+
   exec "${FUCHSIA_BUILD_DIR}/pave.sh" "${pave_args[@]}"
 }
 
