[fx] change 'fx emu' and 'qemu' to build images
- change emu and qemu to build the source fvm (eg fvm.blk) unless '--no-build'
is used
- change qemu to build image dependencies (zircon-a and kernel) unless
'--no-build' is used
- remove emu and qemu dependency on image_paths.sh, using images.json
instead
- change fvm.sh fx-fvm-find-raw-source to return relative path

Change-Id: I3d242c5a6822b812631e0cd4fe8c7e00b7b39192
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/469596
Commit-Queue: Renato Mangini Dias <mangini@google.com>
Reviewed-by: Joshua Seaton <joshuaseaton@google.com>
Reviewed-by: James Tucker <raggi@google.com>

diff --git a/tools/devshell/qemu b/tools/devshell/qemu
--- a/tools/devshell/qemu
+++ b/tools/devshell/qemu
@@ -7,23 +7,33 @@
 ### start fuchsia in qemu with a FVM disk
 ## start fuchsia in qemu with a FVM disk
 ##
-## This command delegates to //zircon/scripts/run-zircon. Flags are documented
-## in that script, and can be discovered by passing -h or --help.
+## usage: fx qemu [--no-build] [-z <zbi_image>] [RUN_ZIRCON_FLAGS]
+##
+##      -z <zbi_image>   use <zbi_image> instead of the default.
+##      --no-build       do not attempt to build the fvm and the default zbi images.
+##                       A custom zbi image passed by a '-z' flag is never built.
+##
+## This command delegates to //zircon/scripts/run-zircon. Other flags are
+## documented in that script, and can be discovered by passing -h or --help.
 ##
 
 set -e
 
-source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/image_build_vars.sh || exit $?
+source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
+fx-config-read
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/fvm.sh || exit $?
 
-ZBI_IMAGE="${FUCHSIA_BUILD_DIR}/${IMAGE_ZIRCONA_ZBI}"
-
-while [[ $# -gt 1 ]]; do
+build_flag=true
+ZBI_IMAGE=
+while [[ $# -gt 0 ]]; do
   case "$1" in
     -h|--help)
       fx-command-help
       "${FUCHSIA_DIR}/zircon/scripts/run-zircon" -h
       exit 1
+      ;;
+    --no-build)
+      build_flag=false
       ;;
     -z)
       shift
@@ -42,11 +52,31 @@ authkeys_path="$(get-ssh-authkeys)" || {
 
 qemu_dir="${PREBUILT_QEMU_DIR}/bin"
 
+build_targets=()
+
+KERNEL_IMAGE="$(fx-command-run list-build-artifacts --type kernel --name qemu-kernel images)"
+build_targets+=( "${KERNEL_IMAGE}" )
+if [[ -z "${ZBI_IMAGE}" ]]; then
+  ZBI_IMAGE="$(fx-command-run list-build-artifacts --type zbi --name zircon-a images)"
+  build_targets+=( "${ZBI_IMAGE}" )
+  ZBI_IMAGE="${FUCHSIA_BUILD_DIR}/${ZBI_IMAGE}"
+fi
+
+# Not all builds use an FVM so failing to find a source FVM is OK.
+fvm_source="$(fx-fvm-find-raw-source)"
+[[ -n "${fvm_source}" ]] && build_targets+=( "${fvm_source}" )
+
 args=(
   -a "${FUCHSIA_ARCH}"
   -q "${qemu_dir}"
-  -t "${FUCHSIA_BUILD_DIR}/${IMAGE_QEMU_KERNEL_RAW}"
+  -t "${FUCHSIA_BUILD_DIR}/${KERNEL_IMAGE}"
 )
+
+if $build_flag; then
+  _targets="$(printf ", %s" "${build_targets[@]}")"
+  echo >&2 "Building ${_targets:2}"
+  fx-command-run build "${build_targets[@]}"
+fi
 
 # Construction of a qcow image prevents qemu from writing back to the
 # build-produced image file, which could cause timestamp issues with that file.
@@ -63,12 +93,10 @@ kernelzbi="${imgdir}/fuchsia-ssh.zbi"
 args+=(-z "${kernelzbi}")
 fx-zbi -o "${kernelzbi}" "${ZBI_IMAGE}" --entry "data/ssh/authorized_keys=${authkeys_path}"
 
-# Not all builds use an FVM so failing to find a source FVM is OK.
-fvm_source=$(fx-fvm-find-raw-source)
 if [[ -n "${fvm_source}" ]]; then
-  fvm_tool="${FUCHSIA_BUILD_DIR}/$(fx-command-run list-build-artifacts --name fvm --expect-one tools)"
+  fvm_tool="$(fx-command-run host-tool --print fvm)"
   fvm_raw="${imgdir}/fvm_raw.blk"
-  fx-fvm-extend-image "${fvm_tool}" "${fvm_source}" "${fvm_raw}" "${IMAGE_SIZE}"
+  fx-fvm-extend-image "${fvm_tool}" "${FUCHSIA_BUILD_DIR}/${fvm_source}" "${fvm_raw}" "${IMAGE_SIZE}"
   args+=(-d -D "${fvm_raw}" --diskfmt=raw)
 fi
 
