[build][images] Make bringup product put everything in BOOTFS
The new `bootfs_only` build argument says to put the system image
package into /boot instead of /system and does not create a storage
image at all.  There can still be packages in the "universe" list,
but there is no preinstalled pkgfs in the system at all.  The
bringup product now sets this flag.

Bug: BLD-446 #comment Make bringup product put everything in BOOTFS
Test: /boot/test/sys/running_on_bootfs_test
Change-Id: If07f3d5dd530a007961518b15ab621133850dc4f

diff --git a/tools/devshell/run b/tools/devshell/run
--- a/tools/devshell/run
+++ b/tools/devshell/run
@@ -25,6 +25,13 @@ done
 
 qemu_dir="${BUILDTOOLS_QEMU_DIR}/bin"
 
+args=(
+  -a "${FUCHSIA_ARCH}"
+  -q "${qemu_dir}"
+  -G 3
+  -t "${FUCHSIA_BUILD_DIR}/${IMAGE_QEMU_KERNEL_RAW}"
+)
+
 # Construction of a qcow image prevents qemu from writing back to the
 # build-produced image file, which could cause timestamp issues with that file.
 # Construction of the new ZBI adds //.ssh/authorized_keys for SSH access.
@@ -33,39 +40,33 @@ if [[ ! -d "${imgdir}" ]]; then
   echo >&2 "Failed to create temporary directory"
   exit 1
 fi
-fvmimg="${imgdir}/fvm.blk"
+trap 'rm -rf "$imgdir"' EXIT
+
 kernelzbi="${imgdir}/fuchsia-ssh.zbi"
-trap 'rm "${fvmimg}" "${kernelzbi}" && rmdir "${imgdir}"' EXIT
-
-stat_flags=()
-if [[ $(uname) == "Darwin" ]]; then
-  stat_flags+=("-x")
-fi
-stat_output=$(stat "${stat_flags[@]}" "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_RAW}")
-if [[ "$stat_output" =~ Size:\ ([0-9]+) ]]; then
-  size="${BASH_REMATCH[1]}"
-  newsize=$(($size * 2))
-  # We must take a copy of the build artifact, rather than re-use it, as we
-  # need to modify it in order to extend it.
-  echo -n "Creating disk image..."
-  cp "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_RAW}" "${fvmimg}"
-  "${ZIRCON_TOOLS_DIR}/fvm" "${fvmimg}" extend --length "${newsize}"
-  echo "done"
-else
-  fx-error "could not extend fvm, unable to stat fvm image"
-fi
-
+args+=(-z "${kernelzbi}")
 "${ZIRCON_TOOLS_DIR}/zbi" -o "${kernelzbi}" "${FUCHSIA_BUILD_DIR}/${IMAGE_ZIRCONA_ZBI}" \
   --entry "data/ssh/authorized_keys=${FUCHSIA_DIR}/.ssh/authorized_keys"
 
-"${FUCHSIA_DIR}/zircon/scripts/run-zircon" \
-  -a "${FUCHSIA_ARCH}" \
-  -q "${qemu_dir}" \
-  -G 3 \
-  -t "${FUCHSIA_BUILD_DIR}/${IMAGE_QEMU_KERNEL_RAW}" \
-  -z "${kernelzbi}" \
-  -d \
-  -D "${fvmimg}" \
-  --diskfmt="raw" \
-  "$@"
+if [ -n "$IMAGE_FVM_RAW" ]; then
+  fvmimg="${imgdir}/fvm.blk"
+  args+=(-d -D "${fvmimg}" --diskfmt=raw)
+  stat_flags=()
+  if [[ $(uname) == "Darwin" ]]; then
+    stat_flags+=("-x")
+  fi
+  stat_output=$(stat "${stat_flags[@]}" "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_RAW}")
+  if [[ "$stat_output" =~ Size:\ ([0-9]+) ]]; then
+    size="${BASH_REMATCH[1]}"
+    newsize=$(($size * 2))
+    # We must take a copy of the build artifact, rather than re-use it, as we
+    # need to modify it in order to extend it.
+    echo -n "Creating disk image..."
+    cp "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_RAW}" "${fvmimg}"
+    "${ZIRCON_TOOLS_DIR}/fvm" "${fvmimg}" extend --length "${newsize}"
+    echo "done"
+  else
+    fx-error "could not extend fvm, unable to stat fvm image"
+  fi
+fi
 
+exec "${FUCHSIA_DIR}/zircon/scripts/run-zircon" "${args[@]}" "$@"
