[vdl] Configure "fx vdl" to land in shell terminal.
In this change, we provide help messages to users who wants to map
emulator device to fx tools. We also changed the "fx vdl" behavior to
land in femu's shell terminal. This is the same user experience as "fx
emu"

Test: fx test host_x64/obj/tools/devshell/fx_script_tests.sh

Change-Id: I0a8c1d961b0805b55b5e406efcf873582b2e6cce
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/443795
Testability-Review: Renato Mangini Dias <mangini@google.com>
Commit-Queue: Yuan Zhi <yuanzhi@google.com>
Reviewed-by: Renato Mangini Dias <mangini@google.com>

diff --git a/tools/devshell/vdl b/tools/devshell/vdl
--- a/tools/devshell/vdl
+++ b/tools/devshell/vdl
@@ -21,16 +21,6 @@ set -e
 DEVSHELL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 source "${DEVSHELL_DIR}"/lib/image_build_vars.sh || exit $?
 
-# Scans ports from and return the first identified unused port.
-function find_unused_tcp_port {
-  local server_port="${1}"
-  local max_port=59759
-  while ss -latn | grep -q :${server_port} && server_port < ${max_port}; do
-    server_port=$((${server_port} + 1))
-  done
-  echo "${server_port}"
-}
-
 # Defaults
 ACTION="start"
 EXTR_KERNEL_FLAGS=""
@@ -97,7 +87,18 @@ done
 # Stores VDL outputs such as pid for package server, and created tmp files.
 VDL_PROTO="/tmp/vdl_proto"
 
-if [[ "${ACTION}" == "kill" ]]; then
+# Scans ports from and return the first identified unused port.
+function find_unused_tcp_port {
+  local server_port="${1}"
+  local max_port=59759
+  while ss -latn | grep -q :${server_port} && server_port < ${max_port}; do
+    server_port=$((${server_port} + 1))
+  done
+  echo "${server_port}"
+}
+
+# Cleanup all artifacts created by VDL.
+function kill_vdl {
   "${VDL}" --action=kill \
     --launched_virtual_device_proto="${VDL_PROTO}" \
     --ga=true
@@ -107,6 +108,10 @@ if [[ "${ACTION}" == "kill" ]]; then
     rm "${VDL_PROTO}"
   fi
   exit ${exit_code}
+}
+
+if [[ "${ACTION}" == "kill" ]]; then
+  kill_vdl
 fi
 
 if [[ -f "${VDL_PROTO}" ]]; then
@@ -127,7 +132,6 @@ if [[ ! -d "${img_dir}" ]]; then
   exit 1
 fi
 echo "Created tmp dir ${img_dir}"
-trap 'rm -Rf "${img_dir}"' EXIT
 
 # System images
 # Currently VDL makes some files naming pattern assumptions
@@ -196,26 +200,33 @@ SSH_PORT=$(find_unused_tcp_port 32761)
 readonly PORT_MAP="hostfwd=tcp::${SSH_PORT}-:22"
 
 # Start FEMU using VDL
-set -x
-if [[ "${ACTION}" == "start" ]]; then
-  "${VDL}" --action=start \
-      --emulator_binary_path="${AEMU}" \
-      --pm_tool="${PM}" \
-      --far_tool="${FAR}" \
-      --fvm_tool="${FVM}" \
-      --resize_fvm="${IMAGE_SIZE}" \
-      --gpu="${GPU}" \
-      --headless_mode="${HEADLESS}" \
-      --tuntap="${TUNTAP}" \
-      --upscript="${UPSCRIPT}" \
-      --enable_grpc_server=false \
-      --enable_grpc_tls=false \
-      --system_images="${SYSTEM_FILES}" \
-      --proto_file_path="${DEVICE_PROTO}" \
-      --host_port_map="${PORT_MAP}" \
-      --output_launched_device_proto="${VDL_PROTO}" \
-      --ga=true \
-      --emu_log="/tmp/emulator_log.log" \
-      --audio=true
-fi
+"${VDL}" --action=start \
+    --emulator_binary_path="${AEMU}" \
+    --pm_tool="${PM}" \
+    --far_tool="${FAR}" \
+    --fvm_tool="${FVM}" \
+    --resize_fvm="${IMAGE_SIZE}" \
+    --gpu="${GPU}" \
+    --headless_mode="${HEADLESS}" \
+    --tuntap="${TUNTAP}" \
+    --upscript="${UPSCRIPT}" \
+    --enable_grpc_server=false \
+    --enable_grpc_tls=false \
+    --system_images="${SYSTEM_FILES}" \
+    --proto_file_path="${DEVICE_PROTO}" \
+    --host_port_map="${PORT_MAP}" \
+    --output_launched_device_proto="${VDL_PROTO}" \
+    --ga=true \
+    --emu_log="/tmp/emulator_log.log" \
+    --audio=true
 
+trap 'rm -Rf "${img_dir}" && kill_vdl' EXIT
+
+if [[ "${TUNTAP}" == true ]]; then
+  fx-info "To support fx tools on emulator, please run \"fx set-device step-atom-yard-juicy\""
+  deviceaddr="$(fx-device-finder resolve -ipv4=false step-atom-yard-juicy)"
+  fx-command-run ssh "${deviceaddr}"
+else
+  fx-info "To support fx tools on emulator, please run \"fx set-device 127.0.0.1:${SSH_PORT}\""
+  fx-command-run ssh fuchsia@localhost -p "${SSH_PORT}"
+fi
