[fx] Fix "fx vendor" handling of metadata
Tests: added tests for behavior changes in fx vendor and updated
existing tests.
  $ fx self-test subcommands/fx_vendor_test
  Running test script subcommands/fx_vendor_test
  [1] TEST_fxvendor_exec()  [PASSED]
  [2] TEST_fxvendor_metadata()  [PASSED]
  [3] TEST_fxvendor_nonvendorcmd()  [PASSED]
  All 3 tests passed.

  $ fx self-test --all
  ...
  (all tests pass)

Fixed: 51757
Change-Id: Iea71e2595a3771245f1405913b241601a7064b5b
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/388117
Testability-Review: Renato Mangini Dias <mangini@google.com>
Reviewed-by: Anthony Fandrianto <atyfto@google.com>
Commit-Queue: Renato Mangini Dias <mangini@google.com>

diff --git a/tools/devshell/vendor b/tools/devshell/vendor
--- a/tools/devshell/vendor
+++ b/tools/devshell/vendor
@@ -9,6 +9,7 @@
 ## usage: fx vendor <vendor-dir> [command]
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
+source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/fx-cmd-locator.sh || exit $?
 
 function main {
   if [[ $# -lt 2 ]]; then
@@ -16,27 +17,32 @@ function main {
 
     echo >&2 "commands: "
     for d in "${FUCHSIA_DIR}"/vendor/*; do
-      for f in "$d"/scripts/devshell/*; do
-        if [[ -x "$f" ]]; then
-          echo >&2 "  $(basename $d)" "$(basename $f)"
-        fi
-      done
+      # list all subcommands with summaries, grouped by categories
+      commands vendor "$(basename "$d")" | xargs awk \
+        -v hide_contrib=${hide_contrib} \
+        -v show_deprecated=${show_deprecated} \
+        -f "${FUCHSIA_DIR}/scripts/fx-help.awk"
     done
 
     return 1
   fi
 
-  vendor_cmd_path="${FUCHSIA_DIR}/vendor/$1/scripts/devshell/$2"
+  vendor_name="$1"
+  command_name="$2"
+  command_path="$(commands vendor "${vendor_name}" "${command_name}")"
 
-  if [[ ! -x "${vendor_cmd_path}" ]]; then
-    echo >&2 "command $1 $2 not found!"
+  # expand metadata if it's a "*.fx" file
+  command_path="$(find_exec_from_path "${command_path}")"
+
+  if [[ ! -x "${command_path}" ]]; then
+    echo >&2 "command ${command_name} not found on vendor ${vendor_name}!"
     return 1
   fi
 
   shift
   shift
 
-  exec "${vendor_cmd_path}" "$@"
+  exec "${command_path}" "$@"
 }
 
 main "$@"
