[bugreport] switch to streaming an archive instead of a JSON
* the target program `bugreport` now sends a ZIP archive containing all
  the data to the host
* `fx bugreport` now directly writes to file that ZIP archive
* `fx bugreport` does not use the `bugreport` host tool anymore
* `fx bugreport --serial` is no longer supported until we have a way to
  safely send the archive over serial
* we modify the host tool to just dump the input into an output file so
  that out-of-tree clients still work while we migrate them off the host
  tool

Bug: 6606

TESTED=`fx run-test bugreport_tests`
TESTED=`fx bugreport`

Change-Id: I17172b54b00a85c0231cc10c19f614cb38f01fe1

diff --git a/tools/devshell/contrib/bugreport b/tools/devshell/contrib/bugreport
--- a/tools/devshell/contrib/bugreport
+++ b/tools/devshell/contrib/bugreport
@@ -13,32 +13,23 @@
 ## - Kernel and System logs.
 ## - Inspect Data.
 ##
-## Each element will be separated in its own report file within a supplied
-## directory. If no directory is supplied, a unique one will be generated.
+## If no directory is supplied, a unique one will be generated.
 ##
 ## Usage: fx bugreport [(--output-directory|-o)] <DIRECTORY>] -- <TARGET ARGS>
 ##
 ##    --output-directory    (Optional) Directory where the files will be stored.
 ##                          Must be an existing directory.
-##    --serial              (Optional) Use serial channel instead of ssh.
 ##
 ##    <TARGET ARGS>         Arguments to be passed to the bugreport client within
 ##                          the target.
-##
-## NOTE: For the serial report to work correctly, it requires a clean channel
-##       (no other output). While this is often true, it is not assured. This
-##       means that the serial report is best effort only. If it fails, try
-##       running it again or use minimal.
 
 # Load environment helpers.
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
-source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../contrib/lib/serial.sh || exit $?
 fx-config-read
 
 # Flag Parsing.
 output_dir=
 is_output_dir_provided=false
-use_serial=
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
@@ -50,9 +41,6 @@ while [[ $# -gt 0 ]]; do
       shift
       output_dir="$1"
       is_output_dir_provided=true
-      ;;
-    --serial)
-      use_serial=true
       ;;
     --)
       shift
@@ -79,12 +67,10 @@ if [[ "${is_output_dir_provided}" == "true" ]]; then
 fi
 
 # Verify that we can obtain the target (ssh only).
-if [[ -z "${use_serial}" ]]; then
-  target=$(get-fuchsia-device-addr)
-  if [[ -z "${target}" ]]; then
-    fx-error "Could not obtain target name."
-    exit 1
-  fi
+target=$(get-fuchsia-device-addr)
+if [[ -z "${target}" ]]; then
+  fx-error "Could not obtain target name."
+  exit 1
 fi
 
 # If no output directory is supplied, generate a unique one according to time.
@@ -106,62 +92,21 @@ fi
 
 error_bringing_report=
 tempfile="/tmp/__bugreport_temp"
-if [[ -z "${use_serial}" ]]; then
-  # USING SSH.
-  # Obtain the bug report and store it in a temporary location.
-  fx-command-run "ssh" "${target}" "bugreport ${@}" > "${tempfile}"
-  if [ "$?" -ne 0 ]; then
-    fx-error "Could not obtain bugreport from target."
-    error_bringing_report=true
-  fi
+output_file="${output_dir}/bugreport.zip"
+# Obtain the bug report and store it in a temporary location.
+fx-command-run "ssh" "${target}" "bugreport ${@}" > "${output_file}"
+if [ "$?" -ne 0 ]; then
+  fx-error "Could not obtain bugreport from target."
+  error_bringing_report=true
 else
-  # USING SERIAL.
-  get_serial_device
-  if [[ -z "${DEVICE}" ]]; then
-    fx-error "Could not obtain a serial device."
-    error_bringing_report=true
-  elif serial_port_unavailable "${DEVICE}"; then
-    fx-error "${DEVICE} is unavailable."
-    error_bringing_report=true
-  else
-    echo "Transfering data to host..."
-    send_serial_command "${DEVICE}" "${tempfile}" "run bugreport.cmx ${@}"
-
-    if [[ "$?" -ne 0 ]]; then
-      fx-error "Could not obtain bugreport from target."
-      error_bringing_report=true
-    else
-      # Do the adhoc serial cleanup.
-      # This is needed because the report file will have all the serial output,
-      # including the prompt and the actual "run bugreport.cmx" command.
-      # In order to have our process tool work, we need to clear it to be just the
-      # json content.
-      sed -e "1,2d" -e "$ s/.*/}/" -i "${tempfile}"
-    fi
-  fi
+  echo "Exported ${output_file}"
 fi
 
 if [[ ! -z "${error_bringing_report}" ]]; then
   # Do error cleanup.
-  rm -f "${tempfile}"
+  rm -f "${output_file}"
   if [[ "${is_output_dir_provided}" == "false" ]]; then
     rm -rf "${output_dir}"
   fi
   exit 1
-fi
-
-# Process the bugreport.
-"${FUCHSIA_BUILD_DIR}/tools/bugreport" "${output_dir}" < "${tempfile}"
-if [ "$?" -ne 0 ]; then
-  fx-error "Error processing bugreport."
-  fx-error "Downloaded unprocessed report is in ${tempfile}."
-
-  # Clean up temp directory.
-  if [[ "${is_output_dir_provided}" == "false" ]]; then
-    rm -rf "${output_dir}"
-  fi
-  exit 1
-else
-  # Clean up.
-  rm -f "${tempfile}"
 fi
