[debugger] Add options to fx debug for opening core files
Change-Id: I751476b9ca085086da731ce073309cb66fef7317

diff --git a/tools/devshell/contrib/debug b/tools/devshell/contrib/debug
--- a/tools/devshell/contrib/debug
+++ b/tools/devshell/contrib/debug
@@ -32,7 +32,8 @@ fx-config-read
 source "${FUCHSIA_DIR}/buildtools/vars.sh"
 
 # Defaults.
-port=2345
+port=
+core=
 agent_out="/dev/null"
 
 # Flag parsing.
@@ -49,6 +50,15 @@ while [[ "$1" =~ ^- ]]; do
     --verbose-agent|-va)
       agent_out="/dev/stdout"
       ;;
+    --core|-c)
+      arg=$1
+      shift
+      core="$1"
+      if [[ -z "${core}" ]]; then
+        echo "${arg} takes an argument"
+        exit 1
+      fi
+      ;;
     --)
       shift
       break # Remaining flags are passed to zxdb
@@ -60,6 +70,20 @@ while [[ "$1" =~ ^- ]]; do
   shift
 done
 
+if [[ -n "${port}" && -n "${core}" ]]; then
+  echo "Specifying both a port and a core doesn't make sense"
+  exit 1
+fi
+
+if [[ -n "${core}" && ! -f "${core}" ]]; then
+  echo "Cannot find file ${core}"
+  exit 1
+fi
+
+if [[ -z "${port}" ]]; then
+  port=2345
+fi
+
 # Get the defaulted device address.
 target=$(get-fuchsia-device-addr)
 if [[ -z "${target}" ]]; then
@@ -67,45 +91,53 @@ if [[ -z "${target}" ]]; then
   exit 1
 fi
 
-debug_agent_pkg="fuchsia-pkg://fuchsia.com/debug_agent#meta/debug_agent.cmx"
+connect_ops=
 
-fx_ssh_pid=""
-trap 'kill ${fx_ssh_pid}' EXIT
+if [[ -z "${core}" ]]; then
+  debug_agent_pkg="fuchsia-pkg://fuchsia.com/debug_agent#meta/debug_agent.cmx"
+
+  fx_ssh_pid=""
+  trap 'kill ${fx_ssh_pid}' EXIT
 
 # Leave the SSH connection open. Will be closed on script end.
 # We branch out on whether the user used the verbose-agent flag. If so, we
 # redirect the debug agent output to /dev/null.
-echo -e "Attempting to start the Debug Agent."
-fx-command-run "ssh" "${target}" "run ${debug_agent_pkg} --port=${port}" > "${agent_out}" 2>&1 &
-fx_ssh_pid="$!"
+  echo -e "Attempting to start the Debug Agent."
+  fx-command-run "ssh" "${target}" "run ${debug_agent_pkg} --port=${port}" > "${agent_out}" 2>&1 &
+  fx_ssh_pid="$!"
 
 # We wait until the debug agent is listening on the given port. We use NC to
 # attemp a tcp connection. This will actually go all the way with the handshake,
 # so the debug agent will think initially that NC is a client. But then it will
 # close the connection and receive the actual client's connection and work fine.
-try_count=0
-max_tries=10
-echo "Waiting for the Debug Agent to start."
-while true; do
-  # Use NC to test if the port is open and the debug agent is listening.
-  if nc -w5 -6 -z "${target}" "${port}"; then
-    break
-  fi
+  try_count=0
+  max_tries=10
+  echo "Waiting for the Debug Agent to start."
+  while true; do
+    # Use NC to test if the port is open and the debug agent is listening.
+    if nc -w5 -6 -z "${target}" "${port}"; then
+      break
+    fi
 
-  # Otherwise, we count and check if we need to exit.
-  try_count=$(expr "${try_count}" + 1)
-  if [[ "${try_count}" -gt "${max_tries}" ]]; then
-    fx-error "Timed out trying to find the Debug Agent. Exiting."
-    exit 1
-  fi
-  sleep 1
-done
+    # Otherwise, we count and check if we need to exit.
+    try_count=$(expr "${try_count}" + 1)
+    if [[ "${try_count}" -gt "${max_tries}" ]]; then
+      fx-error "Timed out trying to find the Debug Agent. Exiting."
+      exit 1
+    fi
+    sleep 1
+  done
+
+  connect_ops="--connect [${target}]:${port}"
+else
+  connect_ops="--core ${core}"
+fi
 
 # We start the client with the flag that tells it to quit the agent when zxdb quits.
 "${FUCHSIA_BUILD_DIR}/host_x64/zxdb" \
-  "--connect" "[${target}]:${port}" \
+  ${connect_ops} \
   "--quit-agent-on-exit" \
   "-s" "${FUCHSIA_BUILD_DIR}" \
   "-s" "${ZIRCON_BUILDROOT}" \
   "-s" "${BUILDTOOLS_CLANG_DIR}/lib/debug" \
-  "$@"
+  $@
