[debugger/fidlcat] Use symbol-index in fx commands
Migrate to use "symbol-index" file for symbol lookup. `fx debug` and
`fx fidlcat` will now check for the registration in symbol-index before
running the commands. Hard-coded symbol paths are dropped.

Bug: 57458
Change-Id: I75c26fb9403b9da243bcc590044e0361fa667ea8
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/414515
Reviewed-by: James Tucker <raggi@google.com>
Reviewed-by: Renato Mangini Dias <mangini@google.com>
Testability-Review: James Tucker <raggi@google.com>
Commit-Queue: Dangyi Liu <dangyi@google.com>

diff --git a/tools/devshell/contrib/debug b/tools/devshell/contrib/debug
--- a/tools/devshell/contrib/debug
+++ b/tools/devshell/contrib/debug
@@ -37,7 +37,8 @@
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
 fx-config-read
-source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../contrib/lib/debug-agent.sh || exit $?
+source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/debug-agent.sh || exit $?
+source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/symbol-index.sh || exit $?
 
 # Defaults.
 port=
@@ -180,15 +181,12 @@ else
   fi
 fi
 
+ensure-symbol-index-registered || fx-warn "Failed to register ${FUCHSIA_DIR} in symbol-index!"
+
 # We start the client with the flag that tells it to quit the agent when zxdb quits.
 "${FUCHSIA_BUILD_DIR}/host-tools/zxdb" \
   ${connect_ops[@]} \
   "--quit-agent-on-exit" \
-  "--build-dir" "${FUCHSIA_BUILD_DIR}" \
-  "--build-id-dir" "${FUCHSIA_BUILD_DIR}/.build-id" \
-  "--build-id-dir" "${ZIRCON_BUILDROOT}/.build-id" \
-  "--build-id-dir" "${FUCHSIA_DIR}/prebuilt/.build-id" \
-  "--build-id-dir" "${PREBUILT_CLANG_DIR}/lib/debug/.build-id" \
   "--symbol-server" "gs://fuchsia-artifacts-release/debug" \
   "$@"
 
diff --git a/tools/devshell/contrib/fidlcat b/tools/devshell/contrib/fidlcat
--- a/tools/devshell/contrib/fidlcat
+++ b/tools/devshell/contrib/fidlcat
@@ -179,7 +179,8 @@
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
 fx-config-read
-source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../contrib/lib/debug-agent.sh || exit $?
+source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/debug-agent.sh || exit $?
+source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/symbol-index.sh || exit $?
 
 launch_agent=1
 
@@ -339,14 +340,12 @@ if [[ -z "${port}" ]]; then
   port=2345
 fi
 
+ensure-symbol-index-registered || echo "Failed to register ${FUCHSIA_DIR} in symbol-index!"
+
 if [[ ${launch_agent} -eq 1 ]]; then
   if launch_debug_agent "${port}" "" "${agent_out}"; then
     arguments+=("--connect" "$(get-device-addr-resource):${port}")
     arguments+=("--fidl-ir-path" @"${FUCHSIA_BUILD_DIR}"/all_fidl_json.txt)
-    arguments+=("--build-id-dir" "${FUCHSIA_BUILD_DIR}/.build-id")
-    arguments+=("--build-id-dir" "${ZIRCON_BUILDROOT}/.build-id")
-    arguments+=("--build-id-dir" "${FUCHSIA_DIR}/prebuilt/.build-id")
-    arguments+=("--build-id-dir" "${PREBUILT_CLANG_DIR}/lib/debug/.build-id")
     arguments+=("$@")
 
     if [[ ${use_gdb} -eq 1 ]]; then
diff --git a/tools/devshell/contrib/symbol-index b/tools/devshell/contrib/symbol-index
--- a/tools/devshell/contrib/symbol-index
+++ b/tools/devshell/contrib/symbol-index
@@ -37,14 +37,7 @@
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
 fx-config-read
-
-symbol_index="${FUCHSIA_BUILD_DIR}/host-tools/symbol-index"
-
-if [[ ! -e ${symbol_index} ]]; then
-  fx-error "${symbol_index} is not found, make sure you have //bundles:tools (or //tools) in your
-  'fx set' command and 'fx build' was executed successfully."
-  exit 1
-fi
+source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/symbol-index.sh || exit $?
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
@@ -74,12 +67,13 @@ if [[ $1 == "register" ]]; then
     exit 1
   fi
 
-  set -e
-  "${symbol_index}" add "${FUCHSIA_BUILD_DIR}/.build-id" "${FUCHSIA_BUILD_DIR}"
-  "${symbol_index}" add "${ZIRCON_BUILDROOT}/.build-id" "${ZIRCON_BUILDROOT}"
-  "${symbol_index}" add "${FUCHSIA_DIR}/prebuilt/.build-id"
-  "${symbol_index}" add "${PREBUILT_CLANG_DIR}/lib/debug/.build-id"
-  echo "Registered ${FUCHSIA_DIR} successfully!"
+  if ensure-symbol-index-registered; then
+    echo "Registered ${FUCHSIA_DIR} successfully!"
+  else
+    fx-error "Failed to register ${FUCHSIA_DIR}!"
+    exit 1
+  fi
 else
-  exec "${symbol_index}" "$@"
+  symbol-index "$@"
+  exit $?
 fi
