[fx][debugger][fidlcat] launch_debug_agent now checks for existing agent
This permits for a user to start a debug agent with special
configuration and have the fx client connect to it without any changes
from its normal DX.

TEST=Ran the following commands with no agent and a manual one:
     fx debug
     fx debug --port 5000
     fx fidlcat run fuchsia-pkg://fuchsia.com/echo_client_cpp#meta/echo_client_cpp.cmx
     fx fidlcat --port 5000 run fuchsia-pkg://fuchsia.com/echo_client_cpp#meta/echo_client_cpp.cmx

Change-Id: I91679b50593037cad9dff8159e34b497bad7ab48

diff --git a/tools/devshell/contrib/debug b/tools/devshell/contrib/debug
--- a/tools/devshell/contrib/debug
+++ b/tools/devshell/contrib/debug
@@ -162,10 +162,13 @@ if [[ ! -z "${core}" ]]; then
 elif [[ ! -z "${no_agent}" ]]; then
   echo "Not starting a debug agent."
 else
-  launch_debug_agent
-
-  target=$(get-fuchsia-device-addr)
-  connect_ops="--connect [${target}]:${port}"
+  if launch_debug_agent; then
+    target=$(get-fuchsia-device-addr)
+    connect_ops="--connect [${target}]:${port}"
+  else
+    fx-error "Could not launch debug agent. Exiting."
+    exit 1
+  fi
 fi
 
 # We start the client with the flag that tells it to quit the agent when zxdb quits.
diff --git a/tools/devshell/contrib/fidlcat b/tools/devshell/contrib/fidlcat
--- a/tools/devshell/contrib/fidlcat
+++ b/tools/devshell/contrib/fidlcat
@@ -186,19 +186,21 @@ if [[ -z "${port}" ]]; then
   port=2345
 fi
 
-launch_debug_agent
-
-# We start the client with the flag that tells it to quit the agent when zxdb quits.
-"${FUCHSIA_BUILD_DIR}/tools/fidlcat" \
-  "--connect" "[${target}]:${port}" \
-  "--fidl-ir-path" @"${FUCHSIA_BUILD_DIR}"/all_fidl_json.txt \
-  "-s" "${FUCHSIA_BUILD_DIR}" \
-  "-s" "${ZIRCON_BUILDROOT}" \
-  "-s" "${PREBUILT_CLANG_DIR}/lib/debug" \
-  --pretty-print \
-  ${with_process_info} \
-  ${syscalls} \
-  ${verbose} \
-  ${quiet} \
-  ${log_file} \
-  $@
+if launch_debug_agent; then
+  # We start the client with the flag that tells it to quit the agent when zxdb quits.
+  "${FUCHSIA_BUILD_DIR}/tools/fidlcat" \
+    "--connect" "[${target}]:${port}" \
+    "--fidl-ir-path" @"${FUCHSIA_BUILD_DIR}"/all_fidl_json.txt \
+    "-s" "${FUCHSIA_BUILD_DIR}" \
+    "-s" "${ZIRCON_BUILDROOT}" \
+    "-s" "${PREBUILT_CLANG_DIR}/lib/debug" \
+    --pretty-print \
+    ${with_process_info} \
+    ${verbose} \
+    ${quiet} \
+    ${log_file} \
+    $@
+else
+  fx-error "Could not launch debug agent. Exiting."
+  exit 1
+fi
