[fx] Fix format-code warning logic
fxrev.dev/584061 made `fx format-code` fail and print an error if it
encountered a file it didn't know how to format.

This is useful for notification purposes if the user specifies a single
file that `fx format-code` can't format, but it's bad for `fx
format-code --git`, which tries to format all changed files. In that
case it's better to silently skip files that we don't know how to
format.

Likewise, the `--files` flag can take a glob, so it's possible that an
unformattable file is only included incidentally by a glob. Therefore,
we only show the error if the user specified a single file (or a glob
that only matched one file).

Change-Id: Ic0501af452fbfbc0ff37062f1e56ce4cfc0a326e
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/584344
Commit-Queue: Oliver Newman <olivernewman@google.com>
Fuchsia-Auto-Submit: Oliver Newman <olivernewman@google.com>
Reviewed-by: Gary Boone <gboone@google.com>

diff --git a/tools/devshell/contrib/format-code b/tools/devshell/contrib/format-code
--- a/tools/devshell/contrib/format-code
+++ b/tools/devshell/contrib/format-code
@@ -98,6 +98,15 @@ function format-full-file() {
 
 # Format the given file.
 function format-file() {
+  # If the user requested formatting of a single specific file, we want to
+  # loudly alert them to the fact that we can't actually format that file, since
+  # silently exiting would suggest that we *do* know how to format the file and
+  # that it was already properly formatted.
+  must_format=false
+  if $FILES_SPECIFIED && [[ ${#FILES[@]} == 1 ]]; then
+    must_format=true
+  fi
+
   filename="$(basename "$1")"
   case "${filename}" in
     *.c | *.cc | *.cpp | *.h | *.hh | *.hpp | *.proto | *.ts)
@@ -117,8 +126,18 @@ function format-file() {
     *.rs) format-full-file "${RUST_FMT_CMD}" "$1" ;;
     *.triage) format-full-file "${JSON5_FMT_CMD}" "$1";;
     *.persist) format-full-file "${JSON5_FMT_CMD}" "$1";;
-    *.*) fx-error "Unsupported extension for file $1" && exit 1;;
-    *) fx-error "Unable to determine language for file $1" && exit 1;;
+    *.*)
+      if $must_format; then
+        fx-error "Unsupported extension for file $1"
+        exit 1
+      fi
+      ;;
+    *)
+      if $must_format; then
+        fx-error "Unable to determine language for file $1"
+        exit 1
+      fi
+      ;;
   esac
 }
 
@@ -145,6 +164,7 @@ DRY_RUN=
 VERBOSE=
 CHANGED_LINES=
 ALL_FILES=0
+FILES_SPECIFIED=false
 
 fx-config-read
 
@@ -164,6 +184,7 @@ while [ $# -gt 0 ]; do
       ALL_FILES=1
       ;;
     --files=*)
+      FILES_SPECIFIED=true
       GET_FILES=:
       FILES=$(canonicalize "${PWD}" $(zap-commas "${ARG#--files=}"))
       ;;
