[fx][gn-sdk] Replace default key location
This change replaces the path to the set of default SSH credentials for
connecting to Fuchsia devices from the Fuchsia tree and the GN SDK. The
new default paths are as follows:

Identity file (private key): ~/.ssh/fuchsia_ed25519
Public key: ~/.ssh/fuchsia_ed25519.pub
Allowed users: ~/.ssh/authorized_keys

Previously, a jiri hook would generate a per-checkout set of SSH
credentials for communicating with Fuchsia devices. This led to
confusion when accessing a single device from multiple workstations.

This allows for a per-user, per-workstation Fuchsia identity (SSH
keypair) that can be shared between fx and the GN SDK.

Change-Id: I70b2873014d3a902d3db71b9f933b9bcce1131d5
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/387242
Reviewed-by: James Tucker <raggi@google.com>
Reviewed-by: Renato Mangini Dias <mangini@google.com>
Commit-Queue: Wesley Moy <wesleymoy@google.com>
Testability-Review: Renato Mangini Dias <mangini@google.com>

diff --git a/tools/devshell/contrib/make-fuchsia-vol b/tools/devshell/contrib/make-fuchsia-vol
--- a/tools/devshell/contrib/make-fuchsia-vol
+++ b/tools/devshell/contrib/make-fuchsia-vol
@@ -6,8 +6,8 @@
 #### CATEGORY=Other
 ### build a fuchsia persistent disk
 ## usage: fx make-fuchsia-vol [-include-keys]
-##   -include-keys add the keys from $FUCHSIA_DIR/.ssh/authorized_keys
-##                 to the Zircon ZBI
+##   -include-keys add the keys from ~/.ssh/fuchsia_authorized_keys
+##                 to the Zircon ZBI as authorized_keys
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/image_build_vars.sh || exit $?
 
@@ -29,9 +29,13 @@ done
 
 keys_args=()
 if [ "${include_keys}" == 1 ]; then
+  authkeys_path="$(get-ssh-authkeys)" || {
+    fx-error "Cannot continue without a valid authorized keys file."
+    exit 1
+  }
   fx-zbi -o "${FUCHSIA_BUILD_DIR}/fuchsia-extra-keys.zbi" \
     "${FUCHSIA_BUILD_DIR}/${IMAGE_ZIRCONA_ZBI}" --replace \
-    --entry "data/ssh/authorized_keys=${FUCHSIA_DIR}/.ssh/authorized_keys"
+    --entry "data/ssh/authorized_keys=${authkeys_path}"
 
   keys_args+=(-zbi "${FUCHSIA_BUILD_DIR}/fuchsia-extra-keys.zbi")
 fi
diff --git a/tools/devshell/netboot b/tools/devshell/netboot
--- a/tools/devshell/netboot
+++ b/tools/devshell/netboot
@@ -56,6 +56,11 @@ if [[ ! -x "${netboot_script}" ]]; then
   exit 1
 fi
 
+authkeys_path="$(get-ssh-authkeys)" || {
+  fx-error "Cannot continue without a valid authorized keys file."
+  exit 1
+}
+
 tmpdir="${FUCHSIA_BUILD_DIR}.netboot.tmp"
 mkdir "${tmpdir}"
 trap 'rm -rf "${tmpdir}"' EXIT
@@ -71,12 +76,12 @@ cp "${netboot_script}" "${tmpdir}"
 mkdir "${tmpdir}/host_x64"
 cp "${HOST_OUT_DIR}/bootserver" "${tmpdir}/host_x64/bootserver"
 
-# Make a temporary image that adds in the .ssh/authorized_keys file.
+# Make a temporary image that adds in the ~/.ssh/fuchsia_authorized_keys file.
 # Netboot doesn't require special compression. fxb/43305 for more info.
 fx-zbi-default-compression \
   -o "${tmpdir}/${IMAGE_NETBOOT_ZBI}" \
   "${FUCHSIA_BUILD_DIR}/${IMAGE_NETBOOT_ZBI}" \
-  "--entry=data/ssh/authorized_keys=${FUCHSIA_DIR}/.ssh/authorized_keys"
+  "--entry=data/ssh/authorized_keys=${authkeys_path}"
 
 # Now run the copied script, which will use the temporary ZBI.
 "${tmpdir}/netboot.sh" "${name_args[@]}" -1 "$@"
diff --git a/tools/devshell/pave b/tools/devshell/pave
--- a/tools/devshell/pave
+++ b/tools/devshell/pave
@@ -19,7 +19,12 @@ if [[ -n "$name" ]]; then
   name_args+=("-n" "${name}")
 fi
 
-auth_keys_args=(--authorized-keys "${FUCHSIA_DIR}/.ssh/authorized_keys" "$@")
+authkeys_path="$(get-ssh-authkeys)" || {
+  fx-error "Cannot continue without a valid authorized keys file."
+  exit 1
+}
+
+auth_keys_args=(--authorized-keys "${authkeys_path}" "$@")
 if fx-is-bringup; then
   auth_keys_args=()
 fi
diff --git a/tools/devshell/pave-remote b/tools/devshell/pave-remote
--- a/tools/devshell/pave-remote
+++ b/tools/devshell/pave-remote
@@ -67,6 +67,11 @@ while [[ $# -ne 0 ]]; do
   shift
 done
 
+authkeys_path="$(get-ssh-authkeys)" || {
+  fx-error "Cannot continue without a valid authorized keys file."
+  exit 1
+}
+
 if cached=( $(load_remote_info "$host") ); then
   host="${cached[0]}"
   dir="${cached[1]}"
@@ -105,5 +110,5 @@ if "${pave}"; then
     args+=(-n $(get-device-name))
   fi
 
-  ./pave.sh --authorized-keys "${FUCHSIA_DIR}/.ssh/authorized_keys" "${args[@]}"
+  ./pave.sh --authorized-keys "${authkeys_path}" "${args[@]}"
 fi
diff --git a/tools/devshell/qemu b/tools/devshell/qemu
--- a/tools/devshell/qemu
+++ b/tools/devshell/qemu
@@ -24,6 +24,11 @@ for arg in "$@"; do
   fi
 done
 
+authkeys_path="$(get-ssh-authkeys)" || {
+  fx-error "Cannot continue without a valid authorized keys file."
+  exit 1
+}
+
 qemu_dir="${PREBUILT_QEMU_DIR}/bin"
 
 args=(
@@ -34,7 +39,8 @@ args=(
 
 # Construction of a qcow image prevents qemu from writing back to the
 # build-produced image file, which could cause timestamp issues with that file.
-# Construction of the new ZBI adds //.ssh/authorized_keys for SSH access.
+# Construction of the new ZBI adds ~/.ssh/fuchsia_authorized_keys for SSH
+# access.
 imgdir="$(mktemp -d ${FUCHSIA_BUILD_DIR}/tmp.XXX)"
 if [[ ! -d "${imgdir}" ]]; then
   echo >&2 "Failed to create temporary directory"
@@ -45,7 +51,7 @@ trap 'rm -rf "$imgdir"' EXIT
 kernelzbi="${imgdir}/fuchsia-ssh.zbi"
 args+=(-z "${kernelzbi}")
 fx-zbi -o "${kernelzbi}" "${FUCHSIA_BUILD_DIR}/${IMAGE_ZIRCONA_ZBI}" \
-  --entry "data/ssh/authorized_keys=${FUCHSIA_DIR}/.ssh/authorized_keys"
+  --entry "data/ssh/authorized_keys=${authkeys_path}"
 
 if [ -n "$IMAGE_FVM_FOR_EMU" ]; then
   fvmimg="${imgdir}/fvm.blk"
