[fx overnet] re-organize the overnet fx setup
fx ascendd - must persist, like fx serve, run one per host.
fx overnet - connects host ascendd to target overnetstack
fx onet - execute the overnet debug tool

Examples:
  $ fx ascendd &
  $ fx overnet &
  $ fx onet list-peers
  PEER: Peer { id: NodeId { id: 17091909508713590440 }, is_self: true, description: PeerDescription { services: Some(["fuchsia.overnet.protocol.Diagnostic"]) } }
  PEER: Peer { id: NodeId { id: 1097547210250417262 }, is_self: false, description: PeerDescription { services: Some(["fuchsia.overnet.protocol.Diagnostic"]) } }

Change-Id: I00aee4ae48ad3b1835740e9065900b31adda32ec

diff --git a/tools/devshell/contrib/overnet b/tools/devshell/contrib/overnet
--- a/tools/devshell/contrib/overnet
+++ b/tools/devshell/contrib/overnet
@@ -2,10 +2,17 @@
 
 set -e
 
-### start overnet host-pipe to target device
+### start an overnet host-pipe to target device
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
 fx-config-read
 
+
 onet="$FUCHSIA_BUILD_DIR/host-tools/onet"
+
+if ! echo 'conntest' | socat - /tmp/ascendd; then
+  fx-error "ascendd may not be running, overnet connection may fail"
+  fx-error "Run \`fx ascendd\` to start ascendd"
+fi
+
 socat EXEC:"$onet host-pipe" EXEC:"$FUCHSIA_DIR/scripts/fx shell onet host-pipe"
