[fx][regen-goldens] Improve `fx set` hint
This CL improves the error message when no tests targets were found.
First, it prints an error message including the string "regen-goldens"
to make it clear it's coming from there, not from fx test. Second, it
suggests precise --with arguments needed for the goldens the user tried
to regenerate rather than //bundles:tests, which is very large.

Test: fx self-test subcommands/fx_regen_goldens_test
Change-Id: I42b0feadaa9fdad4e37785f106c5c5368996c695
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/646651
Reviewed-by: Yifei Teng <yifeit@google.com>
Commit-Queue: Mitchell Kember <mkember@google.com>

diff --git a/tools/devshell/contrib/regen-goldens b/tools/devshell/contrib/regen-goldens
--- a/tools/devshell/contrib/regen-goldens
+++ b/tools/devshell/contrib/regen-goldens
@@ -47,8 +47,11 @@ fx-config-read
 
 # Each tool $t has a NAME=${t%% *} and DIR=${t##* }, for which there must exist
 # $(dirname $DIR)/BUILD.gn containing golden_test("${NAME}_golden_tests") with
-# goldens_dir="$(basename $DIR)". See //build/testing/golden_test.gni for more
-# information about golden tests. Please keep this list sorted alphabetically.
+# goldens_dir="$(basename $DIR)", and also group("tests") containing
+# ":${NAME}_golden_tests($host_toolchain)". See //build/testing/golden_test.gni
+# for more information about golden tests.
+#
+# Please keep this list sorted alphabetically.
 readonly all_tools=(
     "fidlc tools/fidl/fidlc/goldens"
     "fidldoc tools/fidl/fidldoc/goldens"
@@ -142,9 +145,19 @@ case $exit_code in
         fi
         ;;
     3) # test not found
-        if ! grep -q "//bundles:tests" "$FUCHSIA_BUILD_DIR/args.gn"; then
-            echo
-            echo "Hint: Try again after \`fx set ... --with //bundles:tests\`"
+        echo "Error: Could not find test targets needed to regenerate goldens"
+        with=()
+        for t in "${tools[@]}"; do
+            parent=$(dirname "${t##* }")
+            target="//$parent:${t%% *}_golden_tests"
+            if ! fx-command-run jq -e \
+                    "any(.test.label | startswith(\"$target\"))" \
+                    "$FUCHSIA_BUILD_DIR/tests.json" > /dev/null; then
+                with+=("--with" "//$parent:tests")
+            fi
+        done
+        if [[ ${#with[@]} -gt 0 ]]; then
+            echo "Hint: Try again after \`fx set ... ${with[*]}\`"
         fi
         ;;
 esac
diff --git a/tools/devshell/tests/subcommands/fx_regen_goldens_test b/tools/devshell/tests/subcommands/fx_regen_goldens_test
--- a/tools/devshell/tests/subcommands/fx_regen_goldens_test
+++ b/tools/devshell/tests/subcommands/fx_regen_goldens_test
@@ -5,10 +5,15 @@
 
 ### Test expected behavior of 'fx regen-goldens'
 
+BT_LINKED_DEPS=(
+  "prebuilt/third_party/jq"
+)
+
 BT_FILE_DEPS=(
   "scripts/fx"
   "tools/devshell/contrib/regen-goldens"
   "tools/devshell/lib/fx-cmd-locator.sh"
+  "tools/devshell/jq.fx"
   "tools/devshell/lib/fx-optional-features.sh"
   "tools/devshell/lib/vars.sh"
   "tools/devshell/lib/platform.sh"
@@ -25,7 +30,7 @@ declare fx fxtest_mock fxtest_mock_impl output fidlc_goldens
 # BUILD.gn (data dependencies), and here. So instead of that, regen-goldens
 # verifies them on every run. We export a variable to disable it during tests,
 # since the golden directories do not exist in the test sandbox.
-export REGEN_GOLDENS_SKIP_CHECK
+export REGEN_GOLDENS_SKIP_CHECK=1
 
 BT_SET_UP() {
   source "$BT_TEMP_DIR/tools/devshell/tests/lib/fuchsia-mock.sh"
@@ -134,16 +139,32 @@ TEST_fatal_error_suggests_reset() {
   BT_EXPECT_FILE_DOES_NOT_CONTAIN_SUBSTRING "$output" "Hint:"
 }
 
-TEST_test_not_found_suggests_bundle() {
+TEST_test_not_found_suggests_fx_set() {
   echo "exit 3" > "$fxtest_mock_impl"
-  echo > "$BT_TEMP_DIR/out/default/args.gn"
   BT_EXPECT_FAIL "$fx" regen-goldens fidlc &> "$output"
+  BT_EXPECT_FILE_CONTAINS_SUBSTRING "$output" "Could not find test targets"
   BT_EXPECT_FILE_CONTAINS_SUBSTRING "$output" "Hint:"
-  BT_EXPECT_FILE_CONTAINS_SUBSTRING "$output" "\--with //bundles:tests"
-  # Unless you already have it:
-  echo "--with //bundles:tests" > "$BT_TEMP_DIR/out/default/args.gn"
-  BT_EXPECT_FAIL "$fx" regen-goldens fidlc &> "$output"
-  BT_EXPECT_FILE_DOES_NOT_CONTAIN_SUBSTRING "$output" "Hint:"
+  BT_EXPECT_FILE_CONTAINS_SUBSTRING "$output" "\--with //tools/fidl/fidlc:tests"
+}
+
+TEST_test_not_found_suggests_fx_set_only_with_needed() {
+  cat <<EOS > "$BT_TEMP_DIR/out/default/tests.json"
+[
+  {
+    "test": {
+      "label": "//tools/fidl/fidlc:fidlc_golden_tests(//build/toolchain:host_x64)"
+    }
+  }
+]
+EOS
+  # Based on tests.json, we should infer the exit status 3 was only due to
+  # fidldoc's tests missing, not fidlc, and so only give that hint.
+  echo "exit 3" > "$fxtest_mock_impl"
+  BT_EXPECT_FAIL "$fx" regen-goldens fidlc fidldoc &> "$output"
+  BT_EXPECT_FILE_CONTAINS_SUBSTRING "$output" "Could not find test targets"
+  BT_EXPECT_FILE_CONTAINS_SUBSTRING "$output" "Hint:"
+  BT_EXPECT_FILE_DOES_NOT_CONTAIN_SUBSTRING "$output" "\--with //tools/fidl/fidlc:tests"
+  BT_EXPECT_FILE_CONTAINS_SUBSTRING "$output" "\--with //tools/fidl/fidldoc:tests"
 }
 
 BT_RUN_TESTS "$@"
