[devshell] Improve error message when SSH fails
If we can't set up the reverse SSH tunnel, be more descriptive
about the consequences.

Change-Id: Iab506442eed36d988b33b10d158f0766975e1998

diff --git a/devshell/amber-tunnel b/devshell/amber-tunnel
--- a/devshell/amber-tunnel
+++ b/devshell/amber-tunnel
@@ -16,5 +16,7 @@ fi
 fx-command-run ssh -q -R 8083:localhost:8083 $device_addr exit
 result=$?
 if [[ "${result}" -ne 0 ]]; then
-  echo "ssh exited with a non-zero status: ${result}." >&2
+  echo "Connection to target could not be established,"\
+       "ssh exited with status: ${result}. Updates will fail." >&2
+  exit "${result}"
 fi
