[fx] use shlock instead of flock
Always use shlock, even when flock is available.
Some users on Ubuntu laptops were complaining that flock was leaving the
lock file behind, but had no trouble with shlock.
Upside: behavior on devices that have flock (Linux) and that don't have
flock (e.g. OS X) is now consistent.
Downside: shlock is not reentrant. Shouldn't be a problem for "fx build"
though, and hasn't been a problem for OS X users so far.

Change-Id: I08e4e6bdbf8dcb9af309c1ad8e858896ddc7e18c

diff --git a/devshell/build b/devshell/build
--- a/devshell/build
+++ b/devshell/build
@@ -12,6 +12,7 @@ fx-config-read
 
 readonly LOCK_FILE="${FUCHSIA_DIR}"/.build_lock
 
+# Exit trap to clean up lock file
 function _rmlock () {
   [[ -n "${LOCK_FILE}" ]] && rm -f "${LOCK_FILE}"
 }
@@ -21,25 +22,18 @@ function _rmlock () {
 # and block until it is.
 function locked {
   declare -r cmd="$@"
-
-  if which flock >/dev/null; then
-    flock -n "${LOCK_FILE}" -c true || echo "Locked by ${LOCK_FILE}..."
-    flock "${LOCK_FILE}" -c "${cmd}"
+  # This will cause a deadlock if any subcommand calls back to fx build,
+  # because shlock isn't reentrant by forked processes.
+  if shlock -f "${LOCK_FILE}" -p $$; then
+    trap _rmlock EXIT
+    ${cmd}
+    _rmlock
   else
-    # Some platforms don't have flock, fall back to shlock.
-    # This will cause a deadlock if any subcommand calls back to fx,
-    # because shlock isn't reentrant by forked processes.
-    if shlock -f "${LOCK_FILE}" -p $$; then
-      trap _rmlock EXIT
-      ${cmd}
-      _rmlock
-    else
-      echo "Locked by ${LOCK_FILE}..."
-      while ! shlock -f "${LOCK_FILE}" -p $$; do sleep .1; done
-      trap _rmlock EXIT
-      ${cmd}
-      _rmlock
-    fi
+    echo "Locked by ${LOCK_FILE}..."
+    while ! shlock -f "${LOCK_FILE}" -p $$; do sleep .1; done
+    trap _rmlock EXIT
+    ${cmd}
+    _rmlock
   fi
 }
 
