[build] limit the build more conservatively
* Users can pass -l and -j to override the fx defaults.
* Do not pass -l by default except on macOS.
* Set ulimit high enough to support job count.
* Use goma recommended number of jobs.

Change-Id: I824005510d33cb25922e3eda55965dce8503c905

diff --git a/devshell/build b/devshell/build
--- a/devshell/build
+++ b/devshell/build
@@ -11,22 +11,54 @@ source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
 fx-config-read
 
 function main {
+  local args=()
+  local have_load=false
+  local have_jobs=false
+  while [[ $# -gt 0 ]]; do
+    case "$1" in
+    -l) have_load=true ;;
+    -j) have_jobs=true ;;
+    esac
+    args+=("$1")
+    shift
+  done
+
+  if ! $have_load; then
+    if [[ "$(uname -s)" == "Darwin" ]]; then
+      # Load level on Darwin is quite different from that of Linux, wherein a
+      # load level of 1 per CPU is not necessarily a prohibitive load level. An
+      # unscientific study of build side effects suggests that cpus*20 is a
+      # reaosnable value to prevent catastrophic load (i.e. user can not kill
+      # the build, can not lock the screen, etc).
+      local cpus="$(fx-cpu-count)"
+      args+=("-l" $(($cpus * 20)))
+    fi
+  fi
+
+  if ! $have_jobs; then
+    local concurrency="$(fx-choose-build-concurrency)"
+    # macOS in particular has a low default for number of open file descriptors
+    # per process, which is prohibitive for higher job counts. Here we raise
+    # the number of allowed file descriptors per process if it appears to be
+    # low in order to avoid failures due to the limit. See `getrlimit(2)` for
+    # more information.
+    local min_limit=$((${concurrency} * 2))
+    if [[ $(ulimit -n) -lt "${min_limit}" ]]; then
+      ulimit -n "${min_limit}"
+    fi
+    args+=("-j" "${concurrency}")
+  fi
+
+
   # TERM is passed for the pretty ninja UI
   # PATH is passed as some tools are referenced via $PATH due to platform differences.
   # TMPDIR is passed for Goma on macOS. TMPDIR must be set, or unset, not
   # empty. Some Dart build tools have been observed writing into source paths
   # when TMPDIR="" - it is deliberately unquoted and using the ${+} expansion
   # expression).
-  local max_load=0
-  if [[ "$(uname -s)" == "Darwin" ]]; then
-    # Only limit maximum load on Darwin.
-    max_load="$(fx-cpu-count)"
-  fi
   fx-try-locked env -i TERM="${TERM}" PATH="${PATH}" \
     ${TMPDIR+"TMPDIR=$TMPDIR"} \
-    "${FUCHSIA_DIR}/buildtools/ninja" -j "$(fx-choose-build-concurrency)" \
-                                      -l ${max_load} \
-                                      -C "${FUCHSIA_BUILD_DIR}" "$@"
+    "${FUCHSIA_DIR}/buildtools/ninja" -C "${FUCHSIA_BUILD_DIR}" "${args[@]}"
 }
 
 main "$@"
