Turn format-code into a clone of git-file-format
... but written in bash.

Once we have a few users of this, we'll delete git-file-format.

Change-Id: I4825353cc6a383205cdffd1ce86cda3544ef37cd

diff --git a/devshell/format-code b/devshell/format-code
--- a/devshell/format-code
+++ b/devshell/format-code
@@ -3,19 +3,136 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-## Runs source formatters on modified files using git-file-format
+## Runs source formatters on modified files
 
-# This tool exists because the FIDL formatter is built from head in zircon,
-# and git-file-format isn't smart enough to do that on its own.
+## Usage: fx format-code
+##           [--help] [--dry-run] [--verbose] [--all]
+##           [--files=FILES,[FILES ...]]
+##           [--git]
+##
+##   --help    Prints this message
+##   --dry-run Stops the program short of running the formatters
+##   --all     Formats all code in the git repo
+##   --files   Allows the user to specify files.  Files are comma separated.
+##             Globs are dealt with by bash; fx format-code "--files=foo/*" will
+##             work as expected.
+##    --git    The default; it uses `git diff-index` against the newest parent
+##             commit in the upstream branch (or against HEAD if no such commit
+##             is found).  Files that are locally modified, staged or touched by
+##             any commits introduced on the local branch are formatted.
 
 set -e
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
 
-SCRIPTS_HOME="${FUCHSIA_DIR}/scripts"
-GIT_FMT_CMD="${SCRIPTS_HOME}"/git-file-format
+function usage() {
+  fx-command-help
+}
 
-[[ -x "${ZIRCON_TOOLS_DIR}"/fidl-format ]] || fx-command-run build-zircon -l
+function zap-commas() {
+  echo $1 | tr ',' '\n'
+}
 
-"${GIT_FMT_CMD}" "$@"
+function get-diff-base() {
+  local upstream=$(git rev-parse --abbrev-ref --symbolic-full-name "@{u}" 2>/dev/null)
+  if [[ -z "${upstream}" ]]; then
+    upstream="origin/master"
+  fi
+  local local_commit=$(git rev-list HEAD ^${upstream} --  2>/dev/null | tail -1)
+  if [[ -z "${local_commit}" ]]; then
+    printf "HEAD"
+  else
+    git rev-parse "${local_commit}"^
+  fi
+}
 
+function format-cmd() {
+  if [ -f $1 ]; then
+    case $1 in
+      *.cc) printf "${CLANG_CMD}" ;;
+      *.cmx) printf "${JSON_FMT_CMD}" ;;
+      *.cpp) printf "${CLANG_CMD}" ;;
+      *.dart) printf "${DART_CMD}" ;;
+      *.fidl) printf "${FIDL_CMD}" ;;
+      *.gn) printf "${GN_CMD}" ;;
+      *.gni) printf "${GN_CMD}" ;;
+      *.go) printf "${GO_CMD}" ;;
+      *.h) printf "${CLANG_CMD}" ;;
+      *.hh) printf "${CLANG_CMD}" ;;
+      *.hpp) printf "${CLANG_CMD}" ;;
+      *.ts) printf "${CLANG_CMD}" ;;
+    esac
+  fi
+}
+
+function hg-cmd() {
+  [[ $1 =~ .*\.h ]] && printf "${FIX_HEADER_GUARDS_CMD}"
+}
+
+DRY_RUN=
+VERBOSE=
+
+for ARG in "$@"; do
+  case "${ARG}" in
+    --verbose) VERBOSE="1" ;;
+    --dry-run) DRY_RUN="1" ;;
+    --all) FILES="$(git ls-files)" ;;
+    --git) ;; # We'll figure this out later
+    --files=*) FILES="${ARG#--files=}" ;;
+    --help) usage && exit 1 ;;
+    *) usage && printf "Unknown flag %s\n" "${ARG}" && exit 1 ;;
+  esac
+done
+
+if [ -z "${FILES+x}" ]; then
+  FILES=$(git diff-index --name-only $(get-diff-base))
+fi
+
+if [[ -n "${VERBOSE}" ]]; then
+  printf "Files to be formatted:\n%s\n" "${FILES}"
+fi
+
+fx-config-read
+
+declare BUILDTOOLS_ROOT="${FUCHSIA_DIR}"/buildtools
+declare HOST_OS=$(uname | tr '[:upper:]' '[:lower:]')
+
+[[ "${HOST_OS}" == "darwin" ]] && HOST_OS="mac"
+case $(uname -m) in
+  x86_64) HOST_ARCH="x64" ;;
+  aarch64) HOST_ARCH="arm64" ;;
+  *) echo "Unknown arch $(uname -m)" && exit 1 ;;
+esac
+
+
+declare HOST_PLATFORM="${HOST_OS}-${HOST_ARCH}"
+
+declare CLANG_CMD="${BUILDTOOLS_ROOT}/${HOST_PLATFORM}/clang/bin/clang-format -style=file -fallback-style=Google -sort-includes -i"
+declare DART_CMD="${FUCHSIA_DIR}/topaz/tools/prebuilt-dart-sdk/${HOST_PLATFORM}/bin/dartfmt -w"
+declare FIDL_CMD="${ZIRCON_TOOLS_DIR}/fidl-format -i"
+declare GN_CMD="${BUILDTOOLS_ROOT}/gn format"
+declare GO_CMD="${BUILDTOOLS_ROOT}/${HOST_PLATFORM}/go/bin/gofmt -w"
+declare JSON_FMT_CMD="${FUCHSIA_DIR}"/scripts/style/json-fmt.py
+
+declare FIX_HEADER_GUARDS_CMD="${FUCHSIA_DIR}/scripts/style/check-header-guards.py --fix"
+
+# If there is a FIDL file to fix, and we don't have a copy of fidl-format,
+# generate one.
+for file in ${FILES}; do
+  if [[ ${file} =~ .*\.fidl ]]; then
+    if [[ ! -x "${FIDL_CMD}" ]]; then
+       printf "fidl-format not found: attempting to build it\n"
+       fx-command-run build-zircon -l
+       break
+     fi
+  fi
+done
+
+[[ -n "${DRY_RUN}" ]] && exit
+
+for file in ${FILES}; do
+  declare fcmd=$(format-cmd ${file})
+  [[ -n "${fcmd}" ]] && ${fcmd} "${file}"
+  declare hgcmd=$(hg-cmd ${file})
+  [[ -n "${hgcmd}" ]] && ${hgcmd} "${file}"
+done
