[fuzz] Don't claim success on ZBI failure
This CL looks for `zbi` under ZIRCON_TOOLS_DIR, and makes sure it
succeeds before claiming success.

Change-Id: Icdb2f4e0ca30ef004225e9d9d0a7d08907ea9462

diff --git a/devshell/fuzz b/devshell/fuzz
--- a/devshell/fuzz
+++ b/devshell/fuzz
@@ -324,9 +324,13 @@ add_to_zbi() {
 
   # Copy fuzzers into Fuchsia
   mv "${image}" "${image}.orig"
-  zbi -o "${image}" "${image}.orig" "${fuzz_manifest}"
+  if ! ${ZIRCON_TOOLS_DIR}/zbi -o "${image}" "${image}.orig" "${fuzz_manifest}" ; then
+    mv "${image}.orig" "${image}"
+    fatal "Could not create ${image}"
+  fi
   popd
   echo "Zircon fuzzers added to ${image}"
+  rm -f "${image}.orig"
 }
 
 # Main
