Revert "[fx][go] Update Go toolchain location"
This reverts commit b0817a9ad5086f38e1fb47027a91e94013826ea3.

Reason for revert: Need to redo after rolling third_party/go forward in garnet/manifest/third_party.

Change-Id: Ib50b2c2bee17b8d93b6db549a7f2d8a7a799b744

diff --git a/devshell/go b/devshell/go
--- a/devshell/go
+++ b/devshell/go
@@ -24,11 +24,10 @@ case "${FUCHSIA_ARCH}" in
     GOARCH=amd64
     ;;
 esac
+GOROOT="${FUCHSIA_BUILD_DIR}/goroot"
 
-GOROOT="${FUCHSIA_BUILD_DIR}/tools/goroot"
 if [[ ! -d "${GOROOT}" ]]; then
-  echo >&2 "ERROR: You must build Go before running this command"
-  echo >&2 "Run \"fx build third_party/go:go_runtime\""
+  echo >&2 "ERROR: You must build the goroot before running this command"
   exit 1
 fi
 
