[go] Add --package arg to `fx go`. Sets GOPATH.
The package must have a corresponding gopath directory in
$FUCHSIA_OUT_DIR/gen/gopaths.

Change-Id: Id449272866e480bf25ba59062e3e53a1d9afc149

diff --git a/devshell/go b/devshell/go
--- a/devshell/go
+++ b/devshell/go
@@ -4,9 +4,17 @@
 # found in the LICENSE file.
 
 ### run the go tool in fuchsia target configuration
+## Usage:
+##  fx go <go tool args>
+##  fx go --package=packagename <go tool args>
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
 fx-config-read
+
+function usage {
+  fx-command-help
+  exit 1
+}
 
 case "${FUCHSIA_ARCH}" in
 	arm64)
@@ -25,4 +33,46 @@ if [[ ! -d "${GOROOT}" ]]; then
 	exit 1
 fi
 
-ZIRCON="${FUCHSIA_DIR}/zircon" CC="${GOROOT}/misc/fuchsia/gccwrap.sh" ZIRCON_SYSROOT="${ZIRCON_BUILDROOT}/build-${ZARCH}/sysroot" GOOS=fuchsia GOARCH=${GOARCH} CGO_ENABLED=1 GOROOT="${GOROOT}" "${GOROOT}/bin/go" "$@"
+while getopts ":-:" opt; do
+  case $opt in
+    \?)
+      echo "unrecognized short option: -$OPTARG"
+      usage
+      ;;
+    -)
+        case $OPTARG in
+        package=*) PACKAGE=${OPTARG#*=};;
+        *)
+            echo "unrecognized long option: $OPTARG"
+            usage
+            ;;
+        esac
+      ;;
+  esac
+done
+shift $((OPTIND-1))
+
+## If --package is provided and has a gopath in $FUCHSIA_BUILD_DIR/gen/gopaths,
+## prepend the given gopath to $GOPATH before invoking $GOROOT/bin/go.
+function package_gopath {
+  local package="$1"
+  if [[ -z "$package" ]]; then
+    return 1
+  fi
+
+  gopathdir="$FUCHSIA_BUILD_DIR/gen/gopaths"
+  d="$gopathdir/$package"
+  if [[ ! -d "$d" ]]; then
+    echo >&2 "package not found in $gopathdir: $package"
+    return 1
+  fi
+
+  echo $d
+}
+
+if [[ -n $PACKAGE ]]; then
+  maybe_gopath="$(package_gopath $PACKAGE)"
+  GOPATH="${maybe_gopath}:${GOPATH}"
+fi
+
+ZIRCON="${FUCHSIA_DIR}/zircon" CC="${GOROOT}/misc/fuchsia/gccwrap.sh" ZIRCON_SYSROOT="${ZIRCON_BUILDROOT}/build-${ZARCH}/sysroot" GOOS=fuchsia GOARCH=${GOARCH} CGO_ENABLED=1 GOPATH="${GOPATH}" GOROOT="${GOROOT}" "${GOROOT}/bin/go" "$@"
