[fx][go] Whitespace cleanup + consistent error messages
plus remove unused variable ZARCH

Change-Id: Ib1c3d2fa7c48aebd96585c5151338a8d43125306

diff --git a/devshell/go b/devshell/go
--- a/devshell/go
+++ b/devshell/go
@@ -17,33 +17,31 @@ function usage {
 }
 
 case "${FUCHSIA_ARCH}" in
-	arm64)
-		GOARCH=arm64
-		ZARCH=arm64
-		;;
-	x64)
-		GOARCH=amd64
-		ZARCH=x64
-		;;
+  arm64)
+    GOARCH=arm64
+    ;;
+  x64)
+    GOARCH=amd64
+    ;;
 esac
 GOROOT="${FUCHSIA_BUILD_DIR}/goroot"
 
 if [[ ! -d "${GOROOT}" ]]; then
-	echo >&2 "You must build the goroot before running this command"
-	exit 1
+  echo >&2 "ERROR: You must build the goroot before running this command"
+  exit 1
 fi
 
 while getopts ":-:" opt; do
   case $opt in
     \?)
-      echo "unrecognized short option: -$OPTARG"
+      echo >&2 "ERROR: Unrecognized short option: -$OPTARG"
       usage
       ;;
     -)
         case $OPTARG in
         package=*) PACKAGE=${OPTARG#*=};;
         *)
-            echo "unrecognized long option: $OPTARG"
+            echo >&2 "ERROR: Unrecognized long option: $OPTARG"
             usage
             ;;
         esac
@@ -63,7 +61,7 @@ function package_gopath {
   gopathdir="$FUCHSIA_BUILD_DIR/gen/gopaths"
   d="$gopathdir/$package"
   if [[ ! -d "$d" ]]; then
-    echo >&2 "package not found in $gopathdir: $package"
+    echo >&2 "ERROR: Package not found in $gopathdir: $package"
     return 1
   fi
 
