[images] all scripts use build gen'd image paths
This should avoid future breakage due to builds moving images around.

BLD-167 #done

Change-Id: I2393603c23eb62c84bfd7ba043f0075dfa70c4cc

diff --git a/devshell/mkzedboot b/devshell/mkzedboot
--- a/devshell/mkzedboot
+++ b/devshell/mkzedboot
@@ -108,14 +108,13 @@ unmountcmd
 # Seek offset*lba/4mb
 # Write with osync
 
-install_image_path="${FUCHSIA_BUILD_DIR}/images/install-${board}.blk"
 if $include_install; then
-  if [[ ! -f "${install_image_path}" ]]; then
-    echo >&2 "Install image not found at ${install_image_path} did you build it?"
+  if [[ ! -f "${FUCHSIA_BUILD_DIR}/${IMAGE_INSTALLER_RAW}" ]]; then
+    echo >&2 "Install image not found at ${FUCHSIA_BUILD_DIR}/${IMAGE_INSTALLER_RAW} did you build it?"
     exit 1
   fi
 
-  install_image_size=$(wc -c "${install_image_path}" | awk '{print $1}')
+  install_image_size=$(wc -c "${FUCHSIA_BUILD_DIR}/${IMAGE_INSTALLER_RAW}" | awk '{print $1}')
   # Add some slack, like the build does, as the file size doesn't represent the
   # volume size and there's no host tool that presently will print the
   # superblock volume size data.
@@ -139,14 +138,14 @@ echo "done"
 
 echo "Writing zedboot for EFI"
 unmountcmd
-dd if="${FUCHSIA_BUILD_DIR}/images/zedboot.esp.blk" of="${USB_DEVICE}" seek=${esp_offset}
+dd if="${FUCHSIA_BUILD_DIR}/${IMAGE_ZEDBOOT_ESP}" of="${USB_DEVICE}" seek=${esp_offset}
 echo "Writing zedboot for Cros"
 unmountcmd
-dd if="${FUCHSIA_BUILD_DIR}/images/zedboot.vboot" of="${USB_DEVICE}" seek=${vboot_offset}
+dd if="${FUCHSIA_BUILD_DIR}/${IMAGE_ZEDBOOT_VBOOT}" of="${USB_DEVICE}" seek=${vboot_offset}
 if $include_install; then
   echo "Writing install partition"
   unmountcmd
-  dd if="${install_image_path}" of="${USB_DEVICE}" seek=${install_offset} bs=4194304
+  dd if="${FUCHSIA_BUILD_DIR}/${IMAGE_INSTALLER_RAW}" of="${USB_DEVICE}" seek=${install_offset} bs=4194304
 fi
 echo "done"
 
