[mkzedboot] Use a file descriptor to lock device
On systems with an automounting daemon, mkzedboot could fail due to EBUSY and
other errors returned by the host operating system due to races with the
automounter. On those systems the event to rescan the partition table, thus
causing automounting occurs when the raw disk device has all open file
descriptors closed. As such, this patch holds open a file descriptor until
all operations that modify the disk are completed.

Change-Id: Ifcab97918bc5b8d6e191e096fbe5ecaa132bee6d

diff --git a/devshell/mkzedboot b/devshell/mkzedboot
--- a/devshell/mkzedboot
+++ b/devshell/mkzedboot
@@ -53,36 +53,33 @@ fi
 echo >&2 "Changing ownership of ${USB_DEVICE} to ${USER}"
 sudo chown "${USER}" "${USB_DEVICE}"
 
-# Linux doesn't automount things aggressively, so no work to do.
-unmountcmd() {
-  return 0
+echo >&2 "Opening device..."
+# We open the device and hold onto an fd for the duration of our modifications.
+# This prevents automounting solutions from observing a final close and
+# rescanning the partition table until we're all done making changes -
+# particularly important on macOS where users would otherwise receive
+# EAGAIN/EBUSY and so on.
+open_device() {
+  case "$(uname)" in
+  Darwin)
+    if ! diskutil quiet unmountDisk "${USB_DEVICE}"; then
+      echo >&2 "Failed to unmount ${USB_DEVICE}, cannot continue"
+      exit 1
+    fi
+    ;;
+  esac
+  exec 3>>"${USB_DEVICE}"
 }
-
-# MacOS is really persistent about remounting disks after the raw block device
-# is closed, so, keep doing this. In the future we will replace CGPT with our
-# own tool that can do everything in one shot, like make-fuchsia-vol does. The
-# hack here keeps an open reference to the disk device, which prevents
-# re-initialization of the gpt driver.
-if [[ "$(uname)" == "Darwin" ]]; then
-  echo
-  echo "### NOTE:"
-  echo "### NOTE: Click 'ignore' on any MacOS disk dialog boxes"
-  echo "### NOTE:"
-  echo
-
-  unmountcmd() {
-    # ignore errors, as we're just making sure it remains unmounted
-    diskutil quiet unmountDisk ${USB_DEVICE} || return 0
-  }
-fi
+close_device() {
+  echo >&2 "Closing device."
+  exec 3>&-
+}
+open_device
 
 # Destroy any existing GPT/MBR on the device and re-create
 echo "Create new GPT partition table... "
-unmountcmd
 "${FUCHSIA_BUILD_DIR}/tools/cgpt" create "${USB_DEVICE}"
-unmountcmd
 "${FUCHSIA_BUILD_DIR}/tools/cgpt" boot -p "${USB_DEVICE}"
-unmountcmd
 echo "done"
 
 echo "Create new partitions... "
@@ -91,9 +88,7 @@ esp_size=$(((63*1024*1024)/512))
 vboot_size=$(((64*1024*1024)/512))
 esp_offset=2048
 vboot_offset=$(($esp_size + $esp_offset))
-unmountcmd
 "${FUCHSIA_BUILD_DIR}/tools/cgpt" add -s "${esp_size}" -t efi -b "${esp_offset}" -l esp "${USB_DEVICE}"
-unmountcmd
 "${FUCHSIA_BUILD_DIR}/tools/cgpt" add -s "${vboot_size}" -t kernel -b "${vboot_offset}" -l zedboot "${USB_DEVICE}"
 
 # NOTE: Ok, so here goes some stuff. I could have written a much smarter "dd"
@@ -129,25 +124,22 @@ if $include_install; then
   install_offset=$(( (($install_min_offset * 512) + 4194303) / 4194304))
   # The lba offset of that is:
   install_lba_offset=$(($install_offset * 8192))
-  unmountcmd
   "${FUCHSIA_BUILD_DIR}/tools/cgpt" add -s "${install_size}" -t "48435546-4953-2041-494E-5354414C4C52" -b "${install_lba_offset}" -l install "${USB_DEVICE}"
 fi
-unmountcmd
 "${FUCHSIA_BUILD_DIR}/tools/cgpt" add -i 2 -T 1 -S 1 -P 2 "${USB_DEVICE}"
 echo "done"
 
 echo "Writing zedboot for EFI"
-unmountcmd
 dd if="${FUCHSIA_BUILD_DIR}/${IMAGE_ZEDBOOT_ESP}" of="${USB_DEVICE}" seek=${esp_offset}
 echo "Writing zedboot for Cros"
-unmountcmd
 dd if="${FUCHSIA_BUILD_DIR}/${IMAGE_ZEDBOOT_VBOOT}" of="${USB_DEVICE}" seek=${vboot_offset}
 if $include_install; then
   echo "Writing install partition"
-  unmountcmd
   dd if="${FUCHSIA_BUILD_DIR}/${IMAGE_INSTALLER_RAW}" of="${USB_DEVICE}" seek=${install_offset} bs=4194304
 fi
 echo "done"
+
+close_device
 
 case "$(uname)" in
   Linux)
