[mkzedboot] one mkzedboot for all your zedbooting
mkvbootzedboot which was really now "make unified zedboot" is now promoted to
replace the "mkzedboot" command.

A few minor changes to improve the UX are added, specifically:
 * Slightly improved error message when the device doesn't look like USB
 * Produce a message before `sudo chown` to be explicit about the password request.

Change-Id: Ifbc15c8422123b5406c60fdbc71286d62ceea96d

diff --git a/devshell/mkzedboot b/devshell/mkzedboot
--- a/devshell/mkzedboot
+++ b/devshell/mkzedboot
@@ -3,47 +3,102 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-### make a zedboot configuration in a target directory
+### make a zedboot USB key
 
-## usage: fx mkzedboot <root of external drive>
-## Builds Fuchsia bootloader and zedboot and copies it to a drive of
-## your choice. Makes zedboot the default boot option.
+## usage: fx mkzedboot [options] <usb device>
+##  -f  force writing to a non-usb target
 
 set -e
 
-source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
-fx-config-read
+source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/image_build_vars.sh
 
-if [[ $# -ne 1 ]]; then
-  fx-command-help
+force=false
+if [[ "$1" == "-f" ]]; then
+  shift
+  force=true
+fi
+
+is_usb() {
+  if ! ${force}; then
+    fx-command-run list-usb-disks | grep "$1"
+  fi
+}
+
+USB_DEVICE="$1"
+if [[ -z "${USB_DEVICE}" ]]; then
+  echo >&2 "device argument required"
+  echo "USB disks:"
+  fx-command-run list-usb-disks
+  exit 1
+fi
+if ! is_usb "${USB_DEVICE}"; then
+  echo >&2 "${USB_DEVICE} does not look like a USB device, use -f to force, or pick from below"
+  echo "USB disks:"
+  fx-command-run list-usb-disks
   exit 1
 fi
 
-if [[ ! -d "$1" ]]; then
-  echo >&2 "error: Drive at $1 does not appear to be mounted."
-  exit 1
+echo >&2 "Changing ownership of ${USB_DEVICE} to ${USER}"
+sudo chown "${USER}" "${USB_DEVICE}"
+
+# Linux doesn't automount things aggressively, so no work to do.
+unmountcmd=""
+# MacOS is really persistent about remounting disks after the raw block device
+# is closed, so, keep doing this. In the future we will replace CGPT with our
+# own tool that can do everything in one shot, like make-fuchsia-vol does. The
+# hack here keeps an open reference to the disk device, which prevents
+# re-initialization of the gpt driver.
+if [[ "$(uname)" == "Darwin" ]]; then
+  echo
+  echo "### NOTE:"
+  echo "### NOTE: Click 'ignore' on any MacOS disk dialog boxes"
+  echo "### NOTE:"
+  echo
+
+  unmountcmd="diskutil quiet unmountDisk ${USB_DEVICE}"
 fi
 
-drive_dir=$1
-efi_target_dir="$1/EFI/BOOT"
+# Destroy any existing GPT/MBR on the device and re-create
+echo "Create new GPT partition table... "
+$unmountcmd
+"${FUCHSIA_BUILD_DIR}/tools/cgpt" create "${USB_DEVICE}"
+$unmountcmd
+"${FUCHSIA_BUILD_DIR}/tools/cgpt" boot -p "${USB_DEVICE}"
+$unmountcmd
+echo "done"
 
-# Do a zircon build, and copy the bootloader to drive
-fx-command-run build-zircon
+echo "Create new partitions... "
+# ESP needs to be a FAT compatible size
+esp_size=$(((63*1024*1024)/512))
+vboot_size=$(((64*1024*1024)/512))
+esp_offset=2048
+vboot_offset=$(($esp_size + $esp_offset))
+$unmountcmd
+"${FUCHSIA_BUILD_DIR}/tools/cgpt" add -s "${esp_size}" -t efi -b "${esp_offset}" -l esp "${USB_DEVICE}"
+$unmountcmd
+"${FUCHSIA_BUILD_DIR}/tools/cgpt" add -s "${vboot_size}" -t kernel -b "${vboot_offset}" -l zedboot "${USB_DEVICE}"
+$unmountcmd
+"${FUCHSIA_BUILD_DIR}/tools/cgpt" add -i 2 -T 1 -S 1 -P 2 "${USB_DEVICE}"
+echo "done"
 
-mkdir -p "${efi_target_dir}"
-cp "${ZIRCON_BUILD_DIR}/bootloader/bootx64.efi" "${efi_target_dir}/BOOTX64.EFI"
+echo "Building zedboot partitions..."
+fx-command-run build "images/zedboot-${ZIRCON_PROJECT}.vboot" "images/zedboot-${ZIRCON_PROJECT}.esp.blk"
+echo "done"
 
-ZEDBOOT_IMAGE="images/zedboot-${ZIRCON_PROJECT}.bin"
+echo "Writing zedboot for EFI"
+$unmountcmd
+dd if="${FUCHSIA_BUILD_DIR}/images/zedboot-${ZIRCON_PROJECT}.esp.blk" of="${USB_DEVICE}" seek=${esp_offset}
+echo "Writing zedboot for Cros"
+$unmountcmd
+dd if="${FUCHSIA_BUILD_DIR}/images/zedboot-${ZIRCON_PROJECT}.vboot" of="${USB_DEVICE}" seek=${vboot_offset}
+echo "done"
 
-# Build the Zedboot image.
-fx-command-run build "$ZEDBOOT_IMAGE"
+case "$(uname)" in
+  Linux)
+    eject "${USB_DEVICE}"
+    ;;
+  Darwin)
+    diskutil eject "${USB_DEVICE}"
+    ;;
+esac
 
-# Copy zedboot.bin to drive
-cp -f "${FUCHSIA_BUILD_DIR}/${ZEDBOOT_IMAGE}" "${drive_dir}/zedboot.bin"
-
-# Set zedboot as the default boot option, with a timeout of 0
-# (i.e. boot instantly into zedboot)
-rm -f "${drive_dir}/CMDLINE"
-echo 'bootloader.default=zedboot bootloader.timeout=0' > "${drive_dir}/CMDLINE"
-
-echo "Bootloader + zedboot loaded to $1"
