[serve-updates] make UI more like `fx boot`
serve-updates now runs in the foreground and reports on the state of the SSH
tunnel. It also makes a reasonable attempt make sure that amber-srv is still
running. It no longer leaks amber-srv, so updating amber-srv now works, as
does switching to a new build directory with `fx set`.

The ssh tunnel still leaks when this script is shutdown, as there's no
protocol over ssh to remove a forward after it's been setup except to tear
down the entire control socket (which would terminate any active shells).
Given that it's a remote forward, this should be mostly non-destructive, and
the leak case should not have any major negative effects for the most common
use case of a single unnamed device.

The output from amber-srv is also suppressed so as to not produce output
about the amber http requests.

Change-Id: I94c25208d0a19071ba66a6ec67ff11b6d2cd3aca

diff --git a/devshell/serve-updates b/devshell/serve-updates
--- a/devshell/serve-updates
+++ b/devshell/serve-updates
@@ -3,12 +3,91 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-### start the update server and open a tunnel to the fuchsia target so
-### it can reach the server
+### start the update server and attach to a running fuchsia device
+## usage: fx serve-updates [-v] [-d <device>]
+##   -v verbose (do not suppress amber-srv output)
+##   -d <device> to specify a specific target device
+##
+## -v must come before -d.
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
 fx-config-read
 
-fx-command-run run-update-svr -d
+# Flag order restrictions exist because we're using the get-device-addr helper
+# from vars.sh which needs -d to appear in $1 in order to work.
+verbose=false
+if [[ "$1" == "-v" ]]; then
+  verbose=true
+  shift
+fi
 
-fx-command-run amber-tunnel "$@"
+# Recover from present situation by finding any already-running amber-srv
+amber_srv_pid=$(pgrep amber-srv)
+cleanup() {
+  if [[ -n "${amber_srv_pid}" ]]; then
+    if kill -0 "${amber_srv_pid}" 2> /dev/null; then
+      kill -TERM "${amber_srv_pid}" 2> /dev/null
+    fi
+  fi
+  wait 2> /dev/null
+}
+trap cleanup EXIT
+
+if [[ -z "${amber_srv_pid}" ]]; then
+  if [[ "${verbose}" = true ]]; then
+    ${FUCHSIA_BUILD_DIR}/host_x64/amber-srv -d ${FUCHSIA_BUILD_DIR} &
+  else
+    ${FUCHSIA_BUILD_DIR}/host_x64/amber-srv -d ${FUCHSIA_BUILD_DIR} > /dev/null &
+  fi
+  amber_srv_pid=$!
+fi
+
+# Allow a little slack for amber-srv to startup, that way the first kill -0 will catch a dead amber-srv.
+sleep 0.1
+if ! kill -0 "${amber_srv_pid}" 2> /dev/null; then
+  echo "Amber Server died, exiting"
+  wait
+  exit $?
+fi
+
+device_addr=
+update_device_addr() {
+  device_addr=$(get-device-addr)
+  if [[ -z "${device_addr}" ]]; then
+    device_addr="$(fx-command-run netaddr --fuchsia 2>/dev/null)"
+  fi
+}
+
+first=true
+while true; do
+  if ! kill -0 "${amber_srv_pid}" 2> /dev/null; then
+    echo "Amber Server died, exiting"
+    amber_srv_pid=
+    exit 1
+  fi
+
+  update_device_addr
+  if [[ -z "${device_addr}" ]]; then
+    echo "No device found, waiting..."
+    sleep 1
+    continue
+  fi
+
+  # If the tunnel is still alive, then we'll just sleep a bit and continue
+  if fx-command-run ssh -q -O check "${device_addr}" 2> /dev/null; then
+    if $first; then
+      echo "Ready to push packages!"
+    fi
+    first=false
+    sleep 1
+    continue
+  else
+    echo "SSH Tunnel lost, restarting..."
+  fi
+
+  echo "SSH Tunnel connecting to ${device_addr}..."
+  fx-command-run ssh -q -R 8083:localhost:8083 "${device_addr}" -- 'echo "Ready to push packages!"'
+  first=false
+done
+
+# See EXIT trap above for cleanup that occurs
