[fx] Add `fx use`; drop --release from `fx set`
This adds a new command `fx use` to simply switch between
different build directories previously created with `fx set`.

`fx set` no longer takes a --release flag and the default build
directory name is just out/${target_cpu}.  The --build-dir switch
is deprecated in favor of just passing the build directory as an
argument, closer to the `gn gen` command-line syntax.  To set up a
release build in a separate directory like `fx set x64 --release`
did before, now do `fx set x64 out/release-x64 --variant release`.

TO-847 #comment `fx set`/`fx use` updates to drop `--release`

Change-Id: I8611450dd53f4ef904a4b2451ab9aeb847502b2b

diff --git a/devshell/set b/devshell/set
--- a/devshell/set
+++ b/devshell/set
@@ -5,22 +5,24 @@
 
 ### set build configuration
 
-## usage: fx set TARGET
-##               [--release] [--packages P1,P2,...]
+## usage: fx set TARGET [[--build-dir] OUTDIR]
+##               [--packages P1,P2,...]
 ##               [--netboot] [--bootfs]
-##               [--build-dir DIR]
 ##               [--args ARG] [--help-args [ARG]] [--variant VARIANT]
 ##               [--goma|--no-goma] [--no-ensure-goma]
 ##               [--goma-dir DIR]
 ##               [--ccache|--no-ccache]
 ##
-## where TARGET is x64, arm64
+## where TARGET is x64 or arm64
 ##
-## Sets build options.
+## OUTDIR is the directory (relative to FUCHSIA_DIR) where the build
+## output goes.  Defaults to "out/TARGET".
+##
+## Sets build options and runs `gn gen OUTDIR` (via //build/gn/gen.py).
 ##
 ## optional arguments:
-##   --release             Build the release variant (e.g., more compiler
-##                         optimizations, less debugging information).
+##   --build-dir OUTDIR    Using this option is deprecated.  It's the same
+##                         as just giving OUTDIR as a non-option argument.
 ##   --packages            Include the listed packages (separated by commas) in the
 ##                         system build. Defaults to the default set of packages
 ##                         for the current layer (e.g., "garnet/packages/default"
@@ -50,9 +52,6 @@
 ##                         If --help-args is used alone, all GN build arguments
 ##                         are displayed (lots of output).
 ##                         This option requires an existing build directory.
-##   --build-dir           The directory (relative to FUCHSIA_DIR) into which to
-##                         generate the build system. Defaults to
-##                         "out/<variant>-<arch>".
 ##   --goma|--no-goma      Whether to use the goma service during the build. Goma
 ##                         attempts to make builds faster using remote build
 ##                         servers. Defaults to detecting whether goma is installed
@@ -106,11 +105,7 @@ function main {
   local ensure_goma=1
   local ccache
   while [[ $# -ne 0 ]]; do
-    case $1 in
-      --release)
-        gen_args="${gen_args} --release"
-        variant=release
-        ;;
+    case "$1" in
       --packages)
         if [[ $# -lt 2 ]]; then
           fx-command-help
@@ -130,11 +125,13 @@ function main {
         extra_packages="${extra_packages},build/packages/bootfs"
         gen_args="${gen_args} --args bootfs_packages=true"
         ;;
+      # TODO(mcgrathr): Remove this after a deprecation period.
       --build-dir)
         if [[ $# -lt 2 ]]; then
           fx-command-help
           return 1
         fi
+        echo >&2 "NOTE: The --build-dir switch is deprecated; give $2 alone."
         build_dir="$2"
         shift
         ;;
@@ -196,9 +193,18 @@ function main {
         gen_args="${gen_args} --ide=$2"
         shift
         ;;
-      *)
+      --*)
         fx-command-help
         return 1
+        ;;
+      *)
+        # A non-option argument is the build_dir, but there can be only one.
+        if [[ -n "$build_dir" ]]; then
+          fx-command-help
+          return 1
+        fi
+        build_dir="$1"
+        ;;
     esac
     shift
   done
@@ -243,14 +249,10 @@ function main {
     fi
   fi
 
-  if [[ -n "${build_dir}" ]]; then
-    gen_args="${gen_args} --build-dir ${build_dir}"
-  else
-    # gen.py defaults to determining the build directory from the variant and
-    # the arch. We replicate that logic here rather than passing a redundant
-    # argument to gen.py.
-    build_dir="out/${variant}-${arch}"
-  fi
+  # This is presumably gen.py's default, but always force it so this
+  # code doesn't have to know what gen.py's default logic is.
+  build_dir="${build_dir:-out/${arch}}"
+  gen_args="${gen_args} --build-dir ${build_dir}"
 
   # If a goma directory wasn't specified explicitly then default to "~/goma".
   if [[ -z "${goma_dir}" ]]; then
@@ -273,15 +275,10 @@ function main {
     gen_args="${gen_args} --ccache"
   fi
 
-  # Update print-vars if you add or remove anything from this list.
-  cat >"${FUCHSIA_CONFIG}" <<END
-# Generated by "fx set".
-FUCHSIA_BUILD_DIR="${build_dir}"
-FUCHSIA_VARIANT="${variant}"
-FUCHSIA_ARCH="${arch}"
-END
-
+  # If this fails, we won't update .config.
   "${FUCHSIA_DIR}/build/gn/gen.py" ${gen_args} "$@" || return $?
+
+  fx-config-write "${build_dir}"
 
   if [[ "${use_goma}" -eq 1 ]] && [[ "${ensure_goma}" -eq 1 ]]; then
     if ! [[ $("${goma_dir}/gomacc" port) =~ ^[0-9]+$ ]]; then
