[set-device] introduce a default-device concept
Common use:

  fx set x64
  fx set-device my-x64-device-name

  fx set arm64
  fx set-device my-arm64-device-name

After the above, when `fx use out/x64` the default device for `fx serve` and
other such scripts will be "my-x64-device-name", and when `fx use out/arm64`,
it will be "my-arm64-device-name".

Users can override the default device for a single command invocation using
the global fx flag `-d`:
  fx -d <device-name> <command>

The set-device command persists to a file that lives alongside the build dir,
specifically `${FUCHSIA_BUILD_DIR}.device`. It is kept outside the build dir
as a convenience in order to not be clobbered by `gn clean`.

Test: Run `fx -x boot`, observe no device is specified (-a flag)
Test: Run `fx set-device`, observe pair is set
Test: Run `fx -x boot`, observe pair is passed to -a.
Test: Run `fx -d my-device-name -x boot` observe device is passed to -a.
Test: Run `fx -x serve` observe -a also has device name.
Test: Run `fx set-device foo-bar-baz-quux`, then `fx -x shell`, observe failure to connect (device does not exist)
Test: Run `fx help set-device`, observe help documentation.
Test: Run `fx`, observe documented -d flag.
Change-Id: I078e884ee7ec0a0166d5171ce9d80d16cbba771a

diff --git a/devshell/shell b/devshell/shell
--- a/devshell/shell
+++ b/devshell/shell
@@ -5,16 +5,12 @@
 
 ### start a remote interactive shell in the target device
 
-## usage: fx shell [-h|--help] [-d|--device <device>] [<command>]
+## usage: fx shell [-h|--help] [<command>]
 ##
-## Creates an SSH connection with a device and executes a command
-## (if specified) on the device.
+## Creates an SSH connection with a device and executes a command.
 ##
 ## Arguments:
 ##   -h|--help    Print out this message.
-##   -d|--device  Fuchsia link-local name of the device. If not
-##                specified, will connect to the only available
-##                device on the link-local network.
 
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
 
@@ -23,21 +19,16 @@ case $1 in
   fx-command-help
   exit 0
   ;;
-  -d|--device)
-  shift  # name
-  if [[ -z "$1" ]]; then
-      echo "Missing parameter: <device>" >&2
-      fx-command-help
-      exit 1
-  fi
-  device="$1"
-  shift  # value
-  ;;
 esac
 
+device_addr="$(get-fuchsia-device-addr)"
+if [[ -z "${device_addr}" ]]; then
+  echo >&2 "Device not found"
+  exit 1
+fi
 # Note: I know there are people who don't like the host-key message, but DO NOT
 # apply -q here, it silences error messages and makes network and configuration
 # failures much harder to diagnose when helping people. The control master will
 # mean you only get one per TCP socket, which is once per newly booted host.
 # It's not a huge burden compared to end user support.
-fx-command-exec ssh "$(fx-command-run netaddr --fuchsia "${device}")" "$@"
+fx-command-exec ssh "${device_addr}" "$@"
