[rust] Make update-rustc-third-party work on Mac again
Made sure to include the buildtools cmake in the path, since it isn’t always
installed on Macs.

Also set up CFLAGS and LDFLAGs to point to a homebrew installed openssl
for the build script of the openssl crate.

Also changed the run of cargo vendor so that it would put build results in
the Fuchsia out directory instead of in the source tree.

Testing: built on Mac
Change-Id: Ic20d9729632d6f778849a8de8cbc0d1672fa5a54

diff --git a/devshell/update-rustc-third-party b/devshell/update-rustc-third-party
--- a/devshell/update-rustc-third-party
+++ b/devshell/update-rustc-third-party
@@ -24,9 +24,22 @@ case "$(uname -s)" in
   *) echo "Error: unrecognized OS"; exit 1;;
 esac
 
+if [[ "$OS" = "mac-x64" ]]; then
+  if ! [[ -x "$(command -v brew)" ]]; then
+    echo >&2 "'brew' binary not found"
+    echo >&2 "A homebrew <https://brew.sh> installation of opensslis required in order to update"       echo >&2 "Rust third party crates on the Mac."
+    exit 1
+  fi
+
+  declare -x PATH=$FUCHSIA_DIR/buildtools/$OS/cmake/bin:$PATH
+  declare -x LDFLAGS="-L$(brew --prefix)/opt/openssl/lib"
+  declare -x CPPFLAGS="-I$(brew --prefix)/opt/openssl/include"
+fi
+
 export RUSTC=$FUCHSIA_DIR/buildtools/$OS/rust/bin/rustc
 
 (cd $FUCHSIA_DIR; $FUCHSIA_DIR/buildtools/$OS/rust/bin/cargo run \
+  --target-dir $FUCHSIA_DIR/out/cargo_vendor_target \
   --manifest-path $FUCHSIA_DIR/third_party/rust-mirrors/cargo-vendor/Cargo.toml \
   -- vendor --sync $FUCHSIA_DIR/third_party/rust-crates/rustc_deps/Cargo.toml \
   $FUCHSIA_DIR/third_party/rust-crates/rustc_deps/vendor)
