[ffx] wrapper script runs via fx
Fix two issues:
- fx no longer respects $FUCHSIA_DIR, this shouldn't either.
- Running via fx in order to pick up default target for wfh flows.

Fixed: 68358
Fixed: 70788
Change-Id: I5b21ab064d5048439d427370dc1958f87f6090f0
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/490003
Reviewed-by: Jordon Wing <jwing@google.com>
Reviewed-by: Matthew Boetger <boetger@google.com>
Fuchsia-Auto-Submit: James Tucker <raggi@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>

diff --git a/src/developer/ffx/scripts/ffx b/src/developer/ffx/scripts/ffx
--- a/src/developer/ffx/scripts/ffx
+++ b/src/developer/ffx/scripts/ffx
@@ -3,27 +3,20 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-fuchsia_dir="${FUCHSIA_DIR}"
-if [[ -z "${fuchsia_dir}" ]]; then
-  # We walk the parent directories looking for .jiri_root rather than using
-  # BASH_SOURCE so that we find the fuchsia_dir enclosing the current working
-  # directory instead of the one containing this file in case the user has
-  # multiple source trees and is picking up this file from another one.
-  fuchsia_dir="$(pwd)"
-  while [[ ! -d "${fuchsia_dir}/.jiri_root" ]]; do
-    fuchsia_dir="$(dirname "${fuchsia_dir}")"
-    if [[ "${fuchsia_dir}" == "/" ]]; then
-      echo "Cannot find Platform Source Tree containing $(pwd)"
-      exit 1
-    fi
-  done
-fi
+# We walk the parent directories looking for .jiri_root rather than using
+# BASH_SOURCE so that we find the fuchsia_dir enclosing the current working
+# directory instead of the one containing this file in case the user has
+# multiple source trees and is picking up this file from another one.
+#
+# NOTE: The FUCHSIA_DIR environment variable is ignored here because it
+# could point to a different Fuchsia checkout in some developer setups.
+fuchsia_dir="$(pwd)"
+while [[ ! -d "${fuchsia_dir}/.jiri_root" ]]; do
+  fuchsia_dir="$(dirname "${fuchsia_dir}")"
+  if [[ "${fuchsia_dir}" == "/" ]]; then
+    echo "Cannot find Platform Source Tree containing $(pwd)"
+    exit 1
+  fi
+done
 
-build_dir="${fuchsia_dir}/$(<"${fuchsia_dir}"/.fx-build-dir)" || exit $?
-
-if ! [[ -x "${build_dir}/host-tools/ffx" ]]; then
-  echo >&2 "ffx is missing! Building ffx!"
-  "${fuchsia_dir}/.jiri_root/bin/fx" build ffx || exit $?
-fi
-
-exec "${build_dir}"/host-tools/ffx "$@"
+exec "${fuchsia_dir}"/scripts/fx ffx "$@"
