[fx] Support --enable and disabled by default for optional features
Change-Id: I7a1a6030b4e18ad17ed09589441164196ed6552f
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/463970
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Reviewed-by: Gary Boone <gboone@google.com>
Fuchsia-Auto-Submit: Renato Mangini Dias <mangini@google.com>

diff --git a/scripts/fx b/scripts/fx
--- a/scripts/fx
+++ b/scripts/fx
@@ -16,25 +16,27 @@ function help_global_options {
   cat <<END
 
 Global fx options: fx [OPTION] ${cmd} ...
-  --dir=BUILD_DIR       Path to the build directory to use when running COMMAND.
-  --disable=FEATURE     Disable a feature (non-persistent).
-                        Valid values for FEATURE: [$(list_optional_features)]
-  -d=DEVICE[:SSH_PORT]  Target a specific device.
-                        DEVICE may be a Fuchsia device name to be resolved using
-                        device-finder or an IP address.
-                        An IPv4 address must be specified directly, while an IPv6
-                        need to be surrounded by brackets.
-                        SSH_PORT, if specified, will be used for all commands
-                        that rely on SSH to connect to the device instead of the
-                        default SSH port (22).
-                        Note: See "fx help set-device" for more help and to set
-                        the default device for a BUILD_DIR.
-  -i                    Iterative mode.  Repeat the command whenever a file is
-                        modified under your Fuchsia directory, not including
-                        out/.
-  -x                    Print commands and their arguments as they are executed.
-  -xx                   Print extra logging of the fx tool itself (implies -x)
+  --dir=BUILD_DIR           Path to the build directory to use when running COMMAND.
+  -d=DEVICE[:SSH_PORT]      Target a specific device.
+                            DEVICE may be a Fuchsia device name to be resolved using
+                            device-finder or an IP address.
+                            An IPv4 address must be specified directly, while an IPv6
+                            need to be surrounded by brackets.
+                            SSH_PORT, if specified, will be used for all commands
+                            that rely on SSH to connect to the device instead of the
+                            default SSH port (22).
+                            Note: See "fx help set-device" for more help and to set
+                            the default device for a BUILD_DIR.
+  -i                        Iterative mode.  Repeat the command whenever a file is
+                            modified under your Fuchsia directory, not including
+                            out/.
+  -x                        Print commands and their arguments as they are executed.
+  -xx                       Print extra logging of the fx tool itself (implies -x)
 END
+  if [[ -n "$(list_optional_features)" ]]; then
+    echo "  --enable|disable=FEATURE  Enable or disable a feature (non-persistent). Valid features:"
+    help_optional_features
+  fi
 }
 
 function help_list_commands {
@@ -135,7 +137,7 @@ source "${features_sh}" || exit $?
 
 while [[ $# -ne 0 ]]; do
   case $1 in
-    --config=*|--dir=*|-d=*|--disable=*)
+    --config=*|--dir=*|-d=*|--disable=*|--enable=*)
       # Turn --switch=value into --switch value.
       arg="$1"
       shift
@@ -179,6 +181,21 @@ while [[ $# -ne 0 ]]; do
       fi
       env_name="$(get_disable_feature_env_name "${feature}")"
       export ${env_name}=1
+      ;;
+    --enable)
+      if [[ $# -lt 2 ]]; then
+        usage
+        fx-error "Missing argument to --enable"
+        exit 1
+      fi
+      shift # Removes --enable.
+      feature="$1"
+      if ! is_valid_feature "${feature}"; then
+        fx-error "Unknown feature \"${feature}\". Valid values are: $(list_optional_features)"
+        exit 1
+      fi
+      env_name="$(get_disable_feature_env_name "${feature}")"
+      export ${env_name}=0
       ;;
     -d)
       if [[ $# -lt 2 ]]; then
@@ -246,6 +263,15 @@ if [[ $? -ne 0 || ! -x "${command_path}" ]]; then
     "\`fx set\` config produces it in the $(_relative "$(get_host_tools_dir)") directory."
   exit 1
 fi
+
+# For each optional feature, force the existence of the FUCHSIA_DISABLE_* env
+# variable. This is needed so that non-bash code can reliably use this
+# to check for optional features that have default values.
+for f in $(list_optional_features); do
+  _disabled_env_name="$(get_disable_feature_env_name "${f}")"
+  is_feature_enabled "$f"
+  export ${_disabled_env_name}=$?
+done
 
 declare -r cmd_and_args="$@"
 shift # Removes the command name.
diff --git a/tools/devshell/tests/fx-internal/optional-features_test b/tools/devshell/tests/fx-internal/optional-features_test
--- a/tools/devshell/tests/fx-internal/optional-features_test
+++ b/tools/devshell/tests/fx-internal/optional-features_test
@@ -13,24 +13,24 @@ BT_FILE_DEPS=(
   "tools/devshell/lib/platform.sh"
 )
 
-declare fx valid_feature
+declare fx
 
 BT_SET_UP() {
   source "${BT_TEMP_DIR}/tools/devshell/tests/lib/fuchsia-mock.sh"
   fx="$(btf::setup_fx)"
-  source "${BT_TEMP_DIR}/tools/devshell/lib/fx-optional-features.sh"
-  # get the first valid feature defined in an array in fx-optional-features.sh
-  # if there are no optional features, this variable will
-  # be empty and the tests that depend on it should return SUCCESS.
-  local features=( $(list_optional_features) )
-  valid_feature="${features[0]}"
 }
 
 TEST_disable_feature() {
-  if [[ -z "${valid_feature}" ]]; then
-    # cannot test without a valid feature to be disabled
-    return 0
-  fi
+  local valid_feature="myfeature"
+  cat >> "${BT_TEMP_DIR}/tools/devshell/lib/fx-optional-features.sh" <<EOF
+    list_optional_features() {
+      echo "${valid_feature}"
+    }
+    is_feature_enabled_by_default() {
+      return 0  # enabled by default
+    }
+EOF
+
   local cmd="mycmd"
   local cmd_path="${BT_TEMP_DIR}/tools/devshell/${cmd}"
   mkdir -p "$(dirname "${cmd_path}")"
@@ -45,13 +45,50 @@ EOF
   # an optional feature. It should return 0 (true), since the feature
   # is not disabled explicitly, hence enabled.
   BT_EXPECT ${fx} ${cmd}
+  # Same, --enable has no effect
+  BT_EXPECT ${fx} --enable=${valid_feature} ${cmd}
 
-  # Now it should return false, since the feature is explicitly disabled
+  # Now it should return 1 (false), since the feature is explicitly disabled
   # in the fx invocation.
   BT_EXPECT_FAIL ${fx} --disable=${valid_feature} ${cmd}
 }
 
+TEST_enable_feature() {
+  local valid_feature="myfeature"
+  cat >> "${BT_TEMP_DIR}/tools/devshell/lib/fx-optional-features.sh" <<EOF
+    list_optional_features() {
+      echo "${valid_feature}"
+    }
+    is_feature_enabled_by_default() {
+      return 1  # disabled by default
+    }
+EOF
+
+  local cmd="mycmd"
+  local cmd_path="${BT_TEMP_DIR}/tools/devshell/${cmd}"
+  mkdir -p "$(dirname "${cmd_path}")"
+  # create a command that runs is_feature_enabled and returns its exit code
+  cat >"${cmd_path}" <<EOF
+#!/bin/bash
+source ${BT_TEMP_DIR}/tools/devshell/lib/fx-optional-features.sh || exit \$\?
+is_feature_enabled "${valid_feature}"
+EOF
+  chmod u+x "${cmd_path}"
+  # check that the command, when executed through fx, works as intended for
+  # an optional feature.
+  # It should return 1 (false), since the feature is not enabled explicitly, hence disabled.
+  BT_EXPECT_FAIL ${fx} ${cmd}
+  # Same, --disable has no effect
+  BT_EXPECT_FAIL ${fx} --disable=${valid_feature} ${cmd}
+
+  # Should return 0 (true), since the feature is explicitly enabled
+  # in the fx invocation.
+  BT_EXPECT ${fx} --enable=${valid_feature} ${cmd}
+
+}
+
 TEST_features_are_valid() {
+  source "${BT_TEMP_DIR}/tools/devshell/lib/fx-optional-features.sh"
   for f in $(list_optional_features); do
     # no spaces
     if [[ $f =~ " " ]]; then
