Revert "[fx] Refactor fx help"
This reverts commit 2a37133b6ff4d9ba117e3c5ffb4e812862a9ff93.

Reason for revert: Some users reported that the find command introduced here was not finding commands for them, resulting in: ERROR: Unknown command set.

Original change's description:
> [fx] Refactor fx help
> 
> Several improvements to `fx help`:
> 
> Major changes:
> - substantial (~20x) performance improvement, from 2.5s to 130ms in my computer
> - support a metadata file (*.fx) for each script or binary, with the same
>    syntax as the current script headers ("^###*" lines)
> - add "#### CATEGORY=", "#### DEPRECATED" and "#### EXECUTABLE=" as
>    optional headers for scripts and metadata files
> - Group commands in categories, according to their CATEGORY headers
> - support vendor subcommands: "vendor <vendor> <command>" for all commands in vendor/*/scripts/devshell/*
> 
> Minor changes:
> - mark "contrib" and "DEPRECATED" commands in the output
> - hide deprecated commands by default, add "fx help --deprecated" to show them
> - add "fx help --no-contrib" to hide contrib commands
> 
> Test: manually ran and checked on linux and macos:
> fx help
> fx help --deprecated
> fx help --no-contrib
> fx help --no-contrib --deprecated
> fx help set
> fx set -h
> fx help vendor myvendor command1
> fx help vendor
> fx help gn  # uses gn.fx
> fx help fidldoc  # uses fidldoc.fx
> fx fidldoc  # fails gracefully if fidldoc is not in build_dir, works otherwise
> 
> Here's an example output (content cropped for clarity):
> 
> ```
> $ time fx help
> [...]
> 
> Source tree:
>   cipd                        run the cipd command line tool
>   gen-cargo                   (contrib) generate symlinks to Rust Cargo.toml output files
>   jiri                        multi-purpose tool for multi-repo development.
> [...]
>   vendor myvendor command1    do something
>   vendor myvendor command2    do something else
> 
> Documentation:
>   fidldoc                      (contrib) generate documentation for FIDL
>   rustdoc                      (contrib) generate documentation for Rust code
>   vendor othervendor cmd3      do something entirely different
> 
> Build:
> [...]
> 
> Device discovery:
> [...]
> 
> Device management:
> [...]
> 
> Software delivery:
> [...]
> 
> Run, inspect and debug:
> [...]
> 
> Other:
> [...]
> 
> Commands marked with "(contrib)" may have other levels of support and/or ownership. See //tools/devshell/README.md for more information. Use `fx help --no-contrib` to hide contrib commands.
> 
> Deprecated commands are hidden. Use `fx help --deprecated` to include deprecated commands.
> 
> real 0m0.138s
> user 0m0.103s
> sys 0m0.064s
> 
> ```
> 
> Bug: 34783
> Change-Id: I7e74ccb95a6dccbb194e4fcc6bebf4b5ef0f9be2

TBR=abarth@google.com,raggi@google.com,mangini@google.com,craiglabenz@google.com

Change-Id: I9d97a442a721c3bf614735cd434dc83d27575aca
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 34783

diff --git a/scripts/fx b/scripts/fx
--- a/scripts/fx
+++ b/scripts/fx
@@ -3,95 +3,82 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-function get_host_tools_dir {
-  local -r build_dir="$(fx-build-dir-if-present && echo "${FUCHSIA_BUILD_DIR}")"
-  local -r host_tools="${build_dir}/host-tools"
-  if [[ -d "${build_dir}" && -d "${host_tools}"  ]]; then
-    echo "${host_tools}"
-  fi
+function get_build_dir {
+  (fx-build-dir-if-present && echo "${FUCHSIA_BUILD_DIR}")
 }
 
-function replace_variable {
-  readonly content=$1
-  readonly var=$2
-  readonly value=$3
-  echo ${content//\$\{${var}\}/${value}}
-}
-
-function get_exec_from_metadata {
-  local -r metadata_file=$1
-
-  export PREBUILT_3P_DIR FUCHSIA_DIR HOST_PLATFORM
-  export HOST_TOOLS_DIR="$(get_host_tools_dir)"
-
-  awk -F ' *= *' -f - "${metadata_file}" <<'EOF'
-    /^#### +EXECUTABLE */ {
-      gsub(/\${PREBUILT_3P_DIR}/, ENVIRON["PREBUILT_3P_DIR"], $2);
-      gsub(/\${FUCHSIA_DIR}/, ENVIRON["FUCHSIA_DIR"], $2);
-      gsub(/\${HOST_TOOLS_DIR}/, ENVIRON["HOST_TOOLS_DIR"], $2);
-      gsub(/\${HOST_PLATFORM}/, ENVIRON["HOST_PLATFORM"], $2);
-      print $2;
-    }
-EOF
-}
-
-function find_executable {
-  local cmd_name="$1"
-  local cmd_path="$(commands "${cmd_name}")"
-  cmd_path="${cmd_path%.fx}"
-  local fx_file_path="${cmd_path}.fx"
-  if [[ ! -f "${fx_file_path}" ]]; then
-    if [[ -x "${cmd_path}" ]]; then
-      echo "${cmd_path}"
-      return 0
-    else
-      return 1
-    fi
-  fi
-  local from_metadata="$(get_exec_from_metadata "${fx_file_path}")"
-
-  if [[ -z "${from_metadata}" ]]; then
-    # no EXECUTABLE in the metadata, so return the cmd_path itself
-    if [[ -x "${cmd_path}" ]]; then
-      echo "${cmd_path}"
-      return 0
-    else
-      return 1
-    fi
-  else # EXECUTABLE is defined in the metadata
-    if [[ -f "${cmd_path}"  && ! "${cmd_path}" -ef "${from_metadata}" ]]; then
-      fx-error "Invalid ${fx_file_path}: if both ${basename_exec} and EXECUTABLE metadata exist, they must point to the same file"
-      return 1
-    fi
-    echo "${from_metadata}"
-    return 0
-  fi
-}
+readonly EPONYMOUS_PREBUILT_3P_COMMANDS=(gn ninja)
+readonly JIRI_BIN_COMMANDS=(cipd jiri)
 
 function commands {
-  local dirs
-  local cmd_name=$1
-  # handle "fx help vendor VENDOR COMMAND"
-  if [[ "${cmd_name}" == "vendor" && $# -eq 3 ]]; then
-    vendor=$2
-    cmd_name=$3
-    dirs=("${fuchsia_dir}"/vendor/${vendor}/scripts/devshell)
-  else
-    dirs=("${fuchsia_dir}"/tools/devshell{,/contrib} "${fuchsia_dir}"/vendor/*/scripts/devshell)
-  fi
-  local -r host_tools="$(get_host_tools_dir)"
+  local dirs=()
+  dirs+=("${fuchsia_dir}"/tools/devshell{,/contrib})
+  local -r build_dir="$(get_build_dir)"
   if [[ -n "${build_dir}" ]]; then
-    dirs+=("${host_tools}")
+    dirs+=("${build_dir}/host-tools")
   fi
 
-  if [[ -z "${cmd_name}" ]]; then
-    cmd_name="*"
-  fi
-  find "${dirs[@]}" -maxdepth 1 -type f \
-    \( -perm -111 -name "${cmd_name}" \) -o \
-    \( -name "${cmd_name}.fx" \) 2>/dev/null | sort -u
+  (
+    for dir in "${dirs[@]}"; do
+      for cmd in "${dir}"/*; do
+        if [[ -x "${cmd}" && -f "${cmd}" ]]; then
+          basename "${cmd}"
+        fi
+      done
+    done
+    echo "${EPONYMOUS_PREBUILT_3P_COMMANDS[@]}" "${JIRI_BIN_COMMANDS[@]}"
+  ) | sort -u
 }
 
+function find_command {
+  local -r cmd=$1
+
+  local command_path="${fuchsia_dir}/tools/devshell/${cmd}"
+  if [[ -x "${command_path}" ]]; then
+    echo "${command_path}"
+    return 0
+  fi
+
+  local command_path="${fuchsia_dir}/tools/devshell/contrib/${cmd}"
+  if [[ -x "${command_path}" ]]; then
+    echo "${command_path}"
+    return 0
+  fi
+
+  local -r build_dir=$(get_build_dir)
+  if [[ -n "${build_dir}" ]]; then
+    local command_path="${build_dir}/host-tools/${cmd}"
+    if [[ -x "${command_path}" ]]; then
+      echo "${command_path}"
+      return 0
+    fi
+  fi
+
+  local tool
+  for tool in "${EPONYMOUS_PREBUILT_3P_COMMANDS[@]}"; do
+    if [[ "$cmd" != "$tool" ]]; then
+      continue
+    fi
+    local command_path="${PREBUILT_3P_DIR}/${tool}/${HOST_PLATFORM}/${tool}"
+    if [[ -x "${command_path}" ]]; then
+      echo "${command_path}"
+      return 0
+    fi
+  done
+
+  for tool in "${JIRI_BIN_COMMANDS[@]}"; do
+    if [[ "$cmd" != "$tool" ]]; then
+      continue
+    fi
+    local command_path="${FUCHSIA_DIR}/.jiri_root/bin/${tool}"
+    if [[ -x "${command_path}" ]]; then
+      echo "${command_path}"
+      return 0
+    fi
+  done
+
+  return 1
+}
 
 function help_global_options {
   cat <<END
@@ -108,45 +95,28 @@ Global fx options: fx [OPTION] ${cmd} ...
 END
 }
 
-function help_list_commands {
-  local hide_contrib=0
-  local show_deprecated=0
-  while [[ $# -ne 0 ]]; do
-    if [[ "$1" == "--deprecated" ]]; then
-      show_deprecated=1
-    elif [[ "$1" == "--no-contrib" ]]; then
-      hide_contrib=1
-    fi
-    shift
-  done
-  commands | xargs awk \
-    -v hide_contrib=${hide_contrib} \
-    -v show_deprecated=${show_deprecated} \
-    -f "${fuchsia_dir}/scripts/fx-help.awk"
-  help_global_options
-  if [[ "${hide_contrib}" -eq 0 ]]; then
-    echo
-    echo "Commands marked with \"(contrib)\" may have other levels of support" \
-         "and/or ownership. See //tools/devshell/README.md for more" \
-         "information. Use \`fx help --no-contrib\` to hide contrib commands."
-  fi
-  if [[ "${show_deprecated}" -eq 0 ]]; then
-    echo
-    echo "Deprecated commands are hidden. Use \`fx help --deprecated\` to" \
-         "include deprecated commands."
-  fi
-}
-
-function help_command {
-  local cmd="$@"
-  local cmd_path="$(commands ${cmd} | head -1)"
-  if [[ -z "${cmd_path}" ]]; then
-    echo "Command ${cmd} not found. Try \`fx help\`"
-  elif [[ $(file -b --mime "${cmd_path}" | cut -d / -f 1) == "text" ]]; then
-    fx-print-command-help "${cmd_path}"
+function help {
+  local cmd="$1"
+  if [[ -z "${cmd}" ]]; then
+    for cmd in $(commands); do
+      local cmd_path="$(find_command "${cmd}")"
+      if [[ $(file -b --mime "${cmd_path}" | cut -d / -f 1) == "text" ]]; then
+        echo "${cmd} | $(sed -n '1,/^###/s/^### //p' < "${cmd_path}")"
+      else
+        echo "${cmd}"
+      fi
+    done | column -t -s '|' -c 2
     help_global_options
   else
-    echo "No help found. Try \`fx ${cmd} -h\`"
+    local cmd_path="$(find_command "${cmd}")"
+    if [[ -z "$cmd_path" ]]; then
+      echo "Command not found. Try \`fx help\`"
+    elif [[ $(file -b --mime "${cmd_path}" | cut -d / -f 1) == "text" ]]; then
+      fx-print-command-help "${cmd_path}"
+      help_global_options
+    else
+      echo "No help found. Try \`fx ${cmd} -h\`"
+    fi
   fi
 }
 
@@ -154,17 +124,23 @@ function usage {
   cat <<END
 usage: fx [--dir BUILD_DIR] [-d DEVICE_NAME] [-i] [-x] COMMAND [...]
 
-Run Fuchsia development commands. Must be run either from a directory
-that is contained in a Platform Source Tree or with the FUCHSIA_DIR
+Run Fuchsia development commands. Must be run with either a current working
+directory that is contained in a Platform Source Tree or the FUCHSIA_DIR
 environment variable set to the root of a Platform Source Tree.
 
-host shell extensions: (requires "source scripts/fx-env.sh")
-  fx-update-path        add useful tools to the PATH
-  fx-set-prompt         display the current configuration in the shell prompt
+commands:
+$(help)
+
+optional shell extensions:
+  fx-go
+  fx-update-path
+  fx-set-prompt
+
+To use these shell extensions, first source fx-env.sh into your shell:
+
+  $ source scripts/fx-env.sh
 
 END
-
-  help_list_commands "$@"
 }
 
 fuchsia_dir="${FUCHSIA_DIR}"
@@ -240,15 +216,15 @@ while [[ $# -ne 0 ]]; do
       shift
       break
       ;;
-    help|--help)
-      if [[ $# -lt 2 || "$2" =~ ^\-\-.* ]]; then
+    help)
+      if [[ $# -gt 1 ]]; then
         shift
-        usage "$@"
+        help "$@"
+        exit
       else
-        shift
-        help_command "$@"
+        usage
+        exit 1
       fi
-      exit 0
       ;;
     -*)
       usage
@@ -269,17 +245,11 @@ if [[ $# -lt 1 ]]; then
 fi
 
 command_name="$1"
-command_path="$(find_executable ${command_name})"
+command_path="$(find_command ${command_name})"
 
 if [[ $? -ne 0 ]]; then
+  usage
   fx-error "Unknown command ${command_name}"
-  exit 1
-fi
-
-if [[ ! -x "${command_path}" ]]; then
-  fx-error "Cannot find executable for ${command_name}: ${command_path}. If" \
-  "this is a tool produced by the build, make sure your \`fx set\` contains" \
-  "it and that \`fx build\` runs successfuly."
   exit 1
 fi
 
