[fx] warn user to execute fx from current source tree.
Test: created a 2nd fuchsia checkout and tested the workflow.

Bug: 80707
Change-Id: I7cb3f77ed0213449fc6f58ec3eece189f244ba2a
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/558183
Commit-Queue: Mahesh Saripalli <maheshsr@google.com>
Reviewed-by: Gary Boone <gboone@google.com>
Reviewed-by: James Tucker <raggi@google.com>
Reviewed-by: Renato Mangini Dias <mangini@google.com>

diff --git a/scripts/fx b/scripts/fx
--- a/scripts/fx
+++ b/scripts/fx
@@ -173,6 +173,20 @@ function fullhelp {
   help_list_commands "$@"
 }
 
+function find_tree_root {
+  local parent="$1"
+  if [[ ! -d "$parent" ]]; then
+    return 1
+  fi
+  while [[ ! -d "${parent}/.jiri_root" ]]; do
+    parent="$(dirname "${parent}")"
+    if [[ "$parent" == "/" ]]; then
+      return 1
+    fi
+  done
+  echo "$parent"
+}
+
 # We walk the parent directories looking for .jiri_root rather than using
 # BASH_SOURCE so that we find the fuchsia_dir enclosing the current working
 # directory instead of the one containing this file in case the user has
@@ -184,14 +198,25 @@ function fullhelp {
 # This logic is replicated in //scripts/fx, //scripts/hermetic_env,
 # //scripts/zsh_completion/_fx, and //src/developer/ffx/scripts. For
 # consistency, copy any changes here to those files as well.
-fuchsia_dir="$(pwd)"
-while [[ ! -d "${fuchsia_dir}/.jiri_root" ]]; do
-  fuchsia_dir="$(dirname "${fuchsia_dir}")"
-  if [[ "${fuchsia_dir}" == "/" ]]; then
-    echo "Cannot find the Platform Source Tree in a parent of directory: $(pwd)"
-    exit 1
-  fi
-done
+if ! fuchsia_dir="$(find_tree_root "$(pwd)")"; then
+  echo >&2 "ERROR: Cannot find the Platform Source Tree in a parent of the current directory: $(pwd)"
+  exit 1
+fi
+
+_this_script="$0"
+if [[ "$_this_script" != "${fuchsia_dir}/.jiri_root/bin/fx" &&
+    "$_this_script" != "${fuchsia_dir}/scripts/fx" ]]; then
+   _this_fuchsia_dir="$(find_tree_root "$(dirname "$_this_script")")"
+   if [[ $? -ne 0 || "$_this_fuchsia_dir" != "$fuchsia_dir" ]]; then
+     if ! cmp -s "$_this_script" "${fuchsia_dir}/.jiri_root/bin/fx"; then
+       echo >&2 "WARNING: You are executing fx from outside of the current"
+       echo >&2 "source tree, and it is a different version."
+       echo >&2 "This can cause inconsistencies. Please update your PATH."
+       echo >&2 "    'fx' was executed from: ${_this_script}"
+       exit 1
+     fi
+   fi
+fi
 
 declare -r vars_sh="${fuchsia_dir}/tools/devshell/lib/vars.sh"
 source "${vars_sh}" || exit $?
diff --git a/tools/devshell/tests/fx-internal/fx_test b/tools/devshell/tests/fx-internal/fx_test
--- a/tools/devshell/tests/fx-internal/fx_test
+++ b/tools/devshell/tests/fx-internal/fx_test
@@ -139,4 +139,37 @@ TEST_fx-hosttools-subcommand-run() {
   BT_EXPECT_STRING_CONTAINS_SUBSTRING "$(${fx} "${subcommand}")" "${output}"
 }
 
+# executes a simple fx command from different fuchsia checkout,
+# while the two fuchsia checkouts have the same version of fx.
+TEST_fx-run_from_same_version() {
+  # creates a temp fuchsia checkout directory.
+  BT_TEMP_DIR_1="$(mktemp -d)"
+  cp -RL "${BT_TEMP_DIR}/." "${BT_TEMP_DIR_1}"
+  cd "${BT_TEMP_DIR_1}"
+  # check whether fx command executed successfully, since the two fuchsia checkouts
+  # have the same versions of fx code.
+  output="$(${fx} help 2>&1)"
+  BT_EXPECT_EQ $? 0
+  BT_EXPECT_STRING_CONTAINS_SUBSTRING "${output}" "usage: fx"
+}
+
+# executes fx command from different fuchsia checkout to detect the
+# inconsistencies in fx versions.
+TEST_fx-run_from_different_version() {
+  local output
+  local line1="WARNING: You are executing fx from outside of the current"
+  local line2="'fx' was executed from:"
+  # creates a temp fuchsia checkout directory and run fx command.
+  BT_TEMP_DIR_1="$(mktemp -d)"
+  cp -RL "${BT_TEMP_DIR}/." "${BT_TEMP_DIR_1}"
+  cd "${BT_TEMP_DIR_1}"
+  # Modify the fx script of the new fuchsia source code tree, so the content
+  # comparsion of fx script fails between the two versions of source code.
+  echo "# test" >>  "${BT_TEMP_DIR}/scripts/fx"
+
+  output="$(${fx} help 2>&1)"
+  BT_EXPECT_STRING_CONTAINS_SUBSTRING "${output}" "${line1}"
+  BT_EXPECT_STRING_CONTAINS_SUBSTRING "${output}" "${line2} ${BT_TEMP_DIR}"
+}
+
 BT_RUN_TESTS "$@"
