[fx][incremental] Add --disable flag on fx
Optional features to support the incoming fx changes related to
incremental building.

Change-Id: I278af5665f75fa209cb41414b171c3b9dc6f495f
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/396271
Commit-Queue: Renato Mangini Dias <mangini@google.com>
Reviewed-by: Wesley Moy <wesleymoy@google.com>
Testability-Review: Renato Mangini Dias <mangini@google.com>

diff --git a/scripts/fx b/scripts/fx
--- a/scripts/fx
+++ b/scripts/fx
@@ -17,6 +17,8 @@ function help_global_options {
 
 Global fx options: fx [OPTION] ${cmd} ...
   --dir=BUILD_DIR       Path to the build directory to use when running COMMAND.
+  --disable=FEATURE     Disable a feature (non-persistent).
+                        Valid values for FEATURE: [${_FX_OPTIONAL_FEATURES[@]}]
   -d=DEVICE[:SSH_PORT]  Target a specific device.
                         DEVICE may be a Fuchsia device name to be resolved using
                         device-finder or an IP address.
@@ -128,9 +130,12 @@ source "${metrics_sh}" || exit $?
 declare -r cmd_locator_sh="${fuchsia_dir}/tools/devshell/lib/fx-cmd-locator.sh"
 source "${cmd_locator_sh}" || exit $?
 
+declare -r features_sh="${fuchsia_dir}/tools/devshell/lib/fx-optional-features.sh"
+source "${features_sh}" || exit $?
+
 while [[ $# -ne 0 ]]; do
   case $1 in
-    --config=*|--dir=*|-d=*)
+    --config=*|--dir=*|-d=*|--disable=*)
       # Turn --switch=value into --switch value.
       arg="$1"
       shift
@@ -159,6 +164,21 @@ while [[ $# -ne 0 ]]; do
       if [[ "$_FX_BUILD_DIR" == //* ]]; then
         _FX_BUILD_DIR="${fuchsia_dir}/${_FX_BUILD_DIR#//}"
       fi
+      ;;
+    --disable)
+      if [[ $# -lt 2 ]]; then
+        usage
+        fx-error "Missing argument to --disable"
+        exit 1
+      fi
+      shift # Removes --disable.
+      feature="$1"
+      if ! is_valid_feature "${feature}"; then
+        fx-error "Unknown feature \"${feature}\". Valid values are: ${_FX_OPTIONAL_FEATURES[@]}"
+        exit 1
+      fi
+      env_name="$(get_disable_feature_env_name "${feature}")"
+      export ${env_name}=1
       ;;
     -d)
       if [[ $# -lt 2 ]]; then
