[fx] support IPv4, IPv6 resolved addresses and SSH port number
- Support IPv4 and IPv6 resolved device addresses in `fx -d` and in
`fx set-device`
- Support `fx -d device:port` and `fx set-device device:port` to override the
default port 22 on ssh-based commands.

Tests included for all the changes and executed on both linux and mac (catalina):

```
$ fx self-test fx-internal/vars_test subcommands/fx_ssh_test fx-internal/devfinder_usage_test
Running test script fx-internal/vars_test
[1] TEST_environment()  [PASSED]
[2] TEST_fx-warn()  [PASSED]
[3] TEST_fx-error()  [PASSED]
[4] TEST_fx-build-dir-write()  [PASSED]
[5] TEST_fx-build-dir-if-present()  [PASSED]
[6] TEST_fx-build-config-load()  [PASSED]
[7] TEST_fx-getdeviceraw-and-isvaliddevice()  [PASSED]
[8] TEST_fx-get-device-ssh-port()  [PASSED]
All 8 tests passed.
Running test script subcommands/fx_ssh_test
[1] TEST_ssh_ipv4_port()  [PASSED]
[2] TEST_ssh_ipv6_port()  [PASSED]
[3] TEST_ssh_invalid_hostname_port()  [PASSED]
[4] TEST_ssh_invalid_ipv6_port()  [PASSED]
[5] TEST_ssh_addr()  [PASSED]
[6] TEST_ssh_resolve_addr_port()  [PASSED]
[7] TEST_ssh_only_port()  [PASSED]
[8] TEST_ssh_only_port_and_setdevice()  [PASSED]
All 8 tests passed.
Running test script fx-internal/devfinder_usage_test
[1] TEST_setdevice()  [PASSED]
[2] TEST_getdeviceaddr_resolved_ipv4_addresses()  [PASSED]
[3] TEST_getdeviceaddr_resolved_ipv6_addresses_setdevice()  [PASSED]
[4] TEST_getdeviceaddr_resolved_ipv6_addresses()  [PASSED]
[5] TEST_getdeviceaddr_name_looks_like_ipv4()  [PASSED]
[6] TEST_getdeviceaddr_singledevice()  [PASSED]
[7] TEST_getdeviceaddr_multipledevice()  [PASSED]
All 7 tests passed.
```

Change-Id: Ic6b04d9a818c14cd53bfb26c0f9df553f4897c13

diff --git a/scripts/fx b/scripts/fx
--- a/scripts/fx
+++ b/scripts/fx
@@ -171,9 +171,16 @@ function help_global_options {
 
 Global fx options: fx [OPTION] ${cmd} ...
   --dir=BUILD_DIR       Path to the build directory to use when running COMMAND.
-  -d=DEVICE_NAME        Target a specific device. DEVICE_NAME may be a Fuchsia
-                        device name. Note: "fx set-device" can be used to set a
-                        default DEVICE_NAME for a BUILD_DIR.
+  -d=DEVICE[:SSH_PORT]  Target a specific device.
+                        DEVICE may be a Fuchsia device name to be resolved using
+                        device-finder or an IP address.
+                        An IPv4 address must be specified directly, while an IPv6
+                        need to be surrounded by brackets.
+                        SSH_PORT, if specified, will be used for all commands
+                        that rely on SSH to connect to the device instead of the
+                        default SSH port (22).
+                        Note: See "fx help set-device" for more help and to set
+                        the default device for a BUILD_DIR.
   -i                    Iterative mode.  Repeat the command whenever a file is
                         modified under your Fuchsia directory, not including
                         out/.
@@ -311,6 +318,10 @@ while [[ $# -ne 0 ]]; do
         exit 1
       fi
       shift # removes -d
+      if ! is-valid-device "$1"; then
+        fx-error "Invalid device: $1. See valid values in 'fx help set-device'"
+        exit 1
+      fi
       export FUCHSIA_DEVICE_NAME="$1"
       ;;
     -i)
diff --git a/tools/devshell/set-device b/tools/devshell/set-device
--- a/tools/devshell/set-device
+++ b/tools/devshell/set-device
@@ -6,17 +6,33 @@
 #### CATEGORY=Device discovery
 ### set the default device to interact with
 
-## usage: fx set-device [<device-name>]
+## usage: fx set-device DEVICE[:SSH_PORT]
 ##
-## fx set-device is used to specify the default device to target for various
-## fx commands, such as serve, syslog, and so on.
+## fx set-device is used to specify the default device to target for
+## fx commands that communicate with a Fuchsia device.
 ## A device is set within the scope of a build directory (i.e. out/arm64 may
-## have a different pair set than out/x64).
+## have a different default device than out/x64).
 ##
 ## If no device name is given, set-device will attempt to discover devices. If
 ## one device is found, that device is set as the default for the current build
 ## directory. If more than one device is found, the user must select one and
 ## provide it to a subsequent invocation of the command.
+##
+## If specified, DEVICE may be a Fuchsia device name that will be resolved
+## using device-finder or an IP address. An IPv4 address must be specified
+## directly, while IPv6 need to be surrounded by brackets.
+##
+## SSH_PORT, if specified, will be used for all commands that rely on SSH to
+## connect to the device, instead of the default SSH port (22).
+##
+## Examples:
+##   fx set-device strut-wind-ahead-turf
+##   fx set-device strut-wind-ahead-turf:222
+##   fx set-device 192.168.1.2
+##   fx set-device 192.168.3.1:8022
+##   fx set-device [fe80::7:8%eth0]
+##   fx set-device [fe80::7:8%eth0]:5222
+##   fx set-device
 ##
 ## To unset, use `fx unset-device`.
 
@@ -38,19 +54,23 @@ device="$1"
 if [[ -z "$device" ]]; then
   devices="$("${FUCHSIA_BUILD_DIR}/host-tools/device-finder" list -mdns -netboot -ipv4=false -full | cut -d ' ' -f 2)"
   if [[ -z "${devices}" ]]; then
-    echo 2>&1 "No devices discovered, please supply a device name"
+    fx-error "No devices discovered, please supply a device name"
     exit 1
   fi
   if [[ "$(echo "$devices" | wc -l)" -ge 2 ]]; then
-    echo 2>&1 "Multiple devices found, please pick one from the list:"
+    fx-error "Multiple devices found, please pick one from the list:"
     device=$(select_device "$devices")
   else
     device="${devices}"
   fi
+elif ! is-valid-device "${device}"; then
+  fx-error "Invalid device: ${device}"
+  fx-command-help
+  exit 1
 fi
 
 if [[ ! -d "${FUCHSIA_BUILD_DIR}" ]]; then
-  echo 2>&1 "Build directory ${FUCHSIA_BUILD_DIR} does not exist, run \"fx set\" first."
+  fx-error "Build directory ${FUCHSIA_BUILD_DIR} does not exist, run \"fx set\" first."
   exit 1
 fi
 
