[fx] Correct the docs and usage of FUCSHIA_DIR
Correct the documentation for FUCSHIA_DIR to note that the
environmental variable is not used.

Clarify the output message when the Fuchsia root is not found
above the current directory.

Update other copies of the root directory search code for
consistency with the recent deprecation of the FUCSHIA_DIR
environmental variable.

Change-Id: Id7ce316b70e7162ed1d75f17e5b9023e773c96a0
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/513296
Reviewed-by: Renato Mangini Dias <mangini@google.com>
Reviewed-by: James Tucker <raggi@google.com>
Commit-Queue: Gary Boone <gboone@google.com>

diff --git a/scripts/hermetic-env b/scripts/hermetic-env
--- a/scripts/hermetic-env
+++ b/scripts/hermetic-env
@@ -27,21 +27,27 @@ if [[ -n "${FUCHSIA_DIR}" ]]; then
 fi
 
 # Mimic `fx` behavior to set up a consistent root and get prebuilt paths.
-fuchsia_dir="${FUCHSIA_DIR}"
-if [[ -z "${fuchsia_dir}" ]]; then
-  # We walk the parent directories looking for .jiri_root rather than using
-  # BASH_SOURCE so that we find the fuchsia_dir enclosing the current working
-  # directory instead of the one containing this file in case the user has
-  # multiple source trees and is picking up this file from another one.
-  fuchsia_dir="$(pwd)"
-  while [[ ! -d "${fuchsia_dir}/.jiri_root" ]]; do
-    fuchsia_dir="$(dirname "${fuchsia_dir}")"
-    if [[ "${fuchsia_dir}" == "/" ]]; then
-      echo "Cannot find Platform Source Tree containing $(pwd)"
-      exit 1
-    fi
-  done
-fi
+#
+# We walk the parent directories looking for .jiri_root rather than using
+# BASH_SOURCE so that we find the fuchsia_dir enclosing the current working
+# directory instead of the one containing this file in case the user has
+# multiple source trees and is picking up this file from another one.
+#
+# NOTE: The FUCHSIA_DIR environment variable is ignored here because it
+# could point to a different Fuchsia checkout in some developer setups.
+#
+# This logic is replicated in //scripts/fx, //scripts/hermetic_env,
+# //scripts/zsh_completion/_fx, and //src/developer/ffx/scripts. For
+# consistency, copy any changes here to those files as well.
+fuchsia_dir="$(pwd)"
+while [[ ! -d "${fuchsia_dir}/.jiri_root" ]]; do
+  fuchsia_dir="$(dirname "${fuchsia_dir}")"
+  if [[ "${fuchsia_dir}" == "/" ]]; then
+    echo "Cannot find the Platform Source Tree in a parent of directory: $(pwd)"
+    exit 1
+  fi
+done
+
 
 export FUCHSIA_DIR="${fuchsia_dir}"
 declare -r prebuilt_sh="${fuchsia_dir}/tools/devshell/lib/prebuilt.sh"
diff --git a/scripts/zsh-completion/_fx b/scripts/zsh-completion/_fx
--- a/scripts/zsh-completion/_fx
+++ b/scripts/zsh-completion/_fx
@@ -32,17 +32,26 @@ __fx_gn_target() {
 _fx() {
   typeset -A opt_args
 
-  local fuchsia_dir="${FUCHSIA_DIR}"
-  if [[ -z "${fuchsia_dir}" ]]; then
-    fuchsia_dir="$(pwd)"
-    while [[ ! -d "${fuchsia_dir}/.jiri_root" ]]; do
-      fuchsia_dir="$(dirname "${fuchsia_dir}")"
-      if [[ "${fuchsia_dir}" == "/" ]]; then
-        _message -r "Cannot find Platform Source Tree containing $(pwd)"
-        return
-      fi
-    done
-  fi
+  # We walk the parent directories looking for .jiri_root rather than using
+  # BASH_SOURCE so that we find the fuchsia_dir enclosing the current working
+  # directory instead of the one containing this file in case the user has
+  # multiple source trees and is picking up this file from another one.
+  #
+  # NOTE: The FUCHSIA_DIR environment variable is ignored here because it
+  # could point to a different Fuchsia checkout in some developer setups.
+  #
+  # This logic is replicated in //scripts/fx, //scripts/hermetic_env,
+  # //scripts/zsh_completion/_fx, and //src/developer/ffx/scripts. For
+  # consistency, copy any changes here to those files as well.
+  local fuchsia_dir="$(pwd)"
+  while [[ ! -d "${fuchsia_dir}/.jiri_root" ]]; do
+    fuchsia_dir="$(dirname "${fuchsia_dir}")"
+    if [[ "${fuchsia_dir}" == "/" ]]; then
+      echo "Cannot find the Platform Source Tree in a parent of directory: $(pwd)"
+      exit 1
+    fi
+  done
+
 
   # list of commands based on //tools/devshell/
   # each file is read to find the description line (starts with "### ").
