[fx] improve fx behavior when run out-of-tree
The location check is simplified to ensure $PWD is a subdirectory of the
Fuchsia source tree.
The condition on failure of the check is an error explicitly.
The error output now provides actionable solutions.

Fixed: 86775
Change-Id: I3322d10d324726e84bfab841ba949e9919226f52
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/595383
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Fuchsia-Auto-Submit: James Tucker <raggi@google.com>
Reviewed-by: Gary Boone <gboone@google.com>

diff --git a/scripts/hermetic-env b/scripts/hermetic-env
--- a/scripts/hermetic-env
+++ b/scripts/hermetic-env
@@ -58,18 +58,20 @@ if ! fuchsia_dir="$(find_tree_root "$(pwd)")"; then
   exit 1
 fi
 
-_this_script="$0"
-if [[ "$_this_script" != "${fuchsia_dir}/.jiri_root/bin/hermetic-env" &&
-    "$_this_script" != "${fuchsia_dir}/scripts/hermetic-env" ]]; then
-   _this_fuchsia_dir="$(find_tree_root "$(dirname "$_this_script")")"
-   if [[ $? -ne 0 || "$_this_fuchsia_dir" != "$fuchsia_dir" ]]; then
-     if ! cmp -s "$_this_script" "${fuchsia_dir}/.jiri_root/bin/hermetic-env"; then
-       echo >&2 "WARNING: You are executing hermetic-env from outside of the"
-       echo >&2 "current source tree, and it is a different version."
-       echo >&2 "This can cause inconsistencies. Please update your PATH."
-       echo >&2 "    'hermetic-env' was executed from: ${_this_script}"
-     fi
-   fi
+script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+
+if [[ "${script_dir}" != "${fuchsia_dir}"* ]]; then
+  echo >&2 "ERROR: You are executing fx from outside of the current source tree"
+  echo >&2 "ERROR: This is not supported as fx does not have a stable internal API"
+  echo >&2
+  echo >&2 "    'hermetic-env' was executed from: ${BASH_SOURCE[0]}"
+  echo >&2 "    'fuchsia directory' resolved to: ${fuchsia_dir}"
+  echo >&2
+  echo >&2 "To run a command in the current Fuchsia directory, run fx from:"
+  echo >&2 "  ${fuchsia_dir}/scripts/hermetic-env"
+  echo >&2 "Or, if you use fx-env.sh, source fx-env from the current fuchsia dir:"
+  echo >&2 "  source ${fuchsia_dir}/scripts/fx-env.sh"
+  exit 1
 fi
 
 export FUCHSIA_DIR="${fuchsia_dir}"
