[scripts] Make make-magenta-x86-64-grub error early if missing tools
Change-Id: I983bd3d416e7e1a6e4ac652932b1bd3e070c2c78

diff --git a/scripts/make-magenta-x86-64-grub b/scripts/make-magenta-x86-64-grub
--- a/scripts/make-magenta-x86-64-grub
+++ b/scripts/make-magenta-x86-64-grub
@@ -15,6 +15,11 @@ PROJECT_DIR="$DIR/../build-$PROJECT"
 
 (cd "$DIR/.."; $DIR/make-parallel $PROJECT) || exit
 
+if ! which xorriso grub-mkrescue &> /dev/null; then
+  echo "ERROR: You must install xorriso and grub-mkrescue"
+  exit
+fi
+
 TEMP="$(mktemp -d)"
 mkdir -p "$TEMP/boot/grub"
 cp "$PROJECT_DIR/magenta.bin" "$TEMP/boot/magenta.bin"
