[prebuilt] Look for cipd in //buildtools
Mirroring the code in //zircon/scripts/download-prebuilt

Change-Id: I1a242c3751014c875832602c53f70db64bdb6602

diff --git a/scripts/update-prebuilt-versions b/scripts/update-prebuilt-versions
--- a/scripts/update-prebuilt-versions
+++ b/scripts/update-prebuilt-versions
@@ -25,16 +25,24 @@ case "$#:$1" in
   ;;
 esac
 
-readonly CIPD="$(type -p cipd)" || {
+
+find_cipd() {
+  # If cipd is in the PATH, just take it.  Otherwise, if the Zircon
+  # checkout is part of a jiri checkout that includes //buildtools,
+  # then find cipd there.
+  type -p cipd || type -p "${ZIRCON_ROOT}/../buildtools/cipd"
+}
+
+readonly CIPD="$(find_cipd)" || {
   echo >&2 "$0: Need cipd in the PATH"
 }
 
 resolve_one_package() {
   local -r package="$1" version="$2"
   local result
-  result="$(cipd resolve "fuchsia/$package" -version "$version")" || {
+  result="$($CIPD resolve "fuchsia/$package" -version "$version")" || {
     local rc=$?
-    echo >&2 "$0: CIPD cannot resolve fuchsia/$package -version $version"
+    echo >&2 "$0: cipd cannot resolve fuchsia/$package -version $version"
     return $rc
   }
   echo "${package} ${result##*:}"
