[zircon][scripts] Don't reuse a build directory with no build.ninja
Also had a message with advice in case something goes awry in the
incremental case.

Bug: BLD-325
Test: manual
Change-Id: I8822f2e615fb9c80ec4767bb0ed2ac68be7cbdc3

diff --git a/zircon/scripts/build-zircon b/zircon/scripts/build-zircon
--- a/zircon/scripts/build-zircon
+++ b/zircon/scripts/build-zircon
@@ -64,8 +64,9 @@ if [[ -z "$BUILDDIR" ]]; then
     BUILDDIR="build-$VARIANT$BUILDDIR_SUFFIX"
 fi
 
-if [[ -r "$BUILDDIR/args.gn" && $# -eq 0 ]]; then
+if [[ -r "$BUILDDIR/args.gn" && -r "$BUILDDIR/build.ninja" && $# -eq 0 ]]; then
     echo >&2 "Reusing existing $BUILDDIR/args.gn"
+    echo >&2 "If Ninja fails confusingly, try: rm -rf $BUILDDIR"
 else
     "$DIR/gn" gen "${GN_SWITCHES[@]}" "$BUILDDIR" --args="
 variants = [ \"$VARIANT\" ]
